### PR TITLE
fix: delete tab character

### PR DESCRIPTION
**Pull request by yigang01**
fix：#3153

### CODE REVIEW

**Comment by yigang01** [comment]
> /重新测试



> /retest

May I ask how to operate it，again commit code？

**Comment by shahar-h** [comment]
Proposal: you can add add a script that validates there are no tabs in chart yaml files by executing the following for each file: 
```shell
grep -q $'\t' <yaml file>
```
This will prevent such cases in future.

**Comment by liorokman** [comment]
This should have been caught by the `yamllint` tool. Maybe something is wrong with how it's being invoked as part of the build?

**Review by liorokman — APPROVED** [review]

**Comment by shahar-h** [comment]
> This should have been caught by the `yamllint` tool. Maybe something is wrong with how it's being invoked as part of the build?

That's because chart is ignored: https://github.com/envoyproxy/gateway/blob/c943042cb61f5248df6bf9f38d555d4222f65c0d/tools/linter/yamllint/.yamllint#L3-L8

**Comment by liorokman** [comment]
But the linter should still be run on the output of the template, after `make generate-manifests` is run.

**Comment by zirain** [comment]
> > This should have been caught by the `yamllint` tool. Maybe something is wrong with how it's being invoked as part of the build?
> 
> That's because chart is ignored:
> 
> https://github.com/envoyproxy/gateway/blob/c943042cb61f5248df6bf9f38d555d4222f65c0d/tools/linter/yamllint/.yamllint#L3-L8

there's a render result located `test/helm/default.yaml`, so I think helm will ignore that.
anyway it's fine to remove it.

**Review by zirain — APPROVED** [review]

**Comment by shahar-h** [comment]
Right, but the output is generated correctly with space indentation.

**Pull request merged**
