### PR TITLE
api: cookie based consistent hashing

### PR DESCRIPTION
**Pull request by arkodg**
Relates to https://github.com/envoyproxy/gateway/issues/2624

Will use this underlying feature in Envoy https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-routeaction-hashpolicy-cookie

### CODE REVIEW

**Comment by arkodg** [comment]
have two opens questions here for @envoyproxy/gateway-maintainers and @envoyproxy/gateway-reviewers 
1. should the `Cookie` structure get split up into two more sub fields - `Existing` and `Generated` to make it easier to divide up the cookie fields, else it can get confusing ?
2. Should the `Attributes` be renamed to `ExtraAttributes` ?

**Comment by zhaohuabing** [comment]
> should the Cookie structure get split up into two more sub fields - Existing and Generated to make it easier to divide up the cookie fields, else it can get confusing ?

One Cookie structure won't cause confusion to me.   Two separate structures seem extreme since there is only one optional `TTL` field. 

>Should the Attributes field be renamed to ExtraAttributes ?

Are there any "built-in" default Attributes? If not, the "Extra" is not needed.

**Comment by arkodg** [comment]
> > should the Cookie structure get split up into two more sub fields - Existing and Generated to make it easier to divide up the cookie fields, else it can get confusing ?
> 
> One Cookie structure won't cause confusion to me. Two separate structures seem excessive since there is only one optional `TTL` field.
> 
> > Should the Attributes field be renamed to ExtraAttributes ?
> 
> Are there any "built-in" default Attributes? If not, the "Extra" is not needed.

TTL field translates into Max-Age attribute

**Comment by zhaohuabing** [comment]
> TTL field translates into Max-Age attribute

Then "Extra" makes sense to me, though I don't have a strong preference for it.

**Review by shawnh2 — APPROVED** [review]

**Comment by shawnh2** [comment]
> 
> 1. should the `Cookie` structure get split up into two more sub fields - `Existing` and `Generated` to make it easier to divide up the cookie fields, else it can get confusing ?
> 
> 2. Should the `Attributes` field be renamed to `ExtraAttributes` ?

1. Just `Cookie` sounds good to me, by the definition here, cookie is only be generated if it is not exist in current request. So it works more like a default option.

2. `Attributes` sounds good too.

**Review by zhaohuabing — APPROVED** [review]
LGTM thanks!

**Pull request merged**
