### PR TITLE
Adds API to Manage Envoy Deployment

### PR DESCRIPTION
**Pull request by danehans**
- Moves `ProviderType` to `api/config/v1alpha1/shared_types.go` since the types are being used by EnvoyGateway and EnvoyProxy APIs.
- Adds `ResourceProvider` type to EnvoyProxy API to define the desired state of supported infrastructure resources.
- Generates DeepCopy methods and CRD manifest.

xref #713

Signed-off-by: danehans <daneyonhansen@gmail.com>

### CODE REVIEW

**Comment by arkodg** [comment]
@danehans this PR looks good, but prefer if we design and the deliver platform customizations in a future release (v0.4.0) so we scope out the exact type of platform customizations the project will support. For e.g. will the project also support HPA based replica fields ?

**Comment by danehans** [comment]
@arkodg thanks for the review and feedback. Since we have multiple requests for providing basic Envoy infra configurability, I disagree that we should wait to provide this feature:

xrefs:
https://github.com/envoyproxy/gateway/issues/713
https://github.com/envoyproxy/gateway/issues/648
https://github.com/envoyproxy/gateway/issues/703

> For e.g. will the project also support HPA based replica fields ?

I see HPA as "advanced configuration" that can be supported in the future.

@Xunzhuo @youngnick @skriss @AliceProxy WDYT?

**Comment by AliceProxy** [comment]
I definitely think that the Envoy infra should be customizable for the end user.

**Comment by danehans** [comment]
> im suggesting delaying this until its part of a roadmap theme

IMHO we would prioritize features that are being requested by users. As I mention in https://github.com/envoyproxy/gateway/pull/766#issuecomment-1337869952, we have multiple requests to provide basic Envoy infra configurability.

**Comment by danehans** [comment]
Per our discussion during the 12/6/22 community meeting, @youngnick @AliceProxy @arkodg agreed to proceed with the general approach of this PR. The approach of this PR is consistent with the EnvoyGateway API and solves Envoy infra configurability that's being requested by the community. Since the API is `alpha`, we can take a broader approach to infra configurability, e.g. exposing `spec`, if we find this approach unmaintainable. @arkodg @AliceProxy @youngnick PTAL at this PR when you have a moment.

**Review by arkodg — APPROVED** [review]

**Review by Xunzhuo — APPROVED** [review]
/lgtm
/approve

**Comment by Xunzhuo** [comment]
/hold

Can we rebase with main before getting this merged?

**Review by AliceProxy — APPROVED** [review]

**Comment by danehans** [comment]
@Xunzhuo @arkodg @AliceProxy per https://github.com/envoyproxy/gateway/pull/766#issuecomment-1341904677 I rebased. Please retag when you have a moment.

**Review by arkodg — APPROVED** [review]

**Pull request merged**
