### PR TITLE
e2e: graceful envoy shutdown

### LINKED ISSUE #2610: E2E Zero DownTime Test when upgrading Envoy Proxy Versions
I executed a naive test:
- Environment: kind, metallb, EG quickstart.yaml
- envoy proxy replicas: 2
- upgrade: 0.6.0 => 0.0.0-latest using `helm upgrade`
- load simulation during upgrade: `hey -c 100 -q 10 -z 300s -host www.example.com http://172.18.255.200/ `  

The upgrade caused some client-facing failures during the test:

```
Error distribution:
  [8]	Get "http://172.18.255.200/": EOF
  [32]	Get "http://172.18.255.200/": dial tcp 172.18.255.200:80: connect: connection refused
  [1]	Get "http://172.18.255.200/": read tcp 172.18.0.1:55220->172.18.255.200:80: read: connection reset by peer
  [1]	Get "http://172.18.255.200/": read tcp 172.18.0.1:55260->172.18.255.200:80: read: connection reset by peer
```
It's probably possible to tune some of the parameters mentioned in my previous comment to achieve a hitless upgrade under certain test conditions (RPS, connection reuse, HTTP version, ...). But, I'm not sure that we can claim to have a hitless upgrade in general, based on such test. 

So, I propose that for the GA scope, we focus on an upgrade test that ensures request convergence to successful execution after the upgrade. A limited hitless upgrade test can be a stretch-goal. 

In the future, we can explore:
- Implementing a graceful envoy shutdown feature and providing guidance on configuring envoy for hitless in-place upgrades
- Supporting canary deployments 

WDYT?

_Originally posted by @guydc in https://github.com/envoyproxy/gateway/issues/1712#issuecomment-1944561296_

### PR DESCRIPTION
**Pull request by guydc**
**What this PR does / why we need it**: 
- Update the upgrade suite to use its own namespace, gatewayclass, envoyproxy, gateway and backend. 
   - The new gatewayclass will have 2 replicas and 15s drain shutdown, which are required for this test to succeed. Increasing the replica count and shutdown drain time for existing gateways causes certain tests like local rate limit to fail and prolongs the suite. 
   - The need for another suite is explained in #2665, as only a single gatewayclass is currently supported in conformance suites
- Adds a test that rolls out the proxy deployment while running load:
  -  Restart is achieved by patching EnvoyProxy resource with a custom restart annotation. 
  - The shutdown manager should ensure that connections are drained gracefully and not closed forcibly. New connections are gradually loadbalanced to the active proxy envoy instance. 
- Small fixes to existing backend upgrade test and moving common parts to utils
- Minor adjustments of the EG upgrade test to the new suite's resources

Future improvements:
- Leverage the HA EnvoyProxy with Shutdown manager as part of the EG upgrade test, and check for hitless upgrades. 
- Move the backend upgrade test into this suite, and restart the upgrade "infra-backend". The current test restarts a common backend, in a way that can affect other tests in the suite.  
- When all limitations are resolved, we can consider merging this suite back into the main suite. 

**Which issue(s) this PR fixes**:
Fixes #2610

### CODE REVIEW

**Comment by guydc** [comment]
blocked on: https://github.com/envoyproxy/gateway/pull/2665#issuecomment-1984987844

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Review by zirain — APPROVED** [review]

**Pull request merged**
