### PR TITLE
feat: Allow configuring tolerations for the EG control plane installed via Helm

### PR DESCRIPTION
**Pull request by coro**
**What this PR does / why we need it**:

Allows the EG operator to be scheduled on nodes with taints. For example, in our cluster, we have a core set of control plane nodes with a `NoSchedule` taint. This PR allows the EG operator to be scheduled on those nodes.

Example Helm values.yaml:
```yaml
deployment:
 pod:
  tolerations:
   - key: "custom.taint"
     operator: "Equal"
     value: "custom.value"
```

This PR also fixes some indentation in the `topologySpreadConstraints` field for the Deployment template - it was inconsistently indented with the rest of the generated manifest.

### CODE REVIEW

**Comment by coro** [comment]
Looks like there's a flake in one of the CI jobs:
```
error - 2024-06-11 13:57:51,299 -- Commit creating failed: {"detail":"Tokenless has reached GitHub rate limit. Please upload using a token: https://docs.codecov.com/docs/adding-the-codecov-token. Expected available in 329 seconds."}
```

Could a maintainer please rerun this test? Thanks!

**Comment by zirain** [comment]
> Looks like there's a flake in one of the CI jobs:
> 
> ```
> error - 2024-06-11 13:57:51,299 -- Commit creating failed: {"detail":"Tokenless has reached GitHub rate limit. Please upload using a token: https://docs.codecov.com/docs/adding-the-codecov-token. Expected available in 329 seconds."}
> ```
> 
> Could a maintainer please rerun this test? Thanks!

you can reply with `/retest` to trigger.

BTW, can you add a test for this new feature?

**Comment by shawnh2** [comment]
add test for this under https://github.com/envoyproxy/gateway/tree/main/test/helm

**Comment by coro** [comment]
@zirain @shawnh2 Added tests, thanks for the pointer. Note I had to change the type of the `topologySpreadConstraints` as it was previously an `object` instead of a `list`.

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Review by zirain — APPROVED** [review]

**Review by shawnh2 — APPROVED** [review]
LGTM! Thanks for adding this!

**Pull request merged**
