### PR TITLE
docs: move announcements on top

### PR DESCRIPTION
**Pull request by Xunzhuo**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

image

### CODE REVIEW

**Comment by Xunzhuo** [comment]
https://gateway.xunzhuo.cafe/announcements

**Review by zirain — APPROVED** [review]

**Comment by zirain** [comment]
skip other tests(e2e, conformance and so on) if there's no code update?

**Comment by arkodg** [comment]
umm, should we combine `Blogs` & `Announcements` ?

**Comment by zirain** [comment]
It's OK for me now, maybe in the future, `Announcements ` is part of `News`.

**Comment by Xunzhuo** [comment]
image

IMO, News and Blogs should be better to separate.

Blogs content should be open to all communities, like user-case sharing, or tech-guides.
Announcements should be maintained by maintainers/release-manager to upload offical content from the project.

cc @arkodg @zirain WDYT?

**Comment by zirain** [comment]
> image
> IMO, News and Blogs should be better to separate.
> 
> Blogs content should be open to community/end-user/contributor, like user-case sharing, or tech-guides/tutorials. And we should encourage end-users to contribute some blogs/experience around eg. Announcements should be maintained by maintainers/release-manager to upload offical content from the project.
> 
> cc @arkodg @zirain WDYT?

that's what I mean.

**Review by cnvergence — APPROVED** [review]

**Pull request merged**
