### PR TITLE
feat(helm): support affinity configuration for EnvoyGateway pod

### PR DESCRIPTION
**Pull request by shahar-h**
**What type of PR is this?**
Feature - Add support for affinity configuration in `EnvoyGateway` pod.

**What this PR does / why we need it**:
A sample use case for affinity configuration is making `EnvoyGateway` HA on different nodes (By adding AntiAffinity rule).

**Which issue(s) this PR fixes**: N/A

### CODE REVIEW

**Review by zirain — CHANGES_REQUESTED** [review]
please add a test for this

**Comment by shahar-h** [comment]
> please add a test for this

How? There is currently no concept of helm chart testing in this repo unless I missed it.

**Comment by zirain** [comment]
you can add an unit test or e2e

**Comment by shahar-h** [comment]
@zirain Since I only made changes to helm chart, the only test that I could think of is a test that executes `helm template` with custom values and validates the output. However, there are no such tests currently. Do you want me to introduce a new concept of helm tests? something like [this](https://github.com/gruntwork-io/terratest/tree/master/examples/helm-basic-example)? If yes, should it be part of this PR or maybe it requires a prior discussion? Any other options that you can think of?

**Comment by zirain** [comment]
I'm thinking of adding golden file test.

**Comment by shahar-h** [comment]
So something like [this](https://medium.com/@zelldon91/advanced-test-practices-for-helm-charts-587caeeb4cb#2f01)? Should I start implement it in the current PR or it needs a further discussion on a separate issue?

**Comment by shahar-h** [comment]
@zirain After reading a bit about golden files tests I feel that it should not be in the scope of this PR, and it requires a further discussion as part of a new issue.

**Review by zirain — APPROVED** [review]

**Review by zhaohuabing — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
