### PR TITLE
feat: support cluster settings for tracing and accesslog backends

### LINKED ISSUE #3069: Support cluster settings for non-xRoute BackendRefs
*Description*:
Currently, Envoy Gateway supports a variety of envoy cluster settings through the `BackendTrafficPolicy` resource, such as:
- TCP Keep Alive
- Timeouts
- Health Checks
- Load Balancing algorithm
- Circuit Breakers

Envoy Gateway is adopting the use of `BackendRef` to represent external services in various resources, such as SecurityPolicy (ExtAuth), EnvoyExtensionPolicy (ExtProc), EnvoyProxy (OTEL sinks). With this change, reuse of existing backend-traffic policies that attach to Services, such as `BackendTLSPolicy`, is now possible for these backends. However, it's not possible to attach a `BackendTrafficPolicy` to Services. As a result, the above-mentioned cluster settings are not configurable for non-xRoute referenced backends. 

**Options:**
1. Split BackendTrafficPolicy to two policies. One policy will contain all fields that have an affinity to Envoy listeners (retries, rate limits, Fault... ) and will attach to `Gateway` and `xRoutes`, while the other will contain all fields that have affinity to Envoy Clusters and will attach to `Services`. 
2. Support attachment of BackendTrafficPolicy to Services.
3. Create an extended BackendRef resource that supports configuration of relevant cluster settings, similar to support for weights in Gateway-API: https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.BackendRef

### PR DESCRIPTION
**Pull request by liorokman**
Fixes #3069

### CODE REVIEW

**Comment by liorokman** [comment]
The E2E tests are failing because the WASM module can't be found:

``` 
        message: 'Wasm: wasm module download failed after 1 attempts, last error:
          wasm module download request failed: status code 404.'
```

This reproduces when trying manually as well:

```
wget https://raw.githubusercontent.com/envoyproxy/envoy/main/examples/wasm-cc/lib/envoy_filter_http_wasm_example.wasm
--2024-08-08 12:50:37--  https://raw.githubusercontent.com/envoyproxy/envoy/main/examples/wasm-cc/lib/envoy_filter_http_wasm_example.wasm
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-08-08 12:50:37 ERROR 404: Not Found.
```

@guydc @zirain any ideas how to get this to work?

**Comment by guydc** [comment]
CC @zhaohuabing

**Comment by liorokman** [comment]
Checking the Envoy repository, it seems that the examples were moved to their own repository recently: https://github.com/envoyproxy/envoy/commit/56be4f40fc5c90b6dd15a5242470c1fcf7ee4222 

The links probably need to be updated in this repository.

**Comment by zirain** [comment]
@liorokman can you open an issue to track and disable those tests?

**Comment by liorokman** [comment]
> @liorokman can you open an issue to track and disable those tests?

Once #4014 is merged, I'll rebase and these tests will start working correctly.

**Review by zirain — APPROVED** [review]
LGTM, thanks!

**Comment by guydc** [comment]
Thanks!

**Review by guydc — APPROVED** [review]

**Pull request merged**
