### PR TITLE
chore: Update Envoy proxy image to envoy:distroless-dev in main

### PR DESCRIPTION
**Pull request by davidalger**
**What this PR does / why we need it**:

This PR updates the Envoy proxy image used to distroless dev builds for the `main` branch.

### CODE REVIEW

**Review by zirain — APPROVED** [review]
LGTM

I recall istio want to use distroless by default, but there are a lot of historical problems.

**Comment by zhaohuabing** [comment]
EG should pin a specific envoy version and use a distroless image when releasing v1.0.0. But I think it's ok to use non-distroless dev images at the moment?

**Comment by davidalger** [comment]
@zhaohuabing The main reason for this is so we're testing and building with the same Envoy base image build EG is released with. Fully on board with pinning specific versions for EG releases and using the latest dev build for EG main branch; but I see it as a risk, albeit a minor one, to be building and testing with an ubuntu base when EG will pin and release with distroless builds of Envoy. The EG image used for dev is already distroless.

Is it often needed to jump into the Envoy containers with a shell for debug purposes? My experience could be different of than others working on the project of course but it isn't something I've needed to do.

**Review by arkodg — APPROVED** [review]

**Comment by arkodg** [comment]
@zhaohuabing, imo if we feel debugging pain, we should surface it in a GH issue and try and and solve it with `egctl`.
Using the `distroless` flavor in `main` and releases ensures lesser surprises (like [this](https://github.com/envoyproxy/gateway/pull/2633#discussion_r1493036329) one )

**Pull request merged**
