### PR TITLE
ci: enable ipv6/dual test

### PR DESCRIPTION
**Pull request by zirain**

### CODE REVIEW

**Comment by zhaohuabing** [comment]
@zirain Do we need configure Kubernetes and Github nodes for IPv6/Dual-stack support?

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Comment by arkodg** [comment]
cc @juwon8891, when the ipFamily listener e2e tests are added, we'll need to only run it on the ipv6 and dual enabled clusters

**Comment by zirain** [comment]
After https://github.com/envoyproxy/ratelimit/pull/748 merged still need some code change to pass ipv6 test.

**Comment by arkodg** [comment]
thanks @zirain, can we track this with a issue - "Global Ratelimit doesnt working for ipv6 only cluster"

**Comment by zirain** [comment]
the dual stack actually didn't work as expected, because RateLimit only work in IPv4 mode, it's not a real dual.

**Comment by zhaohuabing** [comment]
Should we cherry-pick this to v1.2 branch and upgrade the ratelimit image after https://github.com/envoyproxy/ratelimit/pull/748 ?

**Comment by zirain** [comment]
> Should we cherry-pick this to v1.2 branch and upgrade the ratelimit image after [envoyproxy/ratelimit#748](https://github.com/envoyproxy/ratelimit/pull/748) ?

I don't think envoyproxy/ratelimit#748 will be merged soon.

**Comment by zirain** [comment]
```console
Error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):

error decoding 'service.telemetry': failing to parse metrics address "fd00:10:244::16:8888": address fd00:10:244::16:8888: too many colons in address
2024/10/29 01:07:28 collector server run finished with error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):

error decoding 'service.telemetry': failing to parse metrics address "fd00:10:244::16:8888": address fd00:10:244::16:8888: too many colons in address
```

**Comment by zirain** [comment]
wait https://github.com/envoyproxy/gateway/pull/4559 and https://github.com/envoyproxy/gateway/pull/4525

**Comment by zirain** [comment]
More errors:
```cnosole
2024-10-29T10:01:56.1526498Z === RUN   TestE2E/FileAccessLog
2024-10-29T10:01:56.1527650Z     conformance.go:72: 2024-10-29T10:01:56.150860034Z: Applying testdata/accesslog-file.yaml
2024-10-29T10:01:56.1542009Z     apply.go:271: 2024-10-29T10:01:56.153913758Z: Creating accesslog-file HTTPRoute
2024-10-29T10:01:56.1600215Z === RUN   TestE2E/FileAccessLog/Positive
2024-10-29T10:01:56.1660350Z     helpers.go:609: 2024-10-29T10:01:56.165689139Z: Route gateway-conformance-infra/accesslog-file expected 1 Parents got 0
2024-10-29T10:01:57.1659483Z     helpers.go:609: 2024-10-29T10:01:57.165604331Z: Conditions matched expectations
2024-10-29T10:01:57.1661907Z     helpers.go:609: 2024-10-29T10:01:57.165654616Z: Route gateway-conformance-infra/accesslog-file Parents matched expectations
2024-10-29T10:01:57.1683656Z     accesslog.go:58: 2024-10-29T10:01:57.167930535Z: Making GET request to http://[fc00:f853:ccd:e793::cb]/file
2024-10-29T10:01:57.1685288Z     roundtripper.go:219: 2024-10-29T10:01:57.168145919Z: Sending Request:
2024-10-29T10:01:57.1686149Z         < GET /file HTTP/1.1
2024-10-29T10:01:57.1687179Z         < Host: [fc00:f853:ccd:e793::cb]
2024-10-29T10:01:57.1687750Z         < User-Agent: Go-http-client/1.1
2024-10-29T10:01:57.1688172Z         < X-Echo-Set-Header: 
2024-10-29T10:01:57.1688839Z         < X-Envoy-Logged: 1
2024-10-29T10:01:57.1689523Z         < Accept-Encoding: gzip
2024-10-29T10:01:57.1690065Z         < 
2024-10-29T10:01:57.1690485Z         < 
2024-10-29T10:01:57.1690908Z         
2024-10-29T10:01:57.1691327Z         
2024-10-29T10:02:00.2328419Z     http.go:235: 2024-10-29T10:02:00.232468573Z: Request failed, not ready yet: Get "http://[fc00:f853:ccd:e793::cb]/file": dial tcp [fc00:f853:ccd:e793::cb]:80: connect: no route to host (after 1.333µs)
```

**Comment by zirain** [comment]
```
k logs -n gateway-conformance-infra grpc-ext-auth-67d997ccdf-cxfmj
go: downloading github.com/envoyproxy/go-control-plane v0.12.0
go: downloading github.com/golang/protobuf v1.5.4
go: downloading google.golang.org/genproto/googleapis/rpc v0.0.0-20240304212257-790db918fca8
go: downloading google.golang.org/grpc v1.62.1
main.go:15:2: github.com/envoyproxy/go-control-plane@v0.12.0: Get "https://proxy.golang.org/github.com/envoyproxy/go-control-plane/@v/v0.12.0.zip": dial tcp: lookup proxy.golang.org on [fd00:10:96::a]:53: server misbehaving
main.go:16:2: github.com/envoyproxy/go-control-plane@v0.12.0: Get "https://proxy.golang.org/github.com/envoyproxy/go-control-plane/@v/v0.12.0.zip": dial tcp: lookup proxy.golang.org on [fd00:10:96::a]:53: server misbehaving
main.go:17:2: github.com/golang/protobuf@v1.5.4: Get "https://proxy.golang.org/github.com/golang/protobuf/@v/v1.5.4.zip": dial tcp: lookup proxy.golang.org on [fd00:10:96::a]:53: server misbehaving
main.go:18:2: google.golang.org/genproto/googleapis/rpc@v0.0.0-20240304212257-790db918fca8: Get "https://proxy.golang.org/google.golang.org/genproto/googleapis/rpc/@v/v0.0.0-20240304212257-790db918fca8.zip": dial tcp: lookup proxy.golang.org on [fd00:10:96::a]:53: server misbehaving
main.go:19:2: google.golang.org/genproto/googleapis/rpc@v0.0.0-20240304212257-790db918fca8: Get "https://proxy.golang.org/google.golang.org/genproto/googleapis/rpc/@v/v0.0.0-20240304212257-790db918fca8.zip": dial tcp: lookup proxy.golang.org on [fd00:10:96::a]:53: server misbehaving
main.go:20:2: google.golang.org/grpc@v1.62.1: Get "https://proxy.golang.org/google.golang.org/grpc/@v/v1.62.1.zip": dial tcp: lookup proxy.golang.org on [fd00:10:96::a]:53: server misbehaving
main.go:21:2: google.golang.org/grpc@v1.62.1: Get "https://proxy.golang.org/google.golang.org/grpc/@v/v1.62.1.zip": dial tcp: lookup proxy.golang.org on [fd00:10:96::a]:53: server misbehaving
```

**Pull request closed without merging**
