### PR TITLE
Update GatewayClass status based on EnvoyProxy validation

### PR DESCRIPTION
**Pull request by arkodg**
* Refactor EnvoyProxy's `Validate` API
* If a GatewayClass references a `EnvoyProxy` resource, ensure that that the `GatewayClass` status condition is based off the EnvoyProxy validation result

Relates to https://github.com/envoyproxy/gateway/issues/31

### CODE REVIEW

**Comment by arkodg** [comment]
@Xunzhuo, Im unable to generate the manifests for the webhook by adding the `kubebuilder` annotations to the file and running `make manifests`, has something changed with the helm stuff ?

**Comment by Xunzhuo** [comment]
Nothing changes except the output path in make manifests.

Can you tell where,what annotations you add? I will have a try too

@arkodg

**Comment by zirain** [comment]
kindly ping @arkodg , are you still working on this?

**Comment by arkodg** [comment]
> kindly ping @arkodg , are you still working on this?

yes 😅  will resume next week

**Comment by arkodg** [comment]
Below logs highlight that the the `Accepted` condition is set to `False` with a reason of `InvalidParameters` when validation fails on the referenced `EnvoyProxy` resource
```
🐳 ~/go-workspace/src/github.com/envoyproxy/gateway$ kubectl get envoyproxy/ep-config -n envoy-gateway-system -o yaml
apiVersion: config.gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"config.gateway.envoyproxy.io/v1alpha1","kind":"EnvoyProxy","metadata":{"annotations":{},"name":"ep-config","namespace":"envoy-gateway-system"},"spec":{"bootstrap":"blah","logging":{"level":{"system":"debug"}}}}
  creationTimestamp: "2023-04-05T21:58:31Z"
  generation: 2
  name: ep-config
  namespace: envoy-gateway-system
  resourceVersion: "5009"
  uid: ee973c95-a96f-49f3-90ec-233349dbe1bc
spec:
  bootstrap: blah
  logging:
    level:
      system: debug
🐳 ~/go-workspace/src/github.com/envoyproxy/gateway$ kubectl get gc/eg -o yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.networking.k8s.io/v1beta1","kind":"GatewayClass","metadata":{"annotations":{},"name":"eg"},"spec":{"controllerName":"gateway.envoyproxy.io/gatewayclass-controller","parametersRef":{"group":"config.gateway.envoyproxy.io","kind":"EnvoyProxy","name":"ep-config","namespace":"envoy-gateway-system"}}}
  creationTimestamp: "2023-04-05T21:54:21Z"
  finalizers:
  - gateway-exists-finalizer.gateway.networking.k8s.io
  generation: 2
  name: eg
  resourceVersion: "31384"
  uid: 0db8dcfd-b3f7-4cff-8c82-acedc388b78f
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: config.gateway.envoyproxy.io
    kind: EnvoyProxy
    name: ep-config
    namespace: envoy-gateway-system
status:
  conditions:
  - lastTransitionTime: "2023-04-05T22:10:54Z"
    message: 'Invalid parametersRef: unable to unmarshal user bootstrap: proto: syntax
      error (line 1:1): unexpected token "blah"'
    observedGeneration: 2
    reason: InvalidParameters
    status: "False"
    type: Accepted
    ```

**Comment by zirain** [comment]
what's the expected behavior when apply a wrong `EnvoyProxy`? EG use last correct `EnvoyProxy`?
what will happen when EG control plane restarts after a wrong `EnvoyProxy` applied?

**Comment by arkodg** [comment]
> what's the expected behavior when apply a wrong `EnvoyProxy`? EG use last correct `EnvoyProxy`?
> what will happen when EG control plane restarts after a wrong `EnvoyProxy` applied?

thanks for raising this, even w/o this PR we were failing fast -  removing the `GatewayClass` from being accepted if `EnvoyProxy` was invalid, causing entire deletion of data plane. Imo this should be discussed in a separate issue if we want to handle this more gracefully

**Review by zirain — APPROVED** [review]
Overall LGTM, can you open a ticket for the discussion?

**Review by AliceProxy — APPROVED** [review]

**Pull request merged**
