### PR TITLE
add shortnames for EG CRDs

### PR DESCRIPTION
**Pull request by arkodg**
* `btp` for `BackendTrafficPolicy`
* `ctp` for `ClientTrafficPolicy`
* `sp` for `SecurityPolicy`
* `epp` for `EnvoyPatchPolicy`
* `eproxy` for `EnvoyProxy`

### CODE REVIEW

**Comment by zirain** [comment]
`eproxy` sounds bad.

**Comment by arkodg** [comment]
@zirain any suggestions? ep is taken by Endpoint

**Comment by zirain** [comment]
> @zirain any suggestions? ep is taken by Endpoint

what about `envoy` or `proxy` ?

**Review by AliceProxy — APPROVED** [review]
lgtm. I have no issues with `eproxy` personally.

**Review by cnvergence — APPROVED** [review]
lgtm

**Pull request merged**
