### PR TITLE
doc: update user and design documentation due to removal of AuthenticationFilter  and RateLimitFilter CRD resource.

### PR DESCRIPTION
**Pull request by tmsnan**
**What type of PR is this?**
Documentation needs to be updated due to removal of AuthenticationFilter and RateLimitFilter CRD resource

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Releated 
https://github.com/envoyproxy/gateway/pull/2079
[Documentation needs to be updated due to removal of AuthenticationFilter CRD resource](https://gateway.envoyproxy.io/latest/user/rate-limit/#rate-limit-jwt-claims)
#2196

### CODE REVIEW

**Review by zirain — COMMENTED** [review]
cc @arkodg @zhaohuabing

**Review by zhaohuabing — APPROVED** [review]
LGTM. Thanks for updating the docs.

**Comment by arkodg** [comment]
@tmsnan this is the design doc, so we probably need to also update the design decisions mentioning that `RateLimitFilter` has been merged into the `BackendTrafficPolicy`

**Comment by tmsnan** [comment]
> @tmsnan this is the design doc, so we probably need to also update the design decisions mentioning that `RateLimitFilter` has been merged into the `BackendTrafficPolicy`

Yes, Should we keep the rate-limit documentation by using subsetting, or should we remove it directly and only update it in the backend-traffic-policy?

**Review by Xunzhuo — COMMENTED** [review]
Should we sync it also to site/content/en/v0.6.0 ?

**Comment by tmsnan** [comment]
> Should we sync it also to site/content/en/v0.6.0 ?

Need to feed back to the already released v0.6.0 version.  In order to keep the document consistent, I will synchronize.

**Review by Xunzhuo — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
