### PR TITLE
docs: update config types doc

### LINKED ISSUE #1247: make crd-ref-docs support gateway-api object
https://github.com/envoyproxy/gateway/actions/runs/4594246649/jobs/8113043059?pr=1246

### PR DESCRIPTION
**Pull request by zirain**
**What type of PR is this?**

docs: update config types doc

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #1247

### CODE REVIEW

**Review by arkodg — APPROVED** [review]
should the fields (`gateway`, `provider`) be under a top level `spec` field

**Comment by zirain** [comment]
let me investigate why it's changed

**Comment by zirain** [comment]
@arkodg the root cause is here:
https://github.com/envoyproxy/gateway/blob/5c2d453387b65b4e367fa9eb5eca988d5ea19098/api/config/v1alpha1/envoygateway_types.go#L27

**Comment by arkodg** [comment]
Ah this is the startup config, so this style is fine

**Review by arkodg — APPROVED** [review]

**Review by AliceProxy — APPROVED** [review]

**Pull request merged**
