### PR TITLE
chore: add flags to skopeo to prevent errors

### PR DESCRIPTION
**Pull request by Xunzhuo**
Signed-off-by: bitliu <bitliu@tencent.com>

### CODE REVIEW

**Comment by Xunzhuo** [comment]
https://github.com/containers/skopeo/issues/1874, we need to find a way to resolve skopeo copy failure. Or use another way to copy/push image in release workflow.

**Comment by Xunzhuo** [comment]
https://github.com/Xunzhuo/gateway/actions/runs/4081249218/jobs/7034468056 I have tested in my fork, it works.

**Comment by Xunzhuo** [comment]
https://github.com/Xunzhuo/gateway/releases/tag/v1.1.1

**Review by danehans — APPROVED** [review]

**Comment by arkodg** [comment]
these flags will now unfortunately force users to update `docker` else they will see the below error
```
unknown flag: --sbom
See 'docker buildx build --help'.
make[1]: *** [image.push.multiarch] Error 125
make: *** [_run] Error 2
```

**Comment by Xunzhuo** [comment]
> these flags will now unfortunately force users to update `docker` else they will see the below error
> 
> ```
> 
> unknown flag: --sbom
> 
> See 'docker buildx build --help'.
> 
> make[1]: *** [image.push.multiarch] Error 125
> 
> make: *** [_run] Error 2
> 
> ```

Yes..  Another approach is to update skope in release workflow. The default version of skope in Ubuntu is too old.

**Pull request merged**
