### PR TITLE
fix(chart): set ttlSecondsAfterFinished on certgen job to 30 by default

### PR DESCRIPTION
**Pull request by JuniorJPDJ**
This is painless workaround for ArgoCD bug: argoproj/argo-cd#6880

### CODE REVIEW

**Review by zhaohuabing — APPROVED** [review]
@JuniorJPDJ  Thanks for coming up the workaroud for using EG with ArgoCD. Is it because ArgoCD needs the job to exist for a while before it is finished?

**Comment by arkodg** [comment]
thanks for raising this ! I think `30s` also works here. 
weighing the pros and cons of setting this as a default - I believe the con of this is slower clean up (pressure on the k8s API server) ?

**Comment by JuniorJPDJ** [comment]
@zhaohuabing probably. It's not specified anywhere in the ArgoCD docs, but ArgoCD freezes forever on sync phase when job is deleted too quickly.

60s also allows to read logs without much timing pressure ;)

@arkodg you are probably right, but I'm not sure if it creates any pressure, and if it does, its so small and done only when upgrading/installing the chart, as it's just a hook

**Comment by arkodg** [comment]
> @zhaohuabing probably. It's not specified anywhere in the ArgoCD docs, but ArgoCD freezes forever on sync phase when job is deleted too quickly.
> 
> 60s also allows to read logs without much timing pressure ;)
> 
> @arkodg you are probably right, but I'm not sure if it creates any pressure, and if it does, its so small and done only when upgrading/installing the chart, as it's just a hook

cool, lets get this in, can we reduce this to `30` ?

**Comment by JuniorJPDJ** [comment]
I've not seen any problems, but let me try in my setup again first.
Give me a few minutes :D

**Comment by arkodg** [comment]
@JuniorJPDJ can you run `make generate` and commit the changes

**Comment by JuniorJPDJ** [comment]
rebased and `make generate`d

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Pull request merged**
