### PR TITLE
Fixes image.build target

### LINKED ISSUE #753: EG Image Fails to Build
Running on MacOS:

```
$ go env | grep GOOS
GOOS="darwin"
$ go env | grep GOARCH
GOARCH="amd64"
```

```
$ make image
===========>  Building binary envoy-gateway with commit 8327af8 for darwin amd64
CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o /Users/daneyonhansen/go/src/github.com/envoyproxy/gateway/bin/darwin/amd64/envoy-gateway -ldflags "-X github.com/envoyproxy/gateway/internal/cmd/version.EnvoyGatewayVersion=v0.2.0 -X github.com/envoyproxy/gateway/internal/cmd/version.GitCommitID=8327af84c19050b344a76d94f02d0fd30c4822fb" github.com/envoyproxy/gateway/cmd/envoy-gateway
===========>  Building image envoy-gateway in tag 8327af8 for darwin/amd64
===========>  Creating image tag docker.io/envoyproxy/envoy-gateway:8327af8 for amd64
DOCKER_BUILDKIT=1 docker build --platform darwin/amd64 --pull -t docker.io/envoyproxy/gateway-dev:8327af8 -f /Users/daneyonhansen/go/src/github.com/envoyproxy/gateway/tools/docker/envoy-gateway/Dockerfile bin
[+] Building 0.4s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                  0.0s
 => => transferring dockerfile: 37B                                   0.0s
 => [internal] load .dockerignore                                     0.0s
 => => transferring context: 2B                                       0.0s
 => ERROR [internal] load metadata for gcr.io/distroless/static:nonr  0.3s
------
 > [internal] load metadata for gcr.io/distroless/static:nonroot:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:ed05c7a5d67d6beebeba19c6b9082a5513d5f9c3e22a883b9dc73ec39ba41c04: not found
make[1]: *** [image.build.linux_amd64.envoy-gateway] Error 1
make: *** [_run] Error 2
```

Docker Desktop version:
```
$ docker version
Client:
 Cloud integration: v1.0.29
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:01:18 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.14.1 (91661)
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:19 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### PR DESCRIPTION
**Pull request by danehans**
Fixes #753 

Signed-off-by: danehans <daneyonhansen@gmail.com>

### CODE REVIEW

**Review by AliceProxy — APPROVED** [review]
Still works for me with these changes on Linux so lgtm

**Review by Xunzhuo — COMMENTED** [review]
/hold

The reason why make image failed is that the platform should be default as linux not darwin.

**Comment by Xunzhuo** [comment]
We should set platform to linux when building image on macOS.

Moving go.build cannot resolve this issue:)

**Comment by danehans** [comment]
> Moving go.build cannot resolve this issue:)

Moving go.build did resolve the issue in my testing. However, I'll look into setting the default to linux instead.

**Comment by danehans** [comment]
@Xunzhuo I have updated the PR to override the `PLATFORM` for the Kube Makefile, PTAL. I took this approach b/c I still want to call `make build` and have EG built for Darwin.

**Comment by danehans** [comment]
Superseded by https://github.com/envoyproxy/gateway/pull/764.

**Pull request closed without merging**
