### PR TITLE
chore: unify log

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Loong Dai <loong.dai@intel.com>

Introduce log function to unify log.
Usage:

```
target:
   @$(LOG_TARGET)
   @$(call log, "log info")

### CODE REVIEW

**Review by kflynn — APPROVED** [review]

**Comment by arkodg** [comment]
@daixiang0 can you attach the o/p of `make help`, TIA !

**Comment by daixiang0** [comment]
@arkodg do you mean add colored output? `make help` does not need it since the `log` would print `====>` as the prefix.

**Comment by arkodg** [comment]
> @arkodg do you mean add colored output? `make help` does not need it since the `log` would print `====>` as the prefix.

meant can you share the output of `make help` in this PR so its easier to validate your changes rather than pulling your branch locally and testing it :)

**Comment by daixiang0** [comment]
`make help` output:
```
root:[gateway]$ make help
make[1]: Entering directory '/root/github/gateway'
Envoy Gateway is an open source project for managing Envoy Proxy as a standalone or Kubernetes-based application gateway

Usage:
  make <Target> <Option>

Targets:

Golang
  build            Build envoy-gateway for host platform. See Option PLATFORM and BINS.
  build-multiarch  Build envoy-gateway for multiple platforms. See Option PLATFORMS and IMAGES.
  test             Run all Go test of code sources.
  format           Update dependences with mod tidy.
  clean            Remove all files that are created during builds.

Image
  image            Build docker images for host platform. See Option PLATFORM and BINS.
  image-multiarch  Build docker images for multiple platforms. See Option PLATFORMS and IMAGES.
  push             Push docker images to registry.
  push-multiarch   Push docker images for multiple platforms to registry.

Lint
  lint             Run all linter of code sources, including golint, yamllint, whitenoise lint and codespell.

Kubernetes Development
  manifests        Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects.
  generate         Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
  kube-test        Run Kubernetes provider tests.

Kubernetes Deployment
  kube-install     Install CRDs into the Kubernetes cluster specified in ~/.kube/config.
  kube-uninstall   Uninstall CRDs from the K8s cluster specified in ~/.kube/config. Call with ignore-not-found=true to ignore resource not found errors during deletion.

Kubernetes Build Dependencies
  kustomize        Download kustomize locally if necessary.
  controller-gen   Download controller-gen locally if necessary.
  envtest          Download envtest-setup locally if necessary.

Options:
  MAKE_IN_DOCKER
                 Run make inside a Docker container which has all the preinstalled tools needed to support all the make targets
                 This option is available to all cmds.
                 Example: make build MAKE_IN_DOCKER=1
  BINS
                 The binaries to build. Default is all of cmd.
                 This option is available when using: make build|build-multiarch
                 Example: make build BINS="envoy-gateway"
  IMAGES
                 Backend images to make. Default is all of cmds.
                 This option is available when using: make image|image-multiarch|push|push-multiarch
                 Example: make image-multiarch IMAGES="envoy-gateway"
  PLATFORM
                 The specified platform to build.
                 This option is available when using: make build|image
                 Example: make build BINS="envoy-gateway" PLATFORM="linux_amd64""
                 Supported Platforms: linux_amd64 linux_arm64 darwin_amd64 darwin_arm64
  PLATFORMS
                 The multiple platforms to build.
                 This option is available when using: make build-multiarch
                 Example: make build-multiarch BINS="envoy-gateway" PLATFORMS="linux_amd64 linux_arm64"
                 Default is "linux_amd64 linux_arm64 darwin_amd64 darwin_arm64".
make[1]: Leaving directory '/root/github/gateway'
```

**Comment by daixiang0** [comment]
`make clean`:
```
root:[gateway]$ make clean
make[1]: Entering directory '/root/github/gateway'
make[2]: Entering directory '/root/github/gateway'
make[3]: Entering directory '/root/github/gateway'
===========>  Cleaning all build output
make[3]: Leaving directory '/root/github/gateway'
make[2]: Leaving directory '/root/github/gateway'
make[1]: Leaving directory '/root/github/gateway'
```

Actually this PR does not change much, just unifies.

**Review by arkodg — APPROVED** [review]

**Pull request merged**
