### PR TITLE
chore: bump codespell from 2.2.4 to 2.2.5

### PR DESCRIPTION
**Pull request by zirain**
fixes: #1549

### CODE REVIEW

**Comment by arkodg** [comment]
did some digging, looks like `codespell` intentionally moved to `requester` from `requestor` https://github.com/codespell-project/codespell/pull/2845

We should probably do the same instead of adding an ignore word, i.e. change the instances of `requestor` to `requester`

**Comment by arkodg** [comment]
haha, good catch, this is going to be an interesting chain of GH issues

**Comment by zirain** [comment]
address followup: https://github.com/envoyproxy/gateway/issues/1572

**Review by arkodg — APPROVED** [review]
approving for now, since we have a follow up issue to track the spelling drama

**Pull request merged**
