### PR TITLE
more tests in experimental conformance profile report

### PR DESCRIPTION
**Pull request by arkodg**

### CODE REVIEW

**Review by zirain — APPROVED** [review]

**Comment by arkodg** [comment]
something is broken in the conformance framework, ive disabled the mesh feature, but the tests still run
cc @Xunzhuo

**Comment by Xunzhuo** [comment]
This is sn upstream bug. I manually remove them before

**Comment by arkodg** [comment]
blocked on https://github.com/kubernetes-sigs/gateway-api/pull/2515

**Comment by arkodg** [comment]
hey @Xunzhuo where's the report artifact :) ?

**Comment by Xunzhuo** [comment]
https://github.com/envoyproxy/gateway/actions/runs/6648815440?pr=2056

@arkodg

**Comment by arkodg** [comment]
thanks 
looks like we should work on enabling the skipped tests before v0.6
```
apiVersion: gateway.networking.k8s.io/v1alpha1
date: "2023-10-26T02:53:47Z"
gatewayAPIVersion: TODO
implementation:
  contact:
  - https://github.com/envoyproxy/gateway/blob/main/GOVERNANCE.md
  organization: envoyproxy
  project: envoy-gateway
  url: https://github.com/envoyproxy/gateway
  version: latest
kind: ConformanceReport
profiles:
- core:
    result: partial
    skippedTests:
    - GatewaySecretInvalidReferenceGrant
    statistics:
      Failed: 0
      Passed: 9
      Skipped: 1
    summary: ""
  name: TLS
- core:
    result: partial
    skippedTests:
    - GatewaySecretInvalidReferenceGrant
    - GatewayWithAttachedRoutes
    statistics:
      Failed: 0
      Passed: 27
      Skipped: 2
    summary: ""
  extended:
    result: partial
    skippedTests:
    - HTTPRouteRewritePath
    statistics:
      Failed: 0
      Passed: 11
      Skipped: 1
    summary: ""
    supportedFeatures:
    - HTTPRoutePortRedirect
    - HTTPRoutePathRedirect
    - HTTPRouteRequestTimeout
    - HTTPRouteQueryParamMatching
    - HTTPRouteRequestMultipleMirrors
    - HTTPRoutePathRewrite
    - HTTPRouteBackendTimeout
    - HTTPRouteSchemeRedirect
    - HTTPRouteHostRewrite
    - HTTPRouteRequestMirror
    - HTTPRouteMethodMatching
    - HTTPRouteResponseHeaderModification
  name: HTTP
```

**Review by Xunzhuo — APPROVED** [review]

**Pull request merged**
