### PR TITLE
Support setting idle timeout time function based on data flow

### LINKED ISSUE #3108: e2e: Idle Timeout in ClientTrafficPolicy
*Description*:
Test this feature e2e.

relates to #2861

### PR DESCRIPTION
**Pull request by bjlhlin**
**What type of PR is this?**

feat: Support setting idle timeout time function based on data flow
**What this PR does / why we need it**:
EG currently does not support setting idle timeout times based on data streams. This PR supports this feature
**Which issue(s) this PR fixes**:

Fixes #3108

### CODE REVIEW

**Comment by shawnh2** [comment]
This PR seems does not fix #3108 (adding an end-to-end test for current idleTimeout api), please change it, if the issue you are trying to fix does not exist, feel free to create a new one.

**Comment by arkodg** [comment]
the PR doesnt match the issue, the issue talks about adding an e2e and the PR is adding a new API field for `StreamIdleTimeout`

**Comment by shawnh2** [comment]
close in favour of #3672

**Pull request closed without merging**
