### PR TITLE
docs(observability): add grafana integration docs along with sample dashboards

### LINKED ISSUE #1764: Show Grafana Integration in docs
*Description*:
https://github.com/envoyproxy/gateway/pull/1745 adds docs for integrating envoy proxy metrics into prometheus.

It would be great to also include grafana integration in the docs with a pre built dashboard
seeing an old one here https://grafana.com/grafana/dashboards/6693-envoy/

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

### PR DESCRIPTION
**Pull request by psinghal20**
**What type of PR is this?**

**What this PR does / why we need it**:
This PR adds a doc for integrating Grafana and Prometheus to visualize Envoy Proxy metrics. This PR also adds sample dashboards for users to get started. 

**Which issue(s) this PR fixes**:

Fixes #1764

### CODE REVIEW

**Comment by arkodg** [comment]
thanks for adding these dashboards @psinghal20 !

can you take a snapshot of the dashboard with some data and include it in the docs ?

**Review by arkodg — APPROVED** [review]
LGTM thanks !
ptal @Xunzhuo @zirain

**Comment by zirain** [comment]
what about to release these dashboards to https://grafana.com/grafana/dashboards/?

**Comment by psinghal20** [comment]
These dashboards are based on the Grafana dashboards already available at https://grafana.com/grafana/dashboards/. I had to make several changes to get the panels working with EG. We can reupload on the Grafana portal with these changes if required.

**Comment by arkodg** [comment]
Yeah I'd suggest creating the workflow of pushing the dashboards as a follow up issue

**Comment by zirain** [comment]
> These dashboards are based on the Grafana dashboards already available at https://grafana.com/grafana/dashboards/. I had to make several changes to get the panels working with EG. We can reupload on the Grafana portal with these changes if required.

can you open an issue track this?

**Review by zirain — APPROVED** [review]

**Comment by psinghal20** [comment]
Filed a follow-up issue: https://github.com/envoyproxy/gateway/issues/2018

PS: I don't think I have merge rights on the repo(earlier I did, I think?) but if the PR is ready to be merged, can someone merge this? It is ready from my end.

**Comment by zirain** [comment]
Thanks @psinghal20

**Pull request merged**
