### PR TITLE
docs: Fix global rate limit doc for sourceCIDR type

### PR DESCRIPTION
**Pull request by owenhaynes**
**What this PR does / why we need it**:
Fix's the doc to use the correct enum names for the sourceCIDR type for global rate limiting.  This could be a bug in the translator but this fixes the doc in case it not.

### CODE REVIEW

**Review by zhaohuabing — APPROVED** [review]
LGTM thanks!

**Comment by arkodg** [comment]
can you also update `site/content/en/v1.0.1/tasks/traffic/global-rate-limit.md` with the same diff, tia !

**Comment by owenhaynes** [comment]
@arkodg this has been done.

**Review by zirain — APPROVED** [review]

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Pull request merged**
