### PR TITLE
update Envoy to v1.24

### PR DESCRIPTION
**Pull request by skriss**
Signed-off-by: Steve Kriss <krisss@vmware.com>

### CODE REVIEW

**Comment by arkodg** [comment]
thanks for bumping this, any specific reason apart from running envoy with the latest image features and fixes ?
took a peek into the release notes https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.24/v1.24.0 and the only thing that stood out was `total_weight` being deprecated (all we'll need to do is delete the line)
https://github.com/envoyproxy/gateway/blob/6f540b51db45fefd95ca13f6f9ec9f835c3c3f7d/internal/xds/translator/route.go#L165

**Comment by skriss** [comment]
> thanks for bumping this, any specific reason apart from running envoy with the latest image features and fixes ?

Just that; I figure as an Envoy-aligned project we'll want to keep pretty up-to-date with the latest and greatest. It also helps us stay on top of deprecations/etc.

> the only thing that stood out was total_weight being deprecated (all we'll need to do is delete the line)

Something to consider here is that if we immediately drop that deprecated field, then it's possible it could cause issues during upgrades from previous versions of EG to this new version -- the EG control plane gets upgraded, and before all the data planes have been upgraded, it sends out an xDS config that does not contain this field, which is invalid for older versions of Envoy. In Contour we tend to upgrade Envoy in one release, and then address deprecations / start making use of new features from that Envoy version in the next Contour release, which tends to avoid this issue. Maybe it's too soon to worry about this for EG, but wanted to raise it for consideration. The other thing we need to think about is EG's release cadence relative to Envoy's -- if we're only releasing every 6mo, while Envoy is every quarter, then we may need to do skip some minor versions of Envoy, which could be tricky. IMO we should consider shipping quarterly as well to align with Envoy, but maybe 2-4 weeks after new Envoy minor versions come out so we can pick them up.

**Comment by arkodg** [comment]
thanks for raising those issues, agree with the depreciation strategy
also agree we consider we should consider quarterly releases, something we can discuss in the next community meeting

**Comment by danehans** [comment]
I agree that EG should coincide with Envoy. If so, we need to review the milestones, roadmap, etc and realign.

**Comment by danehans** [comment]
@skriss do you mind creating issues or agenda topics to address the release cadence and depreciation strategy?

**Comment by lizan** [comment]
> Something to consider here is that if we immediately drop that deprecated field, then it's possible it could cause issues during upgrades from previous versions of EG to this new version -- the EG control plane gets upgraded, and before all the data planes have been upgraded, it sends out an xDS config that does not contain this field, which is invalid for older versions of Envoy.

total_weights has been optional for quite a while so I believe it is safe to remove in this case.

**Review by arkodg — APPROVED** [review]

**Comment by danehans** [comment]
> do you mind creating issues or agenda topics to address the release cadence and depreciation strategy?

xref https://github.com/envoyproxy/gateway/issues/663

**Pull request merged**
