### PR TITLE
Run all core and extended conformance tests

### PR DESCRIPTION
**Pull request by arkodg**
Signed-off-by: Arko Dasgupta <arko@tetrate.io>

### CODE REVIEW

**Comment by Xunzhuo** [comment]
The response header modifer is not getting merged yet, so it failed as expectations.

**Comment by arkodg** [comment]
blocked on https://github.com/envoyproxy/gateway/issues/781 https://github.com/envoyproxy/gateway/issues/782 https://github.com/envoyproxy/gateway/issues/783 https://github.com/envoyproxy/gateway/issues/784 https://github.com/envoyproxy/gateway/issues/657

**Comment by danehans** [comment]
@arkodg https://github.com/envoyproxy/gateway/pull/793 adds the `HTTPRouteReferenceGrant` conformance test.

**Comment by arkodg** [comment]
raised https://github.com/kubernetes-sigs/gateway-api/issues/1638 to help ensure that we can easily run all tests (core and extended) automatically after updating to a newer gateway-api released version

**Comment by arkodg** [comment]
moving this out to 0.4.0 since its unlikely the redirect tests issue will be resolved in the next few days before the v0.3.0 release

**Comment by arkodg** [comment]
closing this issue since the skipped tests can be tracked with individual issues

**Pull request closed without merging**
