### PR TITLE
Add ClusterIP to the services in the egctl test data

### PR DESCRIPTION
**Pull request by Ronnie-personal**
**What type of PR is this?** fix: fix egctl test data, also add endpoints ValidateAll().

**What this PR does / why we need it**:  xds endpoint configuration requires address under socketAddress field. We need to provide ClusterIP in the input data file.

**Which issue(s) this PR fixes**: #1742 

Fixes #

### CODE REVIEW

**Comment by arkodg** [comment]
thanks @Ronnie-personal ! does this allow you to add the `ValidateAll()` method back for Endpoints ?

**Comment by Ronnie-personal** [comment]
> thanks @Ronnie-personal ! does this allow you to add the `ValidateAll()` method back for Endpoints ?

Yes, we will be able to add  endpoints ValidateAll(), after this change.
I tested locally, egctl tests passed with ValidateAll() in place.

**Comment by arkodg** [comment]
Can you add ValidateAll into this PR as well ?

**Comment by Ronnie-personal** [comment]
> Can you add ValidateAll into this PR as well ?

Sure, will do.

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Review by zirain — APPROVED** [review]

**Pull request merged**
