### PR TITLE
Adds Cherry-Pick Steps to Release Doc

### PR DESCRIPTION
**Pull request by danehans**
Adds steps for cherry-picking commits from `main` into the release branch.

Signed-off-by: danehans <daneyonhansen@gmail.com>

### CODE REVIEW

**Comment by danehans** [comment]
cc: @Xunzhuo

**Comment by danehans** [comment]
CI failed due to https://github.com/envoyproxy/gateway/issues/1016 flake.

**Comment by danehans** [comment]
CI failed due to https://github.com/envoyproxy/gateway/issues/1016 flake.

**Comment by danehans** [comment]
Waiting for https://github.com/envoyproxy/gateway/pull/1021 to merge and will then rerun CI.

**Review by arkodg — APPROVED** [review]
thanks for adding the note on cherrypick commits b/w rc and release

**Pull request merged**
