### PR TITLE
docs: Fix commands for testing jwt based routing

### LINKED ISSUE #3242: docs: jwt based routing commands miss host header
*Description*:

[jwt based routing commands](https://gateway.envoyproxy.io/v1.0.1/tasks/traffic/http-routing/#jwt-claims-based-routing) miss host header which ends up 404.

*Repro steps*:
```bash
 $ curl -v -H "Authorization: Bearer $TOKEN" "http://${GATEWAY_HOST}/"
*   Trying 20.115.176.94:80...
* Connected to 20.115.176.94 (20.115.176.94) port 80 (#0)
> GET / HTTP/1.1
> Host: 20.115.176.94
> User-Agent: curl/8.1.2-DEV
> Accept: */*
> Authorization: Bearer ... >
< HTTP/1.1 404 Not Found
< date: Mon, 22 Apr 2024 08:45:13 GMT
< content-length: 0
<
* Connection #0 to host 20.115.176.94 left intact
```

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
>Include the access logs and the Envoy logs.

### PR DESCRIPTION
**Pull request by biefy**
Fix commands for testing jwt based routing.

**What type of PR is this?**
docs: Fix commands for testing jwt based routing

**What this PR does / why we need it**:
The commands used for testing jwt based routing miss host headers which cause 404.

**Which issue(s) this PR fixes**:
https://github.com/envoyproxy/gateway/issues/3242

Fixes #3242 commands for testing jwt based routing

### CODE REVIEW

**Review by zhaohuabing — APPROVED** [review]
LGTM thanks！

**Review by zirain — APPROVED** [review]

**Review by zirain — APPROVED** [review]

**Comment by arkodg** [comment]
thanks @biefy , can you also update site/content/en/latest/tasks/traffic/http-routing.md as well ?

**Comment by biefy** [comment]
Thanks @arkodg. Updated the latest http-routing.md.

**Review by zirain — APPROVED** [review]

**Review by zhaohuabing — APPROVED** [review]

**Pull request merged**
