### PR TITLE
e2e: move als test resources out of the base

### PR DESCRIPTION
**Pull request by zirain**
replace: https://github.com/envoyproxy/gateway/pull/3865

### CODE REVIEW

**Comment by zirain** [comment]
wait https://github.com/envoyproxy/gateway/pull/3885

**Comment by zirain** [comment]
ep didn't updated after envoy-als became ready.

**Comment by zirain** [comment]
wait https://github.com/envoyproxy/gateway/pull/3895

**Review by zhaohuabing — APPROVED** [review]
Thanks for cleaning this!

**Review by shawnh2 — APPROVED** [review]
/retest

**Pull request merged**
