### PR TITLE
Bump to gateway api v0.7.0

### PR DESCRIPTION
**Pull request by arkodg**
* Release notes https://github.com/kubernetes-sigs/gateway-api/releases/tag/v0.7.0
* Also re enable redirect tests except  `HTTPRouteRedirectPortAndScheme` 

Fixes: https://github.com/envoyproxy/gateway/issues/992
Fixes: https://github.com/envoyproxy/gateway/issues/993
Fixes: https://github.com/envoyproxy/gateway/issues/994

### CODE REVIEW

**Review by zirain — CHANGES_REQUESTED** [review]
wait for v0.7.0?

**Review by kflynn — APPROVED** [review]
In general, I think we should track all the Gateway API releases, given how infrequent they are. Let's go ahead and land this. 🙂

**Review by zirain — DISMISSED** [review]

**Comment by zirain** [comment]
add a cherrypick label for action testing, please kindly ignore.

**Comment by Xunzhuo** [comment]
/hold

```
Error: test/conformance/conformance_test.go:55:3: unknown field ValidUniqueListenerPorts in struct literal of type suite.Options
FAIL	github.com/envoyproxy/gateway/test/conformance [build failed]
```

**Comment by zirain** [comment]
wait v0.7.1 because of https://github.com/kubernetes-sigs/gateway-api/pull/2024

**Review by zirain — APPROVED** [review]

**Review by Xunzhuo — APPROVED** [review]
Great

**Pull request merged**
