### PR TITLE
add udproute support to kubernetes provider

### PR DESCRIPTION
**Pull request by zhaohuabing**
This PR is a part of https://github.com/envoyproxy/gateway/issues/641

An example of UDPRoute

```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: coredns
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: coredns
      port: 53
```

Signed-off-by: zhaohuabing <zhaohuabing@gmail.com>

### CODE REVIEW

**Comment by arkodg** [comment]
thanks for adding the last piece wrt UDPRoute support !
recommend adding a test case in https://github.com/envoyproxy/gateway/blob/5d11bbe13cb2d3e61364ac641346d610b923cc60/internal/provider/kubernetes/predicates_test.go#L170 to increase coverage for this PR
would also be great if you can attach a rough example of UDPRoute works in this PR (docs can be added later)

**Comment by zhaohuabing** [comment]
I got the following error running envoy gateay

```text
2022-12-22T04:09:56.838Z	ERROR	controller/controller.go:211	Could not wait for Cache to sync	{"runner": "provider", "controller": "gatewayapi", "error": "failed to wait for gatewayapi caches to sync: timed out waiting for cache to be synced"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.1
	/Users/huabingzhao/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.0/pkg/internal/controller/controller.go:211
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/Users/huabingzhao/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.0/pkg/internal/controller/controller.go:216
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/Users/huabingzhao/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.0/pkg/internal/controller/controller.go:242
sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1
	/Users/huabingzhao/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.0/pkg/manager/runnable_group.go:219
2022-12-22T04:09:56.839Z	INFO	manager/internal.go:576	Stopping and waiting for non leader election runnables	{"runner": "provider"}
```

It seems that I have missed something. @arkodg  do you have any idea which part is missing or wrong?

**Comment by zhaohuabing** [comment]
I built an image from the latest code with this PR and got the following error running envoy gateway

```text
2022-12-22T04:09:56.838Z	ERROR	controller/controller.go:211	Could not wait for Cache to sync	{"runner": "provider", "controller": "gatewayapi", "error": "failed to wait for gatewayapi caches to sync: timed out waiting for cache to be synced"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.1
	/Users/huabingzhao/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.0/pkg/internal/controller/controller.go:211
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/Users/huabingzhao/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.0/pkg/internal/controller/controller.go:216
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/Users/huabingzhao/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.0/pkg/internal/controller/controller.go:242
sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1
	/Users/huabingzhao/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.0/pkg/manager/runnable_group.go:219
2022-12-22T04:09:56.839Z	INFO	manager/internal.go:576	Stopping and waiting for non leader election runnables	{"runner": "provider"}
```

I'm not sure that this error comes from my PR or somewhere else. @arkodg  do you have any idea on this?

**Comment by zhaohuabing** [comment]
I also don't know how to add UDPRoute related permission to the cluterrole. I tried to modify internal/provider/kubernetes/config/rbac/role.yaml, but it won't pass the test.

**Comment by arkodg** [comment]
hey @zhaohuabing you probably need to enhance https://github.com/envoyproxy/gateway/blob/main/internal/provider/kubernetes/rbac.go
and run `make generate` and `make manifests` after

**Comment by arkodg** [comment]
LGTM @zhaohuabing ! were you able to get end to end traffic from a client to a backend working ?

**Comment by zhaohuabing** [comment]
> LGTM @zhaohuabing ! were you able to get end to end traffic from a client to a backend working ?

I got it working after fixing a xds translation issue. 

I deployed a coredns to test UDP route, and it can be accessed successfully from within another pod by dig command. The only problem is that it seems that gateway udp port can only be accessed by pod ip, but can not with its service IP. It seems like an issue of KIND and is not relevant to UDPRoute implementation.

**Review by Xunzhuo — APPROVED** [review]
Looks good! Can you add a doc for end user to introduce UDP route usage in a separated PR?

**Comment by arkodg** [comment]
lets get this in for, keep the issue open, until the docs reflect the working case, thanks again @zhaohuabing

**Comment by zhaohuabing** [comment]
Sure I will add the doc later.

**Pull request merged**
