### PR TITLE
feat: support mergeGateways in EnvoyPatchPolicy

### PR DESCRIPTION
**Pull request by cnvergence**
**What type of PR is this?**

feat: support mergeGateways in EnvoyPatchPolicy

**What this PR does / why we need it**:
Support EnvoyPatchPolicy when MergeGateways is enabled and make sure that it targets GatewayClass instead Gateway. As when mergeGateways is enabled, there will be one Envoy deployment for all Gateways in the cluster.

**Which issue(s) this PR fixes**:

Fixes https://github.com/envoyproxy/gateway/issues/2308

### CODE REVIEW

**Comment by arkodg** [comment]
@cnvergence this does make sense, can you please expand on the WHY in the PR description ?

you will also need to update the validation logic https://github.com/envoyproxy/gateway/blob/bf8eaa45b268b2ebf73e44bc3300c73daf51ef67/internal/gatewayapi/envoypatchpolicy.go#L69 to make sure targetRef type is `KindGatewayClass` when `mergeGateways` is true

this feature will also require some additional docs to explain this to the end user

**Comment by cnvergence** [comment]
@arkodg right, I will add this to the GatewayClass level
Also need to fix this https://github.com/envoyproxy/gateway/issues/2308#issuecomment-1864576614

**Comment by cnvergence** [comment]
nvm, it works as expected

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Review by zirain — APPROVED** [review]

**Pull request merged**
