### PR TITLE
fix: Gateway-target BTP ignored when route timeout defined

### LINKED ISSUE #4844: BackendTrafficPolicy attached to Gateway has no affect in case timeouts are configured on HTTPRoute
*Description*:
When creating a `BackendTrafficPolicy` which is attached to gateway, and configuring some timeout on `HTTPRoute`(either `request` or `backendRequest`), `BackendTrafficPolicy` has no affect. 
In case `BackendTrafficPolicy` is attached to `HTTPRoute` everything works.

*Repro steps*:
1. Create a KiND cluster:
```shell
kind create cluster
```
2. Install latest EG chart and enable backend:
```shell
helm upgrade --install eg oci://docker.io/envoyproxy/gateway-helm \
  --version v0.0.0-latest \
  -n envoy-gateway-system \
  --create-namespace \
  --set config.envoyGateway.extensionApis.enableBackend=true \
  --wait
```
3. Apply the following manifests:
```shell
cat <<EOF | kubectl apply -f -
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: config
    namespace: envoy-gateway-system
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: config
  namespace: envoy-gateway-system
spec:
  telemetry:
    accessLog:
      settings:
      - format:
          type: JSON
          json:
            start_time: "%START_TIME%"
            method: "%REQ(:METHOD)%"
            x-envoy-origin-path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
            protocol: "%PROTOCOL%"
            upstream_protocol: "%UPSTREAM_PROTOCOL%"
            response_code: "%RESPONSE_CODE%"
            response_code_details: "%RESPONSE_CODE_DETAILS%"
            x-envoy-upstream-service-time: "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"
            user-agent: "%REQ(USER-AGENT)%"
            :authority: "%REQ(:AUTHORITY)%"
            upstream_host: "%UPSTREAM_HOST%"
            upstream_local_address: "%UPSTREAM_LOCAL_ADDRESS%"
            downstream_local_address: "%DOWNSTREAM_LOCAL_ADDRESS%"
            downstream_remote_address: "%DOWNSTREAM_REMOTE_ADDRESS%"
            requested_server_name: "%REQUESTED_SERVER_NAME%"
            route_name: "%ROUTE_NAME%"
        sinks:
        - type: File
          file:
            path: /dev/stdout
---
apiVersion: v1
kind: Namespace
metadata:
  name: consumer        
---
apiVersion: v1
kind: Secret
metadata:
  name: examplecom-cert
  namespace: consumer
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUYwVENDQTdtZ0F3SUJBZ0lVU282VFFmem9XS2JEOWplT016aWx1SjhvL0hBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2VERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dQpaRzl1TVJnd0ZnWURWUVFLREE5SGJHOWlZV3dnVTJWamRYSnBkSGt4RnpBVkJnTlZCQXNNRGxJbVJDQkVaWEJoCmNuUnRaVzUwTVJRd0VnWURWUVFEREF0bGVHRnRjR3hsTG1OdmJUQWVGdzB5TkRBek1qQXhNek0wTXpCYUZ3MHkKTlRBek1qQXhNek0wTXpCYU1IZ3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWURWUVFJREFaTWIyNWtiMjR4RHpBTgpCZ05WQkFjTUJreHZibVJ2YmpFWU1CWUdBMVVFQ2d3UFIyeHZZbUZzSUZObFkzVnlhWFI1TVJjd0ZRWURWUVFMCkRBNVNKa1FnUkdWd1lYSjBiV1Z1ZERFVU1CSUdBMVVFQXd3TFpYaGhiWEJzWlM1amIyMHdnZ0lpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQ0R3QXdnZ0lLQW9JQ0FRQzJwQzQ0T21wYmxYeWNXQkNKVEFMUGNmUlF3Y2tYNlFubwpWcDNjd3BHcEtqYkE4T1grc3o3UzJ2TzY5T1NSTmtMRVpLTlB3Ui9qUFpyd2N2TlhCZjZNTFlBVHczbGdaUUxxCjhOMXhqRmtlSks1Sml5dFI5MjNaZUNoOHFxY0RtNW05dVA2YzErcGtQV2tCRGRkUTJSeEIwbkI1QU9zc0hLSTYKZmlWTjZzb3FRNDkvTjd6MUhIWDdKODdhNlZZVFBlanF5Qkp4UnBCZC8wUldnQ1IySUE0M2x4Ny9yOGlRaURKRgpMWHdMNzB0RTZXRlhOQkEwR1JEUG0xUFQ0ODB6VlJ4V1cxTHpoMlowaDNkTkhDdGVnVERZWk5ZTE1KQTBxRU1GCmpMQytXRHI4dW1DUDBMUDR2eWVEODNtNG9QTDRsVUVvaURJWGRwMkI0Qk96YWlmVlQrTnQrcmxXUE9PL0tlRzkKdk5VbnlvM3FDeVR0S3NMcTlRTFdEK1MzWjd6dUJuTUdRZm5HN0JrSi9SVnpPcENoOE9PdzB5SjlBYUFJZ3U0VQpSWkpUQy9LVlVZdVZtaDRKSHNxVjhTQ0IxVEhhUElHRFE4VGNERlp5TE9ab0wrYVg5U0FMTkZZaCtiZEVSTXZFClZHaGVzSUhTTm4zbmdabjBVeDNldWJWK2dBMVUyajJuZmJ1MTVla0VCb3dHLzFReGlqVDZnc0E5alcrQVpiR20KQWl5b2l4V2NSWEtOQWM3MTlzK1RkMWNiZUtmdTRxQmh6SG1wdTBxMFQ1bDJCU0dUL3BxUWdIM2dsZ3VvSGNGZApJK2RnUFJtajZ3a3kzdHN0OVczd05zYStkdFJtYVIvRUROTzNhQXZZQUxOUDJUNUU3bkZwMWtzQ2xaQVp4SkFSCnUzUEFYdU4vZlFJREFRQUJvMU13VVRBZEJnTlZIUTRFRmdRVW5vN3FESUcyOTdDY1NWRUNHUEgxNjBnN2tGOHcKSHdZRFZSMGpCQmd3Rm9BVW5vN3FESUcyOTdDY1NWRUNHUEgxNjBnN2tGOHdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBZ0VBVGMzYlBmMGFybGZsbG9XMnVPQ3VTNGxrN0MxU0pnSGF5M29DCm84YXh5MmEwZ3R3YmhpYzZ0OExVUE1zL0NOUEhzbHM3MHVaN3c4WFlxQWRHZUVRMFE5UUlsOXBDTTJ3cDk5Q2MKWmMwd2FwcXlWa2pNT2pGNTAzNWtGUlNTZkhQNThJVitnUGg4eEVaWjFVUHR2ZWM3bXgybTFJOHFCYVB6dkFwcwplVWwyYkxlcW5LYXdXa2EvT3BuZTQzejBmL0sxRktaRGlGb2R4WXZJWmFOU0FzYjMvWWx3RVpOOFBnWDVka2NxClQ1UjU3TkhBazZ5OHIxRjRLTDBxQWpmRDFoN1JGK3dXZkczODJDVy9IVzh3ZkNaODl2TTF3SnpYOTR3RDVxNVYKOUhzWTJYOXlSUzVPV3ZpTVZpTlpLVGZydWFBaDhIYkVTdnd5b2VKSlN5RmIwNWZPZ3dLWHk4cytSdVN6THM5VwoweE5SNm0wb0VwTlJ6OC8yYTY2UGI5cFkrbWt1RXQ1NlVlV2NZZjE3eXdSa1JicmVoazh0dGJ0cWtydGJqdlVsCnFwbng0MEttOUJJU3JrRGwza3E5M3JGdnkzTjY2SlIzY2llaCtKRU5SSTdtSkZucTNpT1VhbWkzay9jS2thci8Ka2RYTkYxRHNTWHcxcjJEN3JNRE5Icldrb1NPM3RTOWtOd0pMbWhsVll6bEtVazBjSklLQXRDTDdGNVlwSU45SQpYVjVlaG5OdkdrYWo5c29pQVZlNzhFOGcwcnNuMUZwWEsyVVEvTVZzWlBxb0dQbERCVW5kaEpUbHg0UHl5SEh0CkJ2S0poTktJaHVOM1RuQzdnZTNWV2ZpNjJST0d1NG5vNVhVVlFMZmw2Z20wVXFWbXFZWDU0VjZaRjFWODl5YnMKWm5QRWhFQT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQ1N3d2dna29BZ0VBQW9JQ0FRQzJwQzQ0T21wYmxYeWMKV0JDSlRBTFBjZlJRd2NrWDZRbm9WcDNjd3BHcEtqYkE4T1grc3o3UzJ2TzY5T1NSTmtMRVpLTlB3Ui9qUFpydwpjdk5YQmY2TUxZQVR3M2xnWlFMcThOMXhqRmtlSks1Sml5dFI5MjNaZUNoOHFxY0RtNW05dVA2YzErcGtQV2tCCkRkZFEyUnhCMG5CNUFPc3NIS0k2ZmlWTjZzb3FRNDkvTjd6MUhIWDdKODdhNlZZVFBlanF5Qkp4UnBCZC8wUlcKZ0NSMklBNDNseDcvcjhpUWlESkZMWHdMNzB0RTZXRlhOQkEwR1JEUG0xUFQ0ODB6VlJ4V1cxTHpoMlowaDNkTgpIQ3RlZ1REWVpOWUxNSkEwcUVNRmpMQytXRHI4dW1DUDBMUDR2eWVEODNtNG9QTDRsVUVvaURJWGRwMkI0Qk96CmFpZlZUK050K3JsV1BPTy9LZUc5dk5VbnlvM3FDeVR0S3NMcTlRTFdEK1MzWjd6dUJuTUdRZm5HN0JrSi9SVnoKT3BDaDhPT3cweUo5QWFBSWd1NFVSWkpUQy9LVlVZdVZtaDRKSHNxVjhTQ0IxVEhhUElHRFE4VGNERlp5TE9abwpMK2FYOVNBTE5GWWgrYmRFUk12RVZHaGVzSUhTTm4zbmdabjBVeDNldWJWK2dBMVUyajJuZmJ1MTVla0VCb3dHCi8xUXhpalQ2Z3NBOWpXK0FaYkdtQWl5b2l4V2NSWEtOQWM3MTlzK1RkMWNiZUtmdTRxQmh6SG1wdTBxMFQ1bDIKQlNHVC9wcVFnSDNnbGd1b0hjRmRJK2RnUFJtajZ3a3kzdHN0OVczd05zYStkdFJtYVIvRUROTzNhQXZZQUxOUAoyVDVFN25GcDFrc0NsWkFaeEpBUnUzUEFYdU4vZlFJREFRQUJBb0lDQUJkbk9OUDBLa3BEZ0xUdzlPZCs4YkkrCnhpRnQvM1JjcEd3YzR6d1ZRNEJ6ZkJJam5Ea1RvMVoxLzNyQ3BDSTJXMzVhYmZITGk2Zzg3ZVJuT21hNWlpbFEKc0VONERnN0x5c0NycmhoOWRUTHZYTlRvTEJ3ajhqUEdXWnZGNjBKRFYwTXdHQklsZWErd0RjczRpSkZmektiagpqZzEzVUdzMTNSVFZNcmNHQWJOQ05ucEUvR1hGS0pvTyt3cmlrT2pFeTFxQVdocWhRZUVGazI1cEc2TDJUeFFRCi9ZUWlkSGNPdUxCVUdIdllCU05XcTJZMjhlZVhHYWdjblhSK2tYNEZKeTBxcFJtM0RTb2I3SzNaRVBhYVk5V3EKc0NHOWJwRU15WS9GdkNVYjNhMGlQYnJYOGFQTGJNY1Q5Ukl6TDRjcWF1L0VhZlRIT240WXBqV2NnZStydmJiVAp0bXRCWDhuUW1YeG5jZFFRQ3pEb2piWjFCQ1V2T1pPQWNZYUNjbHdoWlA4M1BVb2lxL2doWjlLZEdGQW01dWNTCkdwaE0xR1hRclJHcHB3TkFQRldjQWlRZDBNelYwenFQVkZyWTBleC9zanFzR1JLUVRDN2hrb0pQeDJWVW9NK1kKdHJqUzUwdC9xc1htd01uQlFTQTRtY2FvRzdKZVRQSVNicTgrdXFnYXZCTEF2M2tzSXlCWTI1UkUrMjI2VmZWRQp5SENQSGdwR0lvcFE0Mk9OTnF5WE1IZklSVjlwRFBldFNKT25jc25kV1hZMEFLNkE1SXV1bUpiMllJdlMwRG13CktVN2dMZ1VweHJydmQvT3F1VUZENDZHYnZ1QTZZeU1kRVY5VGhLemFnNE5XMTlvcUdUNlJTTWhCZFEvVmpPVm0KTjQ1Ump4SjZkMVRwYjJmUmJqUXBBb0lCQVFEb0pHeFFaSnZsbUlPVkZXTkJpWHh0c1pNR2MyMmkvOHNoSkdaZApCWHp2bkRPRWR4bFpaUS9lcEYzV0ludU5acndrNGl2QjVvdnZ2SGI2aWZjdlVpM3hqZ1lpWHlEZmgwM0hXZFc3Ci9FSmFTMnNrY3BnZDB3bjA1MlNvRzBaREpiODVLUWRHVnE5UTd2ek1MRXI4cmhMcU1tOGszWUlVUjlxWFRKKzUKSGNTazVPa2E5N0lqSkRvcWRsUlVJVDM5YzI0WG5sOVQ0MjJpOWxkY0UvcFBNaXB3Z1c3eUl3bkN4MjRXc09XagpzN1NidU1keXhNMUZ6aTRjeGpLanYwUnYxREJYMzY5RnFmblRGT0ZhWllEVXgvZmUyVUw0UVozaEJxSmpXVFl0Ckc3dC90WnZYaEtIbUJpYmVsQ1Q4aGhGRmZORDRrdkwzaCtPK3FnWmFob2cxd1o0RkFvSUJBUURKYVdmc0JkV3gKOGNDUUd1NVRWNFBHLzBDTEVmVlhXcHdYUlpDcjBwK3pIUUtVQ1V6OS8wV1VRZkJkSzJ0M25SNGIxRytvekZCYwozOHlnNk11VVZKQStlUkJoT2x0TWc1RzhRM3d0Nmt0Nmd3YUgwSE5PNzNmOGtmdC9KVVI2d2pUVDJXcDlXdm5ICjMzSFk4NVBKN3BNQlJkeGVwVmNBQ1VsL1p1ZjhhbjBxcGhzU1FkbFN2cTFIOXFrMWgrOXpBWitaM2JlczgwWVYKVjZIclJFeEU4MTcvSTFkZFVYQ0gwbUZCbzVGU2YzcHZTVmx6UjF4MTRaZkN4WThIUWJ0c1cwaTJSMk1tRHFWdgpRQ2lXMm5hMkZGS1lNSmUwcHRic3lSendIeWNYaVZST3Zib09zZFNLSkRlSnRsQzFkaFI0bDdaOFhsb2lBSTd0Cjg0bVpQSitYYXAwWkFvSUJBQnMxK2NSS3BzTjQ1eU9ZaURQc2E3dG43elg0WGNlWGVEWUFVRWRqRjB2MjRVc0wKc3RyNXI2eUhVOEIvOWorUzVVYmxnLytNaUthblRzTDdYUkFjNyttNm5obDFVU01pZHdtQkRENm15UmhRY3RTbwo0Zy9NNXdQZ0E3cDR4L21pK1JFNEwvUWN3UndaaDJSZlpNTE5uTVg2OTNBNHpzQ1YwNWVja2JSZk91ZWhOWG5GCnd3bS9lMW55Mk51cnNkcDlwMC81Ym04azMzc1VxUlRQK3ExQjBodXg4RkZOcmgwNHh6eTlxNDFPeVVMZm0vRm0KQkRIRWd6ODRORU5oYmlJMW14MFJ5VGUvUHR0eFBTRWRlTVo0VWlPN0Q5Q04wSFhLRTByVjhEWEZaR3NKM0tTYwpsV1dqSHZkRUlqbS9kVkxSMktUcWhMUmpKMXo0RFJxYlhtZit0QWtDZ2dFQVRXTTNyK05LQ1hZbkUvZVZET2E2ClZsS3JIUVJJYlVqK1lwNnpDS0lFQkpFbjlYTmhadEtYakhDTmgyN3dldVFldG5pNGNuWVdocWppK2d5WWRDVE4KeTRNK3ZPenNPWWp3RFJNcytvTmtmdTByTERIMnJDU3N5Sm5hdFM2L2toOWVwdXVKMUNLSmlMZWRDY3dGUS9ocgorWGc3UlE1b1VEWkJURGRnK1laOUUwOEJaZEZ4VEM3QmE3NGxvOURZT3lzcmhMWkJKYTNQaHRIR0FCeWM1WDFSClNkenRhNGlvSVRlL2NMWUZWMXB0MDZhdVBQSDFYOEhQU3VJWG82VW8rMmhUbHQzMUJhRnBCVWIwa1luZFJQYW8KQ1p2YUhtcGdlRmlKeXVWZFl0aThVUWpySFV4TXFzdGhuNE15blphQ0pSZTk0U2xybmxieWxCRVlGSTNMa0NWQgp1UUtDQVFFQTJYMnc5OTdvUUx3NUNtMnc5TXlveVY5ZSt4VU9GVkNZSmsxYUxCRWZ0aE9mbHJnZERxb0dLZ015CkxUN1lsUDhUN2Y1bGJCYVoycGV2b1dneHg0SWVDSnhURDNzV3RLYVZSSjFCNm52aVcwSTBpVmgxMFZrY1l0cTQKY0ptR2hNTEVseXREaUhOZmllMUdvaW0vVndSRTRXaHFNUmJiWDB3MkRYckFOUmRybmJMaC9JUmliL2FHV0xERAorV0VDK1RjQTBFSTVFUk9rUVJvVDBUc20zUEpZaDZaYnViV1l0U3NiRWtCdGRsRkV6WUs3Z0F4STBGVms1MmsvCnFqV0twbTFBaFpTbGI4R2h5NER2QjBnM0tLRWk2SFczM09HUStmK3NBM0lTczUra3hGQVB1OXBPcGVXMmYzbjEKRHh5cFkzVjlvOFBMN0hLcVZrNCs1VVJ6MDRrR1RnPT0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
  namespace: consumer
spec:
  gatewayClassName: eg
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: example.com
      tls:
        mode: Terminate
        certificateRefs:
          - name: examplecom-cert
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: httpbin
  namespace: consumer
spec:
  endpoints:
    - fqdn:
        hostname: httpbin.org
        port: 443 
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: httpbin
  namespace: consumer
spec:
  targetRefs:
    - group: gateway.envoyproxy.io
      kind: Backend
      name: httpbin
  validation:
    wellKnownCACertificates: System
    hostname: httpbin.org
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin
  namespace: consumer
spec:
  parentRefs:
    - name: eg
  hostnames:
    - example.com
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: httpbin
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: eg
  namespace: consumer
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
  useClientProtocol: true
EOF
```
4. Get envoy service name:
```shell
export ENVOY_SERVICE=$(kubectl get svc -n envoy-gateway-system --selector=gateway.envoyproxy.io/owning-gateway-name=eg -o jsonpath='{.items[0].metadata.name}')
```
5. port-forward to envoy service:
```shell
kubectl -n envoy-gateway-system port-forward service/${ENVOY_SERVICE} 8443:443 &
```
6. Curl the backend through Envoy proxy:
```shell
curl -kv --resolve example.com:8443:127.0.0.1 "https://example.com:8443/get"
```
7. Get envoy logs:
```shell
kubectl logs -n envoy-gateway-system -l app.kubernetes.io/name=envoy
```
8. Verify `protocol":"HTTP/2"` and `"upstream_protocol":"HTTP/2"` should appear in latest access log.
9. Add request timeout to HTTPRoute:
```shell
kubectl -n consumer patch httproute httpbin --type='json' -p='[{"op": "add", "path": "/spec/rules/0/timeouts", "value":{"request":"5m0s"}}]'
```
10.  Curl the backend through Envoy proxy:
```shell
curl -kv --resolve example.com:8443:127.0.0.1 "https://example.com:8443/get"
```
11. Get envoy logs:
```shell
kubectl logs -n envoy-gateway-system -l app.kubernetes.io/name=envoy
```
12. Now `protocol":"HTTP/2"` and `"upstream_protocol":"HTTP/1.1"` should appear in latest access logs, which means `useClientProtocol` didn't work.

Root cause:
When `HttpRoute` with configured timeout is processed `irRoute.Traffic` is updated with `Timeout` value:  https://github.com/envoyproxy/gateway/blob/4a4c17993245cf02c7ef16a289124e60b2325b36/internal/gatewayapi/route.go#L280-L282

At a later point, when `BackendTrafficPolicy` is processed for a given route, it is skipped in case `r.Traffic != nil` since it assumes that `Traffic` map was set by a policy that is attached to `HttpRoute` :  https://github.com/envoyproxy/gateway/blob/62f5df81f29b3bfc0f0279837fe40d93e9f18e3a/internal/gatewayapi/backendtrafficpolicy.go#L557-L561
In our case `r.Traffic.Timeout` is set so BackendTrafficPolicy processing is skipped for our route.

Note: I guess the same issue can occur when configuring retry on `HttpRoute`, since in this case `Traffic` is also being set: https://github.com/envoyproxy/gateway/blob/4a4c17993245cf02c7ef16a289124e60b2325b36/internal/gatewayapi/route.go#L749

*Environment*:
Latest EG chart (v0.0.0-latest).

### PR DESCRIPTION
**Pull request by guydc**
**What type of PR is this?**

**What this PR does / why we need it**:

Returns the Gateway-API `HTTPRoute` timeout to the `Route` IR struct, extracting it from the `TrafficFeatures` struct.  Both HTTPRoute and BTP may define a route timeout. Instead of merging during IR calculation, both values are now saved in IR.  The effective route timeout is calculated in XDS translation, giving precedence to GW-API settings. 
This simplifies merging logic and makes it easy to identify routes that a gateway-level policy should be applied to. 

**Which issue(s) this PR fixes**:

Fixes #4844

Release Notes: Yes/No

### CODE REVIEW

**Comment by arkodg** [comment]
looks good thanks, does the unit test cover the regression (overriden policy attached to Gateway + timeout specified in HTTPRoute)?

**Comment by guydc** [comment]
> looks good thanks, does the unit test cover the regression (overriden policy attached to Gateway + timeout specified in HTTPRoute)?

Yea.  `Internal/gatewayapi/testdata/backendtrafficpolicy-with-httproute-timeout.in.yaml` now has a GW-attached BTP with some LB settings. `route-2` has a route timeout and gets the GW-level BTP. The IR contains both BTP settings for LB and timeout.

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Review by zhaohuabing — APPROVED** [review]
LGTM thanks!

**Pull request merged**
