### PR TITLE
docs: fix grammar error --> Typo in envoy-patch-policy.md "garunteed"

### PR DESCRIPTION
**Pull request by gwarren3210**
FIxed the typo of "garunteed" into "guaranteed"

**What type of PR is this?**
docs: fix grammar error

### CODE REVIEW

**Comment by arkodg** [comment]
hey thanks for fixing this @gwarren3210 !

cc @zirain @zhaohuabing with the new doc infra changes in place, will someone need to update 3 files having the same content ?

**Comment by arkodg** [comment]
looks like `codespell` didnt catch this since we disabled this dir
https://github.com/envoyproxy/gateway/pull/3882 
cc @zirain

**Comment by zirain** [comment]
> hey thanks for fixing this @gwarren3210 !
> 
> 1. @zirain @zhaohuabing with the new doc infra changes in place, will someone need to update 3 files having the same content ?
> 2. also why did codespell not catch this

1. you should always change content under `latest` or `v[x].[y]`, `make gen-chek` will do the copy.
2. let me check why.

**Comment by zhaohuabing** [comment]
Yes, docs directory is auto-generated.

**Comment by zirain** [comment]
```
codespell site/content/en/latest/tasks/extensibility/envoy-patch-policy.md
```

not output from codespell

**Comment by gwarren3210** [comment]
I am able to run it on localhost without any changes happening to files but when running it in github.dev I get the following error.

```
go test -timeout 30s github.com/envoyproxy/gateway/internal/cmd/egctl --override-testdata=true
# github.com/containers/storage/drivers/btrfs
/go/pkg/mod/github.com/containers/storage@v1.54.0/drivers/btrfs/btrfs.go:12:10: fatal error: btrfs/ioctl.h: No such file or directory
   12 | #include <btrfs/ioctl.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
FAIL    github.com/envoyproxy/gateway/internal/cmd/egctl [build failed]
FAIL
make[1]: *** [tools/make/golang.mk:51: go.testdata.complete] Error 1
make[1]: Leaving directory '/workspaces/gateway'
make: *** [Makefile:18: _run] Error 2
```

**Comment by zirain** [comment]
> I am able to run it on my local machine without any changes happening to files but when running it in github.dev I get the following error. Also running it on my local machine did not generate any files.
> 
> ```
> go test -timeout 30s github.com/envoyproxy/gateway/internal/cmd/egctl --override-testdata=true
> # github.com/containers/storage/drivers/btrfs
> /go/pkg/mod/github.com/containers/storage@v1.54.0/drivers/btrfs/btrfs.go:12:10: fatal error: btrfs/ioctl.h: No such file or directory
>    12 | #include <btrfs/ioctl.h>
>       |          ^~~~~~~~~~~~~~~
> compilation terminated.
> FAIL    github.com/envoyproxy/gateway/internal/cmd/egctl [build failed]
> FAIL
> make[1]: *** [tools/make/golang.mk:51: go.testdata.complete] Error 1
> make[1]: Leaving directory '/workspaces/gateway'
> make: *** [Makefile:18: _run] Error 2
> ```

linux: sudo apt-get install libbtrfs-dev -y
macos: brew install libffi

**Comment by zirain** [comment]
> > > I am able to run it on my local machine without any changes happening to files but when running it in github.dev I get the following error. Also running it on my local machine did not generate any files.
> > > ```
> > > go test -timeout 30s github.com/envoyproxy/gateway/internal/cmd/egctl --override-testdata=true
> > > # github.com/containers/storage/drivers/btrfs
> > > /go/pkg/mod/github.com/containers/storage@v1.54.0/drivers/btrfs/btrfs.go:12:10: fatal error: btrfs/ioctl.h: No such file or directory
> > >    12 | #include <btrfs/ioctl.h>
> > >       |          ^~~~~~~~~~~~~~~
> > > compilation terminated.
> > > FAIL    github.com/envoyproxy/gateway/internal/cmd/egctl [build failed]
> > > FAIL
> > > make[1]: *** [tools/make/golang.mk:51: go.testdata.complete] Error 1
> > > make[1]: Leaving directory '/workspaces/gateway'
> > > make: *** [Makefile:18: _run] Error 2
> > > ```
> > 
> > 
> > linux: sudo apt-get install libbtrfs-dev -y macos: brew install libffi
> 
> I run into the same issue of it not changing any of the files. It passes all the tests locally, is it possible that a test is broken?

no, it just because you lack of some lib that is needed by this project.

**Comment by zirain** [comment]
@gwarren3210 still plan to move this forward?

**Comment by shawnh2** [comment]
close this one, #4958 fix it

**Pull request closed without merging**
