### PR TITLE
feat: Add secret resource support for EnvoyPatchPolicy

### PR DESCRIPTION
**Pull request by soulxu**
**What type of PR is this?**
* "feat(translator): add new feature"

**What this PR does / why we need it**:
There is requirement to use the PrivateKeyProvider by using EnvoyPatchPolicy. https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#extensions-transport-sockets-tls-v3-privatekeyprovider

Currently, the EnvoyPatchPolicy doesn't support to patch secret resource. This PR added that. 

**Which issue(s) this PR fixes**:
Related to issues: #2456

### CODE REVIEW

**Comment by soulxu** [comment]
cc @arkodg

**Comment by soulxu** [comment]
emm.. the test I added https://github.com/envoyproxy/gateway/pull/2466/files#diff-6c66ffad996396e19c73ce021d399757bbeb656d5d9609b1a91612c8c332153c should be covered the code I change.

**Comment by soulxu** [comment]
> emm.. curious about why the test I added https://github.com/envoyproxy/gateway/pull/2466/files#diff-6c66ffad996396e19c73ce021d399757bbeb656d5d9609b1a91612c8c332153c doesn't cover the code I change.

cc @zhaohuabing @zirain any idea about this? will appreciate the help!

**Comment by zhaohuabing** [comment]
@soulxu Don't know how codecov calculate the coverage for patch, but it's not a blocker for a PR, so don't worry.

**Comment by soulxu** [comment]
> @soulxu Don't know how codecov calculate the coverage for patch, but it's not a blocker for a PR, so don't worry.

thanks!

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Review by zirain — APPROVED** [review]

**Comment by arkodg** [comment]
@soulxu can you also add the new type as a const so it pops up in the API docs ?

**Pull request merged**
