### PR TITLE
fix: infraIR duplicate port translation for merged gateways

### PR DESCRIPTION
**Pull request by cnvergence**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/envoyproxy/gateway/issues/2964

### CODE REVIEW

**Review by Xunzhuo — COMMENTED** [review]
Can add an individual testcase for this feature ?

**Comment by cnvergence** [comment]
let's do that

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Review by Xunzhuo — APPROVED** [review]
Thanks !

**Pull request merged**
