### PR TITLE
revises instructions to render yaml in yaml format, removing the kube…

### LINKED ISSUE #3137: docs: yaml artifacts in guides should code-highlight
*Description*:

most of the tasks combine [a] displaying yaml to be applied with [b] applying it to the cluster using the shorthand:

```shell
cat <<EOF | kubectl apply -f -
---
some: yaml
EOF
```

this is great and convenient copy-paste.
but if the resources were presented first as bona-fide yaml, you'd get better yaml highlighting/color-coding, which makes it easier for the reader to review the content.
it also gives the reader an opportunity to copy just the yaml if they want to save these CRs on their file system and study them before doing a kubectl apply.
(also if the reader is not using the bash shell, that command might not work)

suggestion:  revise all instructions in the user guides / tasks such that we display yaml instead, along with an instruction to kubectl apply the resource[s] to the cluster:

```yaml
---
some: yaml
```

### PR DESCRIPTION
**Pull request by eitansuez**
…ctl apply -f - <<EOF part (#3137)

**What type of PR is this?**

This is a docs-related PR

**What this PR does / why we need it**:

First draft implementation of #3137:  revises yaml snippets in lab instructions to render as yaml.

**Which issue(s) this PR fixes**:

Fixes #3137

### CODE REVIEW

**Comment by eitansuez** [comment]
i'm open to feedback.  a case can be made both for and against this idea of removing the `cat <<EOF | kubectl apply -f` convenience.

**Comment by arkodg** [comment]
hey @eitansuez can we support both styles using tabs ?

**Comment by eitansuez** [comment]
> hey @eitansuez can we support both styles using tabs ?

exactly.  i'm just waiting until tabs capability is added to the hugo config.  i assume @yuluo-yx is working on that?

**Comment by arkodg** [comment]
> > hey @eitansuez can we support both styles using tabs ?
> 
> exactly. i'm just waiting until tabs capability is added to the hugo config. i assume @yuluo-yx is working on that?

it was completed in another PR https://github.com/envoyproxy/gateway/pull/3208

**Comment by eitansuez** [comment]
i'm going to close this PR and start a new one rooted at main's HEAD.

**Pull request closed without merging**
