### PR TITLE
ci(deps): setup dependabot

### PR DESCRIPTION
**Pull request by mmorel-35**
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

### CODE REVIEW

**Comment by mmorel-35** [comment]
You can customise the day and hour of the week you want it to be checked, see https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleday

You can also trigger it manually from the insight > dependency  graph > dependabot

**Comment by arkodg** [comment]
thanks for introducing Dependabot to this project @mmorel-35 !
will help automate dependency bumps as well as proactively catch any compatibility issues

Would the changes show up as 1 PR per week, or would there by multiple PRs (per update or package ecosystem) per week ?
Can you also rebase, thanks

**Comment by mmorel-35** [comment]
HI @arkodg ,
It is one PR per dependency. If you prefer grouping I invite you to take a look on renovate.

I have rebased.

**Comment by arkodg** [comment]
> HI @arkodg , It is one PR per dependency. If you prefer grouping I invite you to take a look on renovate.
> 
> I have rebased.

thanks, lets try it out and hope its not too overwhelming, either ways it needs to get done

**Review by arkodg — APPROVED** [review]
SGTM, thanks !

**Review by sunjayBhatia — APPROVED** [review]

**Pull request merged**
