### PR TITLE
feat: add TopologySpreadConstraints to PodSpec

### PR DESCRIPTION
**Pull request by shahar-h**
**What type of PR is this?**
Feature - Add support for `TopologySpreadConstraints` configuration as part of `PodSpec`.

**What this PR does / why we need it**:
It's needed so we can configure a `TopologySpreadConstraints` for Envoy/RateLimit pods. 
A common use case for `TopologySpreadConstraints` configuration is making Envoy/RateLimit pod HA on multi AZ.

**Which issue(s) this PR fixes**: N/A

### CODE REVIEW

**Review by shawnh2 — COMMENTED** [review]
lgtm on this one. but like #2346 points out, we should find a generic approach to set these fields.

**Comment by shahar-h** [comment]
> lgtm on this one. but like #2346 points out, we should find a generic approach to set these fields.

What does it mean? Can this PR be accepted or I'll have to wait for a generic customization approach in order to define `topologySpreadConstraints`?

**Review by shawnh2 — APPROVED** [review]

**Comment by shawnh2** [comment]
> > lgtm on this one. but like #2346 points out, we should find a generic approach to set these fields.
> 
> What does it mean? Can this PR be accepted or I'll have to wait for a generic customization approach in order to define `topologySpreadConstraints`?

this PR LGTM and can be merged. what i mean here is, when #2346 is ready, all these k8s fields can be patched, it shall requires no further api changes.

**Comment by zhaohuabing** [comment]
Is `TopologySpreadConstraints to PodSpec` a common setting? Should we wait for https://github.com/envoyproxy/gateway/issues/2346 and use the general  k8s manifest patch to achieve this?

**Comment by shahar-h** [comment]
@zhaohuabing As I mentioned in PR description this is a common use case in production systems where you want your data plane to be highly available in multi availability zone.

**Comment by zhaohuabing** [comment]
> @zhaohuabing As I mentioned in PR description this is a common use case in production systems where you want your data plane to be highly available in multi availability zone.

Looks reasonable to me. Defer to other @envoyproxy/gateway-maintainers .

**Review by zirain — APPROVED** [review]

**Comment by zirain** [comment]
I think this's more common than `hostNetwork`, so LGTM.

**Review by Xunzhuo — APPROVED** [review]

**Pull request merged**
