### PR TITLE
dont add filterChainMatch for wildcard hostnames

### PR DESCRIPTION
**Pull request by arkodg**
* skip creating a filterChainMatch with a `*` server_names match since envoy doesnt like it and errors out.

Fixes: https://github.com/envoyproxy/gateway/issues/601

Signed-off-by: Arko Dasgupta <arko@tetrate.io>

### CODE REVIEW

**Comment by arkodg** [comment]
cc @chauhanshubham

**Comment by arkodg** [comment]
verified
```
kubectl get gateway -A -o yaml
apiVersion: v1
items:
- apiVersion: gateway.networking.k8s.io/v1beta1
  kind: Gateway
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"gateway.networking.k8s.io/v1beta1","kind":"Gateway","metadata":{"annotations":{},"name":"eg","namespace":"default"},"spec":{"gatewayClassName":"eg","listeners":[{"name":"https","port":8080,"protocol":"HTTPS","tls":{"certificateRefs":[{"group":"","kind":"Secret","name":"example-cert"}],"mode":"Terminate"}}]}}
    creationTimestamp: "2022-10-19T02:57:45Z"
    generation: 1
    name: eg
    namespace: default
    resourceVersion: "1301"
    uid: 0852e5ef-c64a-4163-98ff-ac2120af885e
  spec:
    gatewayClassName: eg
    listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      name: https
      port: 8080
      protocol: HTTPS
      tls:
        certificateRefs:
        - group: ""
          kind: Secret
          name: example-cert
        mode: Terminate
  status:
    addresses:
    - type: IPAddress
      value: 127.0.0.1
    - type: Hostname
      value: localhost
    conditions:
    - lastTransitionTime: "2022-10-19T03:00:34Z"
      message: The Gateway has been scheduled by Envoy Gateway
      observedGeneration: 1
      reason: Scheduled
      status: "True"
      type: Scheduled
    - lastTransitionTime: "2022-10-19T03:00:35Z"
      message: Address assigned to the Gateway, 1/1 envoy Deployment replicas available
      observedGeneration: 1
      reason: Ready
      status: "True"
      type: Ready
    listeners:
    - attachedRoutes: 1
      conditions:
      - lastTransitionTime: "2022-10-19T03:00:34Z"
        message: Listener is ready
        observedGeneration: 1
        reason: Ready
        status: "True"
        type: Ready
      name: https
      supportedKinds:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
kind: List
metadata:
  resourceVersion: ""
🐳 ~/go-workspace/src/github.com/envoyproxy/gateway$ curl -v -HHost:www.example.com --resolve "www.example.com:8080:127.0.0.1" --cacert example.com.crt https://www.example.com:8080/get
* Added www.example.com:8080:127.0.0.1 to DNS cache
* Hostname www.example.com was found in DNS cache
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to www.example.com (127.0.0.1) port 8080 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: example.com.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=www.example.com; O=httpbin organization
*  start date: Oct 18 21:15:36 2022 GMT
*  expire date: Oct 18 21:15:36 2023 GMT
*  common name: www.example.com (matched)
*  issuer: O=example Inc.; CN=example.com
*  SSL certificate verify ok.
> GET /get HTTP/1.1
> Host:www.example.com
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-type: application/json
< x-content-type-options: nosniff
< date: Wed, 19 Oct 2022 03:04:13 GMT
< content-length: 427
< x-envoy-upstream-service-time: 0
< server: envoy
< 
{
 "path": "/get",
 "host": "www.example.com",
 "method": "GET",
 "proto": "HTTP/1.1",
 "headers": {
  "Accept": [
   "*/*"
  ],
  "User-Agent": [
   "curl/7.64.1"
  ],
  "X-Envoy-Expected-Rq-Timeout-Ms": [
   "15000"
  ],
  "X-Forwarded-Proto": [
   "https"
  ],
  "X-Request-Id": [
   "76b62191-3e54-4ca5-ae2b-6617d95f3d38"
  ]
 },
 "namespace": "default",
 "ingress": "",
 "service": "",
 "pod": "backend-57cfdc96fb-fsctf"
* Connection #0 to host www.example.com left intact
}* Closing connection 0

**Review by chauhanshubham — APPROVED** [review]
thanks

**Review by danehans — APPROVED** [review]

**Comment by danehans** [comment]
@arkodg please test to see if the HTTPS backend is reachable after deleting the secret and comment here.

**Pull request merged**
