### PR TITLE
Update 0.4.0 roadmap items

### PR DESCRIPTION
**Pull request by arkodg**
* Suggesting the theme to be - `Customize Envoy Gateway` to support a wider set of users and their use cases.

Signed-off-by: Arko Dasgupta <arko@tetrate.io>

### CODE REVIEW

**Comment by arkodg** [comment]
we discussed this roadmap in the community meeting today and the proposed theme did not receive any objections.

* @AliceProxy highlighted that we should address scale issues soon, hoping @haq204 can create a GH issue highlighting the scale test results, that can be added into the v0.5.0 roadmap.
* Most of the issues in the v0.4.0 roadmap are assigned except #648 that does not have an owner yet. @danehans @skriss @youngnick @zirain is this something any of you can pick up for v0.4.0 ?

**Comment by zirain** [comment]
I want to release `egctl`(contains `version` and `config` command) in v0.4.

**Comment by arkodg** [comment]
> I want to release `egctl`(contains `version` and `config` command) in v0.4.

sounds good @zirain , moved https://github.com/envoyproxy/gateway/issues/915 into the 0.4.0-rc1 milesone. Is this something that should be added to the 0.4.0 roadmap too ?

**Review by danehans — APPROVED** [review]
At this point, I'm not sure if I can commit to working on a feature for the upcoming release. I should know more in the coming weeks. It might be better if I work on uncommitted features.

**Review by AliceProxy — APPROVED** [review]

**Review by Xunzhuo — APPROVED** [review]

**Pull request merged**
