### PR TITLE
fix: return error on failed requests in controller

### PR DESCRIPTION
**Pull request by cnvergence**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/envoyproxy/gateway/issues/2265

### CODE REVIEW

**Comment by zhaohuabing** [comment]
Looks like the Gateway API conformance test allows non-existent backend:

        	            				/home/runner/go/pkg/mod/sigs.k8s.io/gateway-api@v1.0.0/conformance/utils/suite/suite.go:213
        	Error:      	Received unexpected error:
        	            	context deadline exceeded
        	Test:       	TestGatewayAPIConformance/HTTPRouteInvalidNonExistentBackendRef

**Review by zhaohuabing — CHANGES_REQUESTED** [review]
EG should continue reconciling if some backends are missing. This behavior is allowed according to Gateway API conformance tests.  And it's reasonable because EG should try its best to keep the Gateway functioning.

**Comment by cnvergence** [comment]
Seems like I was wrong with my idea

**Comment by qicz** [comment]
> EG should continue reconciling even if some backends are missing. This behavior is required by the Gateway API conformance tests. And it's reasonable because EG should try its best to keep the Gateway functioning.

IMO, delaying to requeue better for the EG memory consumption

**Pull request closed without merging**
