### PR TITLE
fix: perfix match

### PR DESCRIPTION
**Pull request by zhaohuabing**
fix https://github.com/envoyproxy/gateway/issues/2366

### CODE REVIEW

**Comment by zhaohuabing** [comment]
Close this one. I didn't notice that you already opened a PR @tmsnan

**Comment by tmsnan** [comment]
@zhaohuabing, this is better, I have closed the other one 🤣

**Review by zirain — APPROVED** [review]

**Review by shawnh2 — APPROVED** [review]

**Comment by arkodg** [comment]
@zhaohuabing @tmsnan thanks for finding and fixing this.
shouldnt the fix be to add `/` to the prefix helper function ?

**Comment by zhaohuabing** [comment]
> @zhaohuabing @tmsnan thanks for finding and fixing this. shouldnt the fix be to add `/` to the prefix helper function ?

I thought about it. I'm a bit uncomfortable to change`%s/rule/%d/match/%d` to `%srule/%d/match/%d`. `/` is not part of the prefix but a delimiter.

**Comment by arkodg** [comment]
@zhaohuabing one concern I have is, we may need to continue duplicating code (add the extra `/`) in the future instead of reusing it

**Comment by zhaohuabing** [comment]
Agree. Fixed in https://github.com/envoyproxy/gateway/pull/2394

**Pull request merged**
