### PR TITLE
chore: client mtls test

### LINKED ISSUE #2614: e2e: downstream mTLS
*Description*:
>Describe the issue.

Add an e2e for validating clients using a CA Cert as a trust anchor

Relates to https://github.com/envoyproxy/gateway/issues/88

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

### PR DESCRIPTION
**Pull request by guydc**
**What type of PR is this?**

**What this PR does / why we need it**:
Test client MTLS. This test uses the same key/cert pair as both server and client certificate. The certificate itself is used as trusted CA by both parties. Gateway-API utils support this limited use case at the moment. In the future, consider using different certs which are CA-signed (as opposed to self-signed), when conformance suite utils support this. 

**Which issue(s) this PR fixes**:

Fixes #2614

### CODE REVIEW

**Review by zhaohuabing — APPROVED** [review]
LGTM Thanks!

**Review by arkodg — APPROVED** [review]
LGTM thank you !

**Pull request merged**
