### PR TITLE
feat: add host-infra provider support

### PR DESCRIPTION
**Pull request by shawnh2**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

ref #1393

### CODE REVIEW

**Review by arkodg — APPROVED** [review]
LGTM ! thanks for refactoring a bunch of the common code
standalone mode is finally here 🚀

**Comment by arkodg** [comment]
hey @shawnh2 when we write docs, we should probably highlight that standalone mode is still experimental and not meant for production yet, and not all features work out of the box (like global ratelimit)

**Review by Xunzhuo — APPROVED** [review]

**Comment by Xunzhuo** [comment]
@shawnh2 do we have built any e2e tests for host mode?

**Comment by shawnh2** [comment]
> @shawnh2 do we have built any e2e tests for host mode? and we need a user-facing docs for a quickstart and a little bit words about its scenarios

will add user-facing doc & e2e test as a follow-up.

**Comment by zirain** [comment]
@shawnh2 please rebase to make CI happy.

**Review by arkodg — APPROVED** [review]

**Review by zirain — APPROVED** [review]
This's an experimental feature, let's land it in `v1.2` for more feedback.

**Pull request merged**
