### PR TITLE
moving away from promStatsdExporterContainer

### PR DESCRIPTION
**Pull request by zirain**
fixes: https://github.com/envoyproxy/gateway/issues/3369

### CODE REVIEW

**Review by arkodg — DISMISSED** [review]
🎉 🎉 🎉 
Thanks for driving this work across multiple repos @zirain !

**Comment by zirain** [comment]
need more work to make sure everything work as expected

**Comment by zirain** [comment]
```
ratelimit_service_rate_limit_over_limit{
domain="gateway-conformance-infra/same-namespace/http",
key1="httproute/gateway-conformance-infra/header-ratelimit/rule/0/match/0/*_httproute/gateway-conformance-infra/header-ratelimit/rule/0/match/0/*",
key2="rule-0-match-0_rule-0-match-0",
key3="rule-0-match-1_rule-0-match-1"} 1
```

this key1 is hard to read....

**Comment by zirain** [comment]
```
ratelimit.service.rate_limit.gateway-conformance-infra/same-namespace/http.httproute/gateway-conformance-infra/cidr-ratelimit/rule/0/match/0/*_httproute/gateway-conformance-infra/cidr-ratelimit/rule/0/match/0/*.masked_remote_address_0.0.0.0/0.remote_address.over_limit
```
`.` is a key word in statsd we should avoid to use it in descriptor.

**Comment by zirain** [comment]
> ```
> ratelimit.service.rate_limit.gateway-conformance-infra/same-namespace/http.httproute/gateway-conformance-infra/cidr-ratelimit/rule/0/match/0/*_httproute/gateway-conformance-infra/cidr-ratelimit/rule/0/match/0/*.masked_remote_address_0.0.0.0/0.remote_address.over_limit
> ```
> 
> `.` is a key word in statsd we should avoid to use it in descriptor.

this looks like an upstream issue, need to change the upstream code.

**Comment by arkodg** [comment]
> > ```
> > ratelimit.service.rate_limit.gateway-conformance-infra/same-namespace/http.httproute/gateway-conformance-infra/cidr-ratelimit/rule/0/match/0/*_httproute/gateway-conformance-infra/cidr-ratelimit/rule/0/match/0/*.masked_remote_address_0.0.0.0/0.remote_address.over_limit
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `.` is a key word in statsd we should avoid to use it in descriptor.
> 
> 
> this looks like an upstream issue, need to change the upstream code.

hey can you create a GH issue for this ?

**Review by arkodg — APPROVED** [review]

**Review by zhaohuabing — APPROVED** [review]
LGTM thanks!

**Pull request merged**
