### PR TITLE
Update GOVERNANCE.md

### PR DESCRIPTION
**Pull request by richarddli**
I've left Ambassador, and Alex Gervais will be taking my place on the SC.

cc @alexgervais

### CODE REVIEW

**Review by Xunzhuo — APPROVED** [review]
lgtm. Thanks @richarddli

**Review by zirain — APPROVED** [review]
lgtm. Thanks @richarddli

**Comment by alexgervais** [comment]
Thanks for everything @richarddli !

@Xunzhuo, as an active SC member, can I ask you to add me to the proper groups such as @envoyproxy/gateway-steering-committee and communication channels/meeting invites?

**Comment by Xunzhuo** [comment]
Hi @alexgervais I already kindly ask @mattklein123 to help on it.

**Pull request merged**
