### PR TITLE
refactor: optimize client-go performance by protobuf context-type.

### PR DESCRIPTION
**Pull request by qicz**
**What type of PR is this?**
using `protobuf` context-type to optimize client-go performance.
image

using the `json` needs more memory and time
image

### CODE REVIEW

**Comment by zirain** [comment]
please guard this with an env/cmd args, make it avaliable to fallback.

**Comment by qicz** [comment]
> please guard this with an env/cmd args, make it avaliable to fallback.

I will do this PR at next version

**Comment by arkodg** [comment]
@qicz is this still needed ?

**Comment by qicz** [comment]
xref: https://github.com/envoyproxy/gateway/pull/4282#issuecomment-2378285969

**Pull request closed without merging**
