### PR TITLE
fix: ReplaceFullPath not working for root path (/)

### PR DESCRIPTION
**Pull request by arkodg**
Takes https://github.com/envoyproxy/gateway/pull/2817 forward

### CODE REVIEW

**Review by zhaohuabing — COMMENTED** [review]
Do we need an e2e test to make sure it works?

**Comment by arkodg** [comment]
> Do we need an e2e test to make sure it works?

hey @zhaohuabing added an e2e, ptal

**Review by zhaohuabing — APPROVED** [review]
LGTM thanks!

**Review by shawnh2 — APPROVED** [review]
lgtm

**Pull request merged**
