### PR TITLE
chore: add helm template test

### PR DESCRIPTION
**Pull request by zirain**
this will help us to verify the helm chart changes

### CODE REVIEW

**Comment by zhaohuabing** [comment]
Where is the test :-)

**Comment by zirain** [comment]
> Do we need this? Are the e2e tests enough to verify the helm chart?

e2e just make sure it works, but we should take care of every single line change.

**Review by arkodg — APPROVED** [review]
thanks, will make PR reviews based off helm easier

**Review by zhaohuabing — APPROVED** [review]
LGTM thanks！

**Pull request merged**
