### PR TITLE
Fix TestE2E/RateLimitBasedJwtClaims test

### PR DESCRIPTION
**Pull request by zhaohuabing**
Fix https://github.com/envoyproxy/gateway/issues/2095
Related: https://github.com/envoyproxy/gateway/pull/2086  https://github.com/envoyproxy/gateway/pull/2096

### CODE REVIEW

**Review by zirain — APPROVED** [review]
LGTM, why it pass before?

**Comment by zhaohuabing** [comment]
> LGTM, why it pass before?

Jwks remote fetch is failed

```
(base) ➜  ~ curl https://raw.githubusercontent.com/envoyproxy/gateway/main/examples/kubernetes/authn/jwks.json                                 
404: Not Found% 
```

I renamed the directory author to jwt but forgot to change the path in the yaml files. The directory existed before that PR merged. 

The interesting part is: If I changed the yaml files in that PR, that PR wouldn't get e2e pass because `jwt` directory didn't exist before that PR got merged.

**Comment by zhaohuabing** [comment]
```
this policy can only have a targetRef.kind of Gateway
```
@arkodg Route target has been disabled in this release?

**Comment by arkodg** [comment]
https://github.com/envoyproxy/gateway/blob/4cb4547aeea4e3f1517907159d7312ea3c735843/api/v1alpha1/securitypolicy_types.go#L40 seems like a bug :(

**Comment by arkodg** [comment]
it should look like https://github.com/envoyproxy/gateway/blob/4cb4547aeea4e3f1517907159d7312ea3c735843/api/v1alpha1/backendtrafficpolicy_types.go#L40

**Comment by zhaohuabing** [comment]
> it should look like
> 
> https://github.com/envoyproxy/gateway/blob/4cb4547aeea4e3f1517907159d7312ea3c735843/api/v1alpha1/backendtrafficpolicy_types.go#L40

Do we need to support UDPRoute TCPRoute and TLSRoute?

**Comment by arkodg** [comment]
> > it should look like
> > https://github.com/envoyproxy/gateway/blob/4cb4547aeea4e3f1517907159d7312ea3c735843/api/v1alpha1/backendtrafficpolicy_types.go#L40
> 
> I just added Gateway, HTTPRoute, and GRPCRoute in the SecurityPolicy. I think SecurityPolicy is just for layer 7, right?

with `cors`, and `jwt` those routes are NA, so we can skip for now

**Comment by zhaohuabing** [comment]
The Kubernetes integration test is flake, weird.

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Pull request merged**
