### PR TITLE
api: tcpKeepAlive in BackendTrafficPolicy

### PR DESCRIPTION
**Pull request by arkodg**
Relates to https://github.com/envoyproxy/gateway/issues/1031

### CODE REVIEW

**Review by zhaohuabing — APPROVED** [review]

**Review by zhaohuabing — COMMENTED** [review]
Do we also have keep alive option for downstream connections?

**Comment by arkodg** [comment]
@zhaohuabing yes, https://gateway.envoyproxy.io/v0.6.0/api/extension_types/#clienttrafficpolicy was added in v0.6.0

**Review by zhaohuabing — APPROVED** [review]
LGTM, Thanks!

**Review by Xunzhuo — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
