### PR TITLE
fix: remove no needed new pointer creation

### PR DESCRIPTION
**Pull request by Xunzhuo**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

remove no needed new pointer creation

### CODE REVIEW

**Comment by zirain** [comment]
I recall there's an improment in upstream go, but I cannot recall which version and commit, can you link it?

**Review by cnvergence — APPROVED** [review]
lgtm

**Comment by Xunzhuo** [comment]
@zirain I did not get, and it should be none-related to this PR.

Can we get this in ?

**Comment by zhaohuabing** [comment]
I guess this one: https://go.dev/blog/loopvar-preview

For Go 1.22, we plan to change for loops to make these variables have per-iteration scope instead of per-loop scope. 

It's fixed in Go 1.22, but why lint removes this check in 1.21 ?

**Comment by zirain** [comment]
> I guess it's related to the variable scope in loop: https://go.dev/blog/loopvar-preview
> 
> > For Go 1.22, we plan to change for loops to make these variables have per-iteration scope instead of per-loop scope.
> 
> It's fixed in Go 1.22, but why lint removes this check in 1.21 ?

yeah, that's what I mean.

should we hold this until we move to go1.22?

**Review by arkodg — APPROVED** [review]

**Review by zirain — APPROVED** [review]

**Comment by shawnh2** [comment]
This loopvar feature of go 1.22 requires enable env `GOEXPERIMENT=loopvar` (default closed) explicitly. Maybe we could consider enable this feature for other places as well.

**Pull request merged**
