### PR TITLE
feature: add hostNetwork to the podSpec

### PR DESCRIPTION
**Pull request by tanujd11**
**What type of PR is this?**

Feature

**What this PR does / why we need it**:

added hostNetwork to the podSpec

**Which issue(s) this PR fixes**:

Fixes https://github.com/envoyproxy/gateway/issues/1928

### CODE REVIEW

**Review by Xunzhuo — COMMENTED** [review]
LGTM

**Review by Xunzhuo — APPROVED** [review]

**Comment by zirain** [comment]
Before adding this, I want to clearify the use case. The use of HostNetwork is discouraged.

**Comment by fanux** [comment]
@zirain Although the use of hostnetwork is not encouraged, it is an exception in the scenario of gateways. Firstly, gateways need to expose ports such as 80 and 443, and hostnetwork is very convenient for this. Moreover, a gateway may be shared by many applications, so there will be no port conflicts. Therefore, even in a production environment, it is very convenient to use it in this way. Otherwise, it would be necessary to rely on external load balancing to expose ports 80 and 443, which would greatly increase the complexity for users, especially in situations where there is no external load balancing.

**Review by Xunzhuo — APPROVED** [review]
Re-activate this issue. @fanux and his team come to me and provided me some contexts on this request, their team tries to put EG into production, but this is a blocker for them.

In their scenarios, I think this is reasonable and this would be also a common request when deploying single EG with mergeGateways enabled in a cluster, which means there will be only one single envoyproxy instance, and will be no listeners conflicts. AND in private cloud clusters, there offen will be no loadbalancer implementations, if the envoyproxy needs to expose http-80/https-443, this cannot be worked easily, which needs some changes to kubernetes.

So I am +1 for it.

**Review by shawnh2 — APPROVED** [review]

**Review by qicz — APPROVED** [review]
LGTM

**Comment by arkodg** [comment]
Im still not convinced this is a good idea, the project supports multiple ways to setup a gateway in non LoadBalancer mode
* ClusterIP
* NodePort
* External IP (using `gateway.spec.addresses`)

Setting up `hostNetwork` is not going to be enough and not going to work out of the box if trying to access the deployment directly, because of the custom service to container port mapping for privileged ports, this is not a bug, but a design decision, since the container port is an internal implementation and all traffic must be routed to the deployment via the service

**Pull request merged**
