### PR TITLE
bump gateway api to v0.6.0-rc2

### PR DESCRIPTION
**Pull request by arkodg**
Signed-off-by: Arko Dasgupta <arko@tetrate.io>

### CODE REVIEW

**Comment by arkodg** [comment]
hitting https://github.com/kubernetes-sigs/controller-runtime/issues/2035 since k8s was indirectly bumped to 1.26

**Comment by arkodg** [comment]
bumping controller runtime to v0.14.0 fixes the build issue, seeing tests fail now
```
2022-12-16T15:16:18.446-0800	ERROR	kubernetes/predicates.go:82	unable to find associated HTTPRoutes	{"error": "List on GroupVersionKind gateway.networking.k8s.io/v1beta1, Kind=Gateway specifies selector on field secretGatewayIndex, but no index with name secretGatewayIndex has been registered for GroupVersionKind gateway.networking.k8s.io/v1beta1, Kind=Gateway"}
github.com/envoyproxy/gateway/internal/provider/kubernetes.(*gatewayAPIReconciler).validateSecretForReconcile
	/Users/arkodebdasgupta/go-workspace/src/github.com/envoyproxy/gateway/internal/provider/kubernetes/predicates.go:82
github.com/envoyproxy/gateway/internal/provider/kubernetes.TestValidateSecretForReconcile.func1
	/Users/arkodebdasgupta/go-workspace/src/github.com/envoyproxy/gateway/internal/provider/kubernetes/predicates_test.go:156
testing.tRunner
	/usr/local/opt/go@1.19/libexec/src/testing/testing.go:1446
2022-12-16T15:16:18.446-0800	ERROR	kubernetes/predicates.go:82	unable to find associated HTTPRoutes	{"error": "List on GroupVersionKind gateway.networking.k8s.io/v1beta1, Kind=Gateway specifies selector on field secretGatewayIndex, but no index with name secretGatewayIndex has been registered for GroupVersionKind gateway.networking.k8s.io/v1beta1, Kind=Gateway"}
github.com/envoyproxy/gateway/internal/provider/kubernetes.(*gatewayAPIReconciler).validateSecretForReconcile
	/Users/arkodebdasgupta/go-workspace/src/github.com/envoyproxy/gateway/internal/provider/kubernetes/predicates.go:82
github.com/envoyproxy/gateway/internal/provider/kubernetes.TestValidateSecretForReconcile.func1
	/Users/arkodebdasgupta/go-workspace/src/github.com/envoyproxy/gateway/internal/provider/kubernetes/predicates_test.go:156
testing.tRunner
```

**Comment by arkodg** [comment]
@chauhanshubham how were these tests passing before 🙃

**Review by danehans — APPROVED** [review]

**Comment by chauhanshubham** [comment]
> @chauhanshubham how were these tests passing before 🙃

I guess before the spec bump, not adding `WithIndex` just worked in the fake client, so if there was a query that used an indexed field, it was just returning all objects.

**Comment by arkodg** [comment]
> > @chauhanshubham how were these tests passing before 🙃
> 
> I guess before the spec bump, not adding `WithIndex` just worked in the fake client, so if there was a query that used an indexed field, it was just returning all objects.

ah yah adds up, thanks

**Pull request merged**
