### PR TITLE
feat Route Timeouts

### PR DESCRIPTION
**Pull request by arkodg**
Fixes: https://github.com/envoyproxy/gateway/issues/877

### CODE REVIEW

**Comment by arkodg** [comment]
proactively raising some questions
* should we always set a default route timeout ? or default to Envoy's default of `15s` which imo is too high
* should we always explicitly set the default retry policy ? imo we should
  * retry count - 1 (this is Envoy default) or 2
  * retry on - `reset,connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes`
  * per try timeout - route timeout / retry count
  * retriable_status_codes - 503
  
 
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-retrypolicy

ptal @envoyproxy/gateway-maintainers

**Comment by zhaohuabing** [comment]
> proactively raising some questions
> * should we always set a default route timeout ? or default to Envoy's default of `15s` which imo is too high

Maybe stick to Envoy's default until we get a strong reason to change it - like many feedbacks from end users. 

> * should we always explicitly set the default retry policy ? imo we should
>   * retry count - 1 (this is Envoy default) or 2
>   * retry on - `reset,connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes`
>   * per try timeout - route timeout / retry count
>   * retriable_status_codes - 503
>   * retry_host_predicate - `envoy.retry_host_predicates.previous_hosts`
>   * host_selection_retry_max_attempts: 3
>   
>  
> https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-retrypolicy
> 
> ptal @envoyproxy/gateway-maintainers

 We cant assume the backkend services are always idempotent. I have encountered issues on retries - the service has been called multiple times on the same requests and caused problems on the server side.

**Comment by arkodg** [comment]
> > proactively raising some questions
> > 
> > * should we always set a default route timeout ? or default to Envoy's default of `15s` which imo is too high
> 
> Maybe stick to Envoy's default until we get a strong reason to change it - like many feedbacks from end users.
> 
> > * should we always explicitly set the default retry policy ? imo we should
> >   
> >   * retry count - 1 (this is Envoy default) or 2
> >   * retry on - `reset,connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes`
> >   * per try timeout - route timeout / retry count
> >   * retriable_status_codes - 503
> >   * retry_host_predicate - `envoy.retry_host_predicates.previous_hosts`
> >   * host_selection_retry_max_attempts: 3
> > 
> > https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-retrypolicy
> > ptal @envoyproxy/gateway-maintainers
> 
> We cant assume the backkend services are always idempotent. I have encountered issues on retries - the service has been called multiple times on the same requests and caused problems on the server side.

hey @zhaohuabing not adding any retries in this PR
@kflynn and I chatted about this in the community meeting last week and decided to make retries opt in using a seperate API

**Comment by zirain** [comment]
any conformance/e2e test for this?

**Comment by arkodg** [comment]
https://github.com/kubernetes-sigs/gateway-api/pull/2254 should be get merged soon

**Comment by zirain** [comment]
let's wait for that?

**Comment by arkodg** [comment]
> let's wait for that?

there are already translation tests in `gateway-api` & `xds` layer

**Review by zhaohuabing — APPROVED** [review]
LGTM

**Review by AliceProxy — APPROVED** [review]

**Pull request merged**
