### PR TITLE
fix: some status updates are discarded by the status updater

### PR DESCRIPTION
**Pull request by zhaohuabing**
Fix https://github.com/envoyproxy/gateway/issues/4336

### CODE REVIEW

**Comment by arkodg** [comment]
thanks !
do we also need to change the order of status updater and k8s controller ?

**Comment by zhaohuabing** [comment]
> thanks ! do we also need to change the order of status updater and k8s controller ?

I don't know if it's possible: status updater is added as a runnable in the k8s controller and start within it because it also needs leader election.

The current solution is removing the check for start and receive all the updates even it's not started yet.

**Review by arkodg — APPROVED** [review]
thanks for fixing this !

**Review by zirain — APPROVED** [review]

**Comment by zhaohuabing** [comment]
Should we cherry-pick this to v1.1 branch @guydc @arkodg ?

**Comment by arkodg** [comment]
> Should we cherry-pick this to v1.1 branch @guydc @arkodg ?

Sure let's add a label and make sure to add it to v1.1
4

**Pull request merged**
