### PR TITLE
Revert "chore: upgrade test should use VERSION by default (#4393)"

### PR DESCRIPTION
**Pull request by zhaohuabing**
Revert this for now to release v1.2.0-rc.1
https://github.com/envoyproxy/gateway/pull/4476#issuecomment-2436776156

### CODE REVIEW

**Comment by zirain** [comment]
why revert?

**Comment by zirain** [comment]
#4393 fix other problem, you'd better send another one:
- revert the change in kube.mk
- chagne lastVersionTag to "v1.1.2"

**Comment by arkodg** [comment]
we are going to always hit this issue when releasing, we can't revert each time, I would instead hardcode this in the test, and add it as a step post releasing the bits

**Comment by zirain** [comment]
> we are going to always hit this issue when releasing, we can't revert each time, I would instead hardcode this in the test, and add it as a step post releasing the bits

we should change the logic `if version == "" || strings.Contains("rc")`

**Comment by zirain** [comment]
oh, same when releasing `1.2.0`.

**Comment by zhaohuabing** [comment]
Try to fix it with https://github.com/envoyproxy/gateway/pull/4524

**Comment by zhaohuabing** [comment]
> Try to fix it with #4524

This only works for the main branch. If we try to release a minor release like v1.1.3 after v1.2.0, it will use v1.2.0 as for upgrade test.

I'll update the version in upgrade test after releasing v1.2.0 and use that PR as an example to add a step in the release note.

**Pull request closed without merging**
