### PR TITLE
Use `/` to create internal IR names instead of `-`

### PR DESCRIPTION
**Pull request by arkodg**
* Also had to replace `/` with `-` when creating K8s resource names :)

Relates to https://github.com/envoyproxy/gateway/issues/1640

### CODE REVIEW

**Comment by arkodg** [comment]
thanks for creating `make testdata` @Xunzhuo, saved me hours today :)

**Review by zirain — COMMENTED** [review]
lgtm, @envoyproxy/gateway-maintainers ptal.

**Review by Xunzhuo — APPROVED** [review]
Great

**Pull request merged**
