### PR TITLE
refactor: reorder fault filter

### LINKED ISSUE #3046: Reorder fault Envoy filter and make it the first filter
*Description*:
>Describe the issue.

Make the fault filter the first filter since it doesnt rely on other filter funcationality, may reject a request early and we can save on processing in other filters
https://github.com/envoyproxy/gateway/blob/3d519339bc68ab1f8ece22c89aeb757e7fcc58cd/internal/xds/translator/httpfilters.go#L100

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

### PR DESCRIPTION
**Pull request by ShyunnY**
**What type of PR is this?**

Change the fault filter order to first

**What this PR does / why we need it**:

Fixes #3046

### CODE REVIEW

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Review by shawnh2 — APPROVED** [review]
lgtm, thanks

**Pull request merged**
