### PR TITLE
bug: compute endpointType for all protocol types

### PR DESCRIPTION
**Pull request by arkodg**
Fixes: https://github.com/envoyproxy/gateway/issues/2832

### CODE REVIEW

**Comment by zirain** [comment]
able to add an e2e test?

**Comment by arkodg** [comment]
> able to add an e2e test?

the issue is do we want to route to an external FQDN ? Ive seen bad statuses being returned in the past due to middleware thinking we are bots etc, may cause flakes

**Comment by zirain** [comment]
> > able to add an e2e test?
> 
> the issue is do we want to route to an external FQDN ? Ive seen bad statuses being returned in the past due to middleware thinking we are bots etc, may cause flakes

flakes better than error?

**Review by zirain — APPROVED** [review]

**Pull request merged**
