### PR TITLE
ci: add badges for security scans

### PR DESCRIPTION
**Pull request by shahar-h**
**What this PR does / why we need it**:
Add status badges for security scans related workflows:
* CodeQL
* OSV-Scanner
* Trivy

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Review by guydc — APPROVED** [review]
Awesome, thanks!

**Comment by shahar-h** [comment]
@guydc can you reapprove?

**Review by zirain — APPROVED** [review]

**Review by guydc — APPROVED** [review]

**Pull request merged**
