### PR TITLE
fix: match serviceName in tracing with mergedGateways topology

### PR DESCRIPTION
**Pull request by cnvergence**
**What type of PR is this?**

**What this PR does / why we need it**:

When mergeGateways is enabled, tracing should set its service name to GatewayClass name, as there will be only one service for every gateway listener.

**Which issue(s) this PR fixes**:

Fixes https://github.com/envoyproxy/gateway/issues/3210

### CODE REVIEW

**Review by zirain — COMMENTED** [review]
LGTM, can you add a translator test?

**Review by shawnh2 — APPROVED** [review]
lgtm

**Comment by cnvergence** [comment]
just thinking if we should use `GatewayClassName . EnvoyNamespace` format instead

**Review by arkodg — APPROVED** [review]

**Review by zirain — APPROVED** [review]

**Comment by zirain** [comment]
it would be better to see a xds translator test, but LGTM now.

**Pull request merged**
