### PR TITLE
fix: skip the ReasonTargetNotFound for all policies

### LINKED ISSUE #2724: BTP Status getting modified by unrelated GatewayClass
facing the same issue with BTP as in e2e test https://github.com/envoyproxy/gateway/actions/runs/8073622448/job/22057769156?pr=2665#step:6:2130

#2665 introduce merge gateways e2e test, that requires multiple-gatewayclass per controller feature. but this test will affects all the other test cases that have policies attached. because the new gatewayclass in controller will also update the policy status, even the policy is not belong to new GC's.

 so by fixing #2631, I think this issue can be resolved. assigning myself to these two issues.

_Originally posted by @shawnh2 in https://github.com/envoyproxy/gateway/issues/2520#issuecomment-1968509285_

### PR DESCRIPTION
**Pull request by shawnh2**
**What type of PR is this?**

**What this PR does / why we need it**:

currently, skip the `PolicyReasonTargetNotFound` for all policies as a workaround, will revisit this issue via #2631 

**Which issue(s) this PR fixes**:

Fixes #2724

### CODE REVIEW

**Comment by arkodg** [comment]
thanks @shawnh2, code looks good, just to be sure, can we add a test case where all 4 policy types target an unknown gateway, and we can make sure there is no `status` set for those

**Comment by shawnh2** [comment]
> thanks @shawnh2, code looks good, just to be sure, can we add a test case where all 4 policy types target an unknown gateway, and we can make sure there is no `status` set for those

sure, some tests has been added.

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Comment by zirain** [comment]
//retest

**Review by zirain — APPROVED** [review]

**Pull request merged**
