### PR TITLE
chore: replace `targetRef` with `targetRefs` in doc

### PR DESCRIPTION
**Pull request by shawnh2**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Review by zirain — APPROVED** [review]

**Comment by arkodg** [comment]
thanks @shawnh2 !
can you also update `docs/` and `v1.1/` :)

**Comment by zirain** [comment]
> thanks @shawnh2 ! can you also update `docs/` and `v1.1/` :)

you should just update `v1.1` and run `make gen-check`

**Comment by shawnh2** [comment]
updated

**Review by arkodg — APPROVED** [review]
thanks !

**Review by guydc — APPROVED** [review]

**Pull request merged**
