### PR TITLE
Updates Quickstart Guide Links for v0.2.0 Release

### PR DESCRIPTION
**Pull request by danehans**
Updates the Quickstart guide links for the v0.2.0 release.

Signed-off-by: danehans <daneyonhansen@gmail.com>

### CODE REVIEW

**Comment by danehans** [comment]
Note: I will submit a PR after cutting the release to change the links back to `latest`.

**Comment by danehans** [comment]
Closing due to https://github.com/envoyproxy/gateway/pull/631.

**Comment by danehans** [comment]
The Quickstart guide is the only user/dev doc that references release artifacts:
```
$ grep -ri "https://github.com/envoyproxy/gateway/releases/download/latest" docs/user docs/dev
```

**Review by arkodg — APPROVED** [review]
wow, I was expecting more lines to be changed, but looks like the content is modular and reusable !

**Review by Xunzhuo — APPROVED** [review]

**Pull request merged**
