### PR TITLE
feat: expose prom port in rl svc

### LINKED ISSUE #2869: expose prom port in rate limit service
*Description*:
>Describe the issue.

Support Prometheus monitoring using service monitor

Relates to https://github.com/envoyproxy/gateway/pull/2729

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

### PR DESCRIPTION
**Pull request by ShyunnY**
**What type of PR is this?**

feat: expose prom port in rl svc

**Which issue(s) this PR fixes**:

Fixes #2869

### CODE REVIEW

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Review by zirain — APPROVED** [review]

**Pull request merged**
