### PR TITLE
chore: add crd categories

### PR DESCRIPTION
**Pull request by zirain**
with this patch, you can get all eg resources with following command:
```shell
kubctl get envoy-gateway
```

### CODE REVIEW

**Review by liorokman — COMMENTED** [review]
Maybe also add the `gateway-api` category?

**Comment by zirain** [comment]
> Maybe also add the `gateway-api` category?

I think we should different with upstream.

**Review by liorokman — APPROVED** [review]
LGTM

**Review by arkodg — APPROVED** [review]
🚀

**Pull request merged**
