### PR TITLE
e2e: use grafana alloy instead of fluent-bit

### PR DESCRIPTION
**Pull request by zirain**
- this will make configuration simpler and test run faster
- easier to support IPv6 and Dual

### CODE REVIEW

**Review by shawnh2 — APPROVED** [review]

**Comment by zhaohuabing** [comment]
Hi @zirain curios why grafana alloy is faster than fluent-bit?

**Comment by zhaohuabing** [comment]
There are two copies of logs are in the loki?

**Comment by zirain** [comment]
> Hi @zirain curios why grafana alloy is faster than fluent-bit?

it's faster on my local cluster.

**Comment by zirain** [comment]
> I would prefer to keep the more popular one (for users who are using EG or likely to use it) rather than the faster one

I want to bring this back cause I cannot figure out how to make fluent-bit support IPv6 and Dual.

**Review by arkodg — APPROVED** [review]

**Review by zhaohuabing — APPROVED** [review]

**Pull request merged**
