### PR TITLE
ci: setup action for cherrypick

### PR DESCRIPTION
**Pull request by zirain**
1. setup action for cherrypick by using https://github.com/carloscastrojumo/github-cherry-pick-action
2. see demo from https://github.com/zirain/test-action/pull/9
3. this action should be updated per release
4. will cerate `cherrypick/release-v0.4` later

**NOTE: label(e.g. `cherrypick/release-v0.4`) should be added before merging PR.**

cc @AliceProxy @arkodg @Xunzhuo 

BTW, need enable following options:

image

### CODE REVIEW

**Comment by Xunzhuo** [comment]
It can only work for one release version? Like if we update this with v0.4.0, we can only cherry-pick commits to v0.4.0, but if I want to cherry-pick commits to v0.3.0, v0.2.0 ... It can not work, right?

**Comment by zirain** [comment]
> It can only work for one release version? Like if we update this with v0.4.0, we can only cherry-pick commits to v0.4.0, but if I want to cherry-pick commits to v0.3.0, v0.2.0 ... It can not work, right?

Actually, I think we can make it more generic. 

For now, RM (release manager) is different for each release.
Send a PR to copy these parts when RM is confirmed.
When a release is EOL, just remove those lines.

**Comment by arkodg** [comment]
this approach sgtm, another one im seeing is https://github.com/sqren/backport/tree/main

**Comment by zirain** [comment]
> this approach sgtm, another one im seeing is https://github.com/sqren/backport/tree/main

it looks like a CLI, not a Github action?

**Comment by arkodg** [comment]
> > this approach sgtm, another one im seeing is https://github.com/sqren/backport/tree/main
> 
> it looks like a CLI, not a Github action?

https://github.com/sqren/backport-github-action

**Comment by zirain** [comment]
@arkodg so you think https://github.com/sqren/backport-github-action is better?
if so will you send a PR for that, I will close this.

**Review by arkodg — APPROVED** [review]
LGTM thanks, good to add some guidance in release steps as a follow up to this PR

**Comment by zirain** [comment]
@AliceProxy you're RM of v0.4, can you take a look at this?

**Comment by Xunzhuo** [comment]
> > It can only work for one release version? Like if we update this with v0.4.0, we can only cherry-pick commits to v0.4.0, but if I want to cherry-pick commits to v0.3.0, v0.2.0 ... It can not work, right?
> 
> Actually, I think we can make it more generic.
> 
> For now, RM (release manager) is different for each release. Send a PR to copy these parts when RM is confirmed. When a release is EOL, just remove those lines.

Can we document these points in release proccess ?

**Comment by zirain** [comment]
@Xunzhuo done

**Review by Xunzhuo — APPROVED** [review]

**Comment by Xunzhuo** [comment]
maybe we need an approval from @AliceProxy

**Comment by AliceProxy** [comment]
Sorry, I was occupied with Kubecon pretty much all last week and I didn't notice this today before I released v0.4.0. In general though I'm a +1 for this system for future releases.

**Comment by zirain** [comment]
@AliceProxy can you give a approval to get this PR in?

**Review by AliceProxy — APPROVED** [review]

**Pull request merged**
