### PR TITLE
Roadmap for v0.6.0

### PR DESCRIPTION
**Pull request by arkodg**

### CODE REVIEW

**Comment by arkodg** [comment]
ptal @AliceProxy @Xunzhuo since some of the roadmap issues have been assigned to you.

https://github.com/envoyproxy/gateway/issues/1365 needs an owner to drive it, @qicz can you help with this ?

**Review by Xunzhuo — APPROVED** [review]
/lgtm

cc @qicz for another look.

**Comment by qicz** [comment]
> ptal @AliceProxy @Xunzhuo since some of the roadmap issues have been assigned to you.
> 
> #1365 needs an owner to drive it, @qicz can you help with this ?

There will be more work to do in the company in the next few months, and I don't know if I have more time to do this. But I will try to take the time to do it. thanks

**Review by qicz — APPROVED** [review]
LGTM

**Pull request merged**
