### PR TITLE
docs: add a "releases" tab

### LINKED ISSUE #2156: Add a releases tab in doc
*Description*:
>Describe the issue.

Add a releases tab similar to `design`, `user guide

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

### PR DESCRIPTION
**Pull request by lemonlinger**
Fixes #2156

### CODE REVIEW

**Comment by arkodg** [comment]
@lemonlinger we also need to move the release notes under the tab

**Comment by zirain** [comment]
I'd like rename the tabel to `News`, release is one kind of.

**Comment by arkodg** [comment]
@zirain we have Release Announcements under the Announcements tab, this is release notes

**Comment by lemonlinger** [comment]
> @lemonlinger we also need to move the release notes under the tab

And the release notes need to be automatically generated from GitHub pull requests?

**Comment by arkodg** [comment]
they are manually written https://github.com/envoyproxy/gateway/tree/main/release-notes and then copied over to https://github.com/envoyproxy/gateway/tree/main/site

**Comment by lemonlinger** [comment]
> they are manually written https://github.com/envoyproxy/gateway/tree/main/release-notes and then copied over to https://github.com/envoyproxy/gateway/tree/main/site

Release notes have been added. 

PTAL @arkodg

**Review by zirain — APPROVED** [review]

**Review by shawnh2 — APPROVED** [review]
lgtm

**Pull request merged**
