### PR TITLE
feat: add all resource type support for `egctl x status`

### PR DESCRIPTION
**Pull request by shawnh2**
**What type of PR is this?**

follow-up of #2550, add support for `egctl x status all` to get the summary of all resource types status

for example, the resource types with empty status will be ignored:

image

### CODE REVIEW

**Comment by arkodg** [comment]
can we keep this similar to `kubectl get all` which looks like

the resource type is appended into the name with `/`

```
kubectl get all
NAME                           READY   STATUS    RESTARTS       AGE
pod/backend-5cbb9cd947-rgdb7   1/1     Running   2 (116m ago)   2d3h

NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/backend      ClusterIP   10.97.147.91   <none>        3000/TCP   2d3h
service/kubernetes   ClusterIP   10.96.0.1      <none>        443/TCP    2d3h

NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/backend   1/1     1            1           2d3h

NAME                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/backend-5cbb9cd947   1         1         1       2d3h
``

**Comment by shawnh2** [comment]
> can we keep this similar to `kubectl get all` which looks like
> 
> the resource type is appended into the name with `/`
> 
> ```
> kubectl get all
> NAME                           READY   STATUS    RESTARTS       AGE
> pod/backend-5cbb9cd947-rgdb7   1/1     Running   2 (116m ago)   2d3h
> 
> NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
> service/backend      ClusterIP   10.97.147.91   <none>        3000/TCP   2d3h
> service/kubernetes   ClusterIP   10.96.0.1      <none>        443/TCP    2d3h
> 
> NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
> deployment.apps/backend   1/1     1            1           2d3h
> 
> NAME                                 DESIRED   CURRENT   READY   AGE
> replicaset.apps/backend-5cbb9cd947   1         1         1       2d3h
> ``
> ```

done, it's much simpler this way.

image

**Comment by arkodg** [comment]
great work @shawnh2, one suggestion - can we use small case for `kind` ?

**Comment by shawnh2** [comment]
> great work @shawnh2, one suggestion - can we use small case for `kind` ?

of course

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Review by cnvergence — APPROVED** [review]
lgtm

**Pull request merged**
