### PR TITLE
docs: update BackendTLSPolicy docs

### PR DESCRIPTION
**Pull request by zhaohuabing**
Update BackendTLSPolicy docs for https://github.com/envoyproxy/gateway/pull/4784

### CODE REVIEW

**Review by arkodg — APPROVED** [review]

**Review by arkodg — APPROVED** [review]

**Comment by lsjostro** [comment]
This broke our setup when upgraded. Could we please update the release notes to highlight it as a breaking change? Just so that others not run into this causing downtime for their services.

**Comment by arkodg** [comment]
are you using v0.0.0-latest @lsjostro ? this hasn't released yet https://github.com/envoyproxy/gateway/pull/4784/files

**Comment by lsjostro** [comment]
Nope, the feature/fix was released with v1.2.4. (maybe not the docs?).

**Comment by arkodg** [comment]
yeah you're right @lsjostro the fix was part of v1.2.4 and since the docs highlighted the example, it should be surfaced as a breaking change and not a bug fix

**Pull request merged**
