### PR TITLE
Docs/Tests: documentation and e2e tests for Datadog tracing

### PR DESCRIPTION
**Pull request by Hartigan**
Hi

This PR introduce documentation and end-to-end tests for Datadog tracing which added in https://github.com/envoyproxy/gateway/pull/4298

End-to-end test implemented via [Grafana Alloy](https://grafana.com/docs/alloy/latest/), where Alloy acts as adapter from [Datadog agent interface](https://github.com/DataDog/datadog-agent) into `OpenTelemetry` format.

Thanks

### CODE REVIEW

**Comment by Hartigan** [comment]
@zirain , may you take a look?

**Review by zirain — COMMENTED** [review]
Generally LGTM, thanks for adding this.

**Comment by zirain** [comment]
Now the pipeline looks like [Envoy] -> [Alloy] -> [OTel-collecotr] -> [Tempo], right?
Does OTel-collector[-contrib] could play as Datadog backend?

**Comment by Hartigan** [comment]
@zirain yes.
Looks like Opentelemetry collector has [Datadog receiver support](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/datadogreceiver/README.md). I may try rewrite without test without Alloy.

**Comment by Hartigan** [comment]
Now test uses only `opentelemetry-collector` without `Alloy`. Also,  I updated `opentelemetry-collector` to `0.108.0`

**Review by zirain — APPROVED** [review]

**Comment by Hartigan** [comment]
@zirain should I mention somebody for additional review or approval?

**Review by arkodg — APPROVED** [review]

**Comment by arkodg** [comment]
thanks for also adding docs and e2e @Hartigan !

**Pull request merged**
