### PR TITLE
chore: use v1.0.0 as default for upgrade test

### PR DESCRIPTION
**Pull request by guydc**
**What this PR does / why we need it**:
Now that v1.0.0 is released, we should use it a baseline for upgrade tests in CI.

### CODE REVIEW

**Review by zhaohuabing — COMMENTED** [review]
Is it reasonable to cover one more old versions(v 0.0.6)?

**Review by zirain — APPROVED** [review]

**Review by cnvergence — APPROVED** [review]

**Comment by arkodg** [comment]
@zhaohuabing the release/v1.0 branch already has the v0.6 to v1.0 test

**Review by arkodg — APPROVED** [review]

**Comment by zhaohuabing** [comment]
Do we support upgrade from v0.6 to latest？

**Comment by arkodg** [comment]
@zhaohuabing id suggest we only start with supporting migrating from one minor version to the next minor version

**Pull request merged**
