### PR TITLE
api: enableProxyProtocol in ClientTrafficPolicy

### PR DESCRIPTION
**Pull request by arkodg**
Relates to https://github.com/envoyproxy/gateway/issues/1328

### CODE REVIEW

**Comment by zirain** [comment]
Will there be other fields in the future? if so, prefer to something like: 
```
proxyProtocol:
  enable: true
  xxxx:
  yyy:
```

**Comment by arkodg** [comment]
@zirain good question, the only thing I can think of is TLV, but unsure how common it is for end users to set it.
Also prefer implicit enable rather than explicit enable with a field

**Comment by Xunzhuo** [comment]
Should ctp reuse the same proxyprotocol like btp https://github.com/envoyproxy/gateway/commit/99b1642b3c1ff20ed8f82ffb0ea8b88108dbdf96 ?

**Comment by zhaohuabing** [comment]
> @zirain good question, the only thing I can think of is TLV, but unsure how common it is for end users to set it. Also prefer implicit enable rather than explicit enable with a field

We can make the `EnableProxyProtocol` as an empty structure for better future-proofing.

**Comment by arkodg** [comment]
hey @Xunzhuo we can't use confirm from `btp` which picks a specific version (v1 or v2), this is server side, which can interpret both

**Review by zhaohuabing — APPROVED** [review]

**Comment by arkodg** [comment]
emissary seems to have a `boolean` knob too
https://www.getambassador.io/docs/emissary/latest/topics/running/ambassador-with-aws#recommended-configuration
so does contour
https://projectcontour.io/guides/proxy-proto/

I would prefer to start with `bool` before we introduce a `struct` because there is no good use case yet

**Review by zirain — APPROVED** [review]
Thanks!

**Pull request merged**
