### PR TITLE
feat(EG K8S Provider): Improve EG Gateway xDS & startup reliability

### PR DESCRIPTION
**Pull request by alexwo**
###  What type of PR is this?
feat(EG K8S Provider): Improve EG Gateway xDS & startup reliability

### What this PR does / why we need it:
- Service Readiness: By waiting for the xDS service to start up, we ensure that the service discovery mechanism is operational, which is crucial for dynamically managing service configurations and routing in microservices architectures.
- Stability and Reliability: This cautious approach prioritizes the stability and reliability of the system by preventing any unconfigured or misconfigured instances of Envoy from intercepting traffic, which could lead to service disruptions or degraded user experiences.
- Observability: Completing a successful reconcile cycle before startup can make it easier to monitor and debug the system, as it sets a clear baseline for the operational state of the Envoy instances.

###  Which issue(s) this PR fixes:
This enhancement facilitates the safer upgrades of EG gateways and features improved xDS consistency on startup.

###  High Level Changes
A custom health check is implemented to ensure that EG controller is deemed ready only once the xDS snapshot is persisted, or after at least one reconciliation is completed for empty or new clusters.
A custom watcher is added to initiate an initial dummy reconciliation, this ensures empty or news deployments can start (as a successful reconcile is a trigger for startup)

- Configuration Validation: Ensuring a successful reconcile cycle before startup means that the initial configuration passed to Envoy proxies is validated and error-free. This minimizes the chances of runtime errors related to misconfigurations.

https://github.com/envoyproxy/gateway/issues/2810

! Draft !

### CODE REVIEW

**Comment by arkodg** [comment]
@alexwo is this necessary ?
based on https://github.com/envoyproxy/gateway/blob/main/internal/xds/cache/snapshotcache.go I believe we only push a snapshot if the IR exists

**Comment by alexwo** [comment]
> @alexwo is this necessary ? based on https://github.com/envoyproxy/gateway/blob/main/internal/xds/cache/snapshotcache.go I believe we only push a snapshot if the IR exists, so if a IR hasn't been translated yet, it shouldnt result in a xds response (this needs to be cross checked)

Sure, If there are no items requiring translation, we don't anticipate an XDS response. Our focus is solely on verifying that the XDS server has successfully initiated and that a reconciliation loop, albeit inactive, has been executed. (empty / new cluster)

If there are any IRs translated due to a reconciliation loop containing items needing processing, we verify that a snapshot has indeed been persisted before deeming the instance ready. 

There are essentially two conditions that indicate the instance's health. (cluster with resources for xDS)

**Comment by aoledk** [comment]
@alexwo You closed this PR in favor of @arkodg 's suggestion (https://github.com/envoyproxy/gateway/issues/2810#issuecomment-1981979019) to use longer `initialDelaySeconds` ?

**Pull request closed without merging**
