### PR TITLE
bugfix: fix upstream get unwanted /.

### LINKED ISSUE #3807: Incorrect url rewrite, double slash
*Description*:
I have HTTPRoute with following configuration:
```yaml
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              replacePrefixMatch: /api/service/
              type: ReplacePrefixMatch
      matches:
        - path:
            type: PathPrefix
            value: /service/
```
I expect getting `/api/service/version` rewrite for `/service/version` request but got `/api/service//version`.

*Environment*:
version: v1.0.2

*Logs*:
```
envoy-dev-eg-527a6325-856695c98-xbrgh envoy {"start_time":"2024-07-10T14:28:24.951Z","method":"GET","x-envoy-origin-path":"/api/service//version","protocol":"HTTP/1.1","response_code":"400","response_flags":"-","response_code_details":"via_upstream","connection_termination_details":"-","upstream_transport_failure_reason"
:"-","bytes_received":"0","bytes_sent":"435","duration":"2","x-envoy-upstream-service-time":"-","x-forwarded-for":"XXXX,","user-agent":"XXX","x-request-id":"77f300c3-be96-4ebf-87de-f6d135bc19e
c",":authority":"HOST","upstream_host":"172.20.0.50:8080","upstream_cluster":"httproute/dev/service/rule/0","upstream_local_address":"172.20.1.22:59174","downstream_local_address":"172.20.1.22:8080","downstream_remote_address":"XXXX:44076","requested_server_name":"-","route_name":"http
route/dev/service/rule/0/match/0/XXXX"}
```

P.S. Also, found close issue #2976  but for Redirect

### LINKED ISSUE #3989: upstream get unwanted /
ref #1044 

the main branch has the same bug
image
image

### PR DESCRIPTION
**Pull request by qicz**
**What type of PR is this?**

**What this PR does / why we need it**:
when the pathMath.Prefix has suffix / but EG has removed it, 
https://github.com/envoyproxy/gateway/blob/f4c53f4899b543a6461e7bf666a9bfa3b476e6b4/internal/xds/translator/route.go#L148-L153
and the urlRewrite.Path.PrefixMatchReplace suffix with / the upstream will get unwanted /
**Which issue(s) this PR fixes**:

Fixes #3989 , Fix #3807

### CODE REVIEW

**Comment by zirain** [comment]
can you add a test to guarantee this?

**Review by shawnh2 — APPROVED** [review]

**Review by zirain — APPROVED** [review]

**Comment by arkodg** [comment]
@qicz can you add an e2e for this ?

**Pull request merged**
