### PR TITLE
chore: fix http2_protocol_options  warning message

### LINKED ISSUE #2023: warning message when bootstrap
```
[2023-10-20 00:03:08.381][1][warning][misc] [source/common/protobuf/message_validator_impl.cc:21] Deprecated field: type envoy.config.cluster.v3.Cluster Using deprecated option 'envoy.config.cluster.v3.Cluster.http2_protocol_options' from file cluster.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.
[2023-10-20 00:03:08.395][1][warning][main] [source/server/server.cc:902] There is no configured limit to the number of allowed active downstream connections. Configure a limit in `envoy.resource_monitors.downstream_connections` resource monitor.
[2023-10-20 00:03:23.398][1][warning][config] [source/extensions/config_subscription/grpc/grpc_subscription_impl.cc:130] gRPC config: initial fetch timed out for type.googleapis.com/envoy.service.runtime.v3.Runtime
```

### PR DESCRIPTION
**Pull request by tmsnan**
**What type of PR is this?**
Replace deprecated option 'envoy.config.cluster.v3.Cluster.http2_protocol_options`

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #2023

### CODE REVIEW

**Comment by zirain** [comment]
@tmsnan can you fix the conflict?

**Comment by tmsnan** [comment]
> @tmsnan can you fix the conflict?

done

**Review by arkodg — APPROVED** [review]

**Review by zirain — APPROVED** [review]

**Pull request merged**
