### PR TITLE
docs: improve api type members

### PR DESCRIPTION
**Pull request by zirain**
before:

image

after:

image

### CODE REVIEW

**Comment by arkodg** [comment]
nice ! this LGTM, one thing I see missing is the `optional` / `required` tags, how should we surface that ?

**Review by arkodg — APPROVED** [review]

**Comment by zirain** [comment]
> nice ! this LGTM, one thing I see missing is the `optional` / `required` tags, how should we surface that ?

let me find out and try to fix with another PR.

**Pull request merged**
