### PR TITLE
Support dynamic GatewayControllerName in xRoute status

### PR DESCRIPTION
**Pull request by arkodg**

### CODE REVIEW

**Comment by arkodg** [comment]
blocked on https://github.com/envoyproxy/gateway/pull/1265

**Review by AliceProxy — APPROVED** [review]
lgtm

**Review by Xunzhuo — COMMENTED** [review]
I am a bit confused, since the GatewayControllerName in `api/config/v1alpha1/envoygateway_types.go` is a const, I am not sure if it is dynamic.

**Comment by arkodg** [comment]
@Xunzhuo, the default can be overridden using the `EnvoyGateway` config.

Here is the config with a custom controller name
```
kubectl get configmap/envoy-gateway-config -n envoy-gateway-system -o yaml
apiVersion: v1
data:
  envoy-gateway.yaml: |
    apiVersion: config.gateway.envoyproxy.io/v1alpha1
    gateway:
      controllerName: "gateway.envoyproxy.io/custom-gatewayclass-controller"
    kind: EnvoyGateway
    provider:
      type: "Kubernetes"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: eg
    meta.helm.sh/release-namespace: envoy-gateway-system
  creationTimestamp: "2023-04-07T16:40:35Z"
  labels:
    app.kubernetes.io/instance: eg
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gateway-helm
    app.kubernetes.io/version: latest
    helm.sh/chart: gateway-helm-v0.0.0-latest
  name: envoy-gateway-config
  namespace: envoy-gateway-system
  resourceVersion: "955"
  uid: 5fa1615d-e611-46b9-a018-5e7490cf5398
```

Here is the status on the HTTPRoute highlighting the custom controller name
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.networking.k8s.io/v1beta1","kind":"HTTPRoute","metadata":{"annotations":{},"name":"backend","namespace":"default"},"spec":{"hostnames":["www.example.com"],"parentRefs":[{"name":"eg"}],"rules":[{"backendRefs":[{"group":"","kind":"Service","name":"backend","port":3000,"weight":1}],"matches":[{"path":{"type":"PathPrefix","value":"/"}}]}]}}
  creationTimestamp: "2023-04-07T16:44:52Z"
  generation: 1
  name: backend
  namespace: default
  resourceVersion: "1275"
  uid: 20adb962-2d6e-436c-8397-9caeff305198
spec:
  hostnames:
  - www.example.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: backend
      port: 3000
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
status:
  parents:
  - conditions:
    - lastTransitionTime: "2023-04-07T16:45:11Z"
      message: Route is accepted
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2023-04-07T16:45:11Z"
      message: Resolved all the Object references for the Route
      observedGeneration: 1
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    controllerName: gateway.envoyproxy.io/custom-gatewayclass-controller
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: eg
```

**Review by Xunzhuo — APPROVED** [review]
Great thanks!

**Pull request merged**
