### PR TITLE
docs: added defaults for load balancing

### LINKED ISSUE #4070: Load Balancing default behaviour documentation
### Description
Default behaviour of Load Balancing in envoy gateway is not documented properly in Envoy Gateway docs or Envoy Proxy docs.

Related Envoy Gateway Docs:
- [Load Balancing](https://gateway.envoyproxy.io/docs/tasks/traffic/load-balancing/)
- `loadBalancer` field in [BackendTrafficPolicySpec](https://gateway.envoyproxy.io/docs/api/extension_types/#backendtrafficpolicyspec)

@arkodg clarified in slack that default behaviour is `LeastRequest`. We should document this.

### PR DESCRIPTION
**Pull request by luvk1412**
**What type of PR is this?**

Documentation improvement

**What this PR does / why we need it**:
Add default behaviour of load balancing.

**Which issue(s) this PR fixes**:

Fixes #4070

### CODE REVIEW

**Comment by arkodg** [comment]
thanks for fixing this !
you'll need to make the change in https://github.com/envoyproxy/gateway/blob/addb86a3197be91c1187d9d01c19f56558d37028/api/v1alpha1/loadbalancer_types.go#L10 and run `make generate` / the docs are auto generated

**Comment by arkodg** [comment]
DCO is failing can you also sign and force push (`--amend -s`) ?

**Comment by luvk1412** [comment]
shouldn't i modify the doc at ?
https://github.com/envoyproxy/gateway/blob/addb86a3197be91c1187d9d01c19f56558d37028/api/v1alpha1/backendtrafficpolicy_types.go#L104 
as this is where it is mentioned as optional and hence default value should be documented ? Or you want me to document in `loadbalancer_types.go` ? @arkodg

**Comment by arkodg** [comment]
> shouldn't i modify the doc at ?
> 
> https://github.com/envoyproxy/gateway/blob/addb86a3197be91c1187d9d01c19f56558d37028/api/v1alpha1/backendtrafficpolicy_types.go#L104
> 
> 
> as this is where it is mentioned as optional and hence default value should be documented ? Or you want me to document in `loadbalancer_types.go` ? @arkodg

sure yah - `Defaults to `LeastRequest`. here should make it easier for users to understand the defaults

**Comment by luvk1412** [comment]
have done the changes @arkodg

**Review by arkodg — DISMISSED** [review]
thanks !

**Comment by zirain** [comment]
Need to run `make gen-check` locally to make CI happy.

**Review by shawnh2 — DISMISSED** [review]
LGTM! Thanks for adding this.

**Comment by luvk1412** [comment]
@zirain `make gen-check` i failing for me on local, here are last few lines: 
<details>
<summary>Last few error lines</summary>

```shell
===========> Running go.testdata.complete ... 
go test -timeout 30s github.com/envoyproxy/gateway/internal/xds/translator --override-testdata=true
ok      github.com/envoyproxy/gateway/internal/xds/translator   1.395s
go test -timeout 30s github.com/envoyproxy/gateway/internal/cmd/egctl --override-testdata=true
ok      github.com/envoyproxy/gateway/internal/cmd/egctl        2.238s
go test -timeout 30s github.com/envoyproxy/gateway/internal/infrastructure/kubernetes/ratelimit --override-testdata=true
ok      github.com/envoyproxy/gateway/internal/infrastructure/kubernetes/ratelimit      1.053s
go test -timeout 30s github.com/envoyproxy/gateway/internal/infrastructure/kubernetes/proxy --override-testdata=true
ok      github.com/envoyproxy/gateway/internal/infrastructure/kubernetes/proxy  1.089s
go test -timeout 30s github.com/envoyproxy/gateway/internal/xds/bootstrap --override-testdata=true
ok      github.com/envoyproxy/gateway/internal/xds/bootstrap    0.797s
go test -timeout 60s github.com/envoyproxy/gateway/internal/gatewayapi --override-testdata=true
ok      github.com/envoyproxy/gateway/internal/gatewayapi       7.889s
===========> Running gen-check ... 
===========> ERROR: Some files need to be updated
diff --git a/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml b/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml
index 2190e623..a23e6567 100644
--- a/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml
+++ b/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml
@@ -510,7 +510,7 @@ spec:
               loadBalancer:
                 description: |-
                   LoadBalancer policy to apply when routing traffic from the gateway to
-                  the backend endpoints
+                  the backend endpoints. Defaults to `LeastRequest`.
                 properties:
                   consistentHash:
                     description: |-
diff --git a/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyextensionpolicies.yaml b/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyextensionpolicies.yaml
index 5b88ec48..74a91b66 100644
--- a/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyextensionpolicies.yaml
+++ b/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyextensionpolicies.yaml
@@ -624,7 +624,7 @@ spec:
                         loadBalancer:
                           description: |-
                             LoadBalancer policy to apply when routing traffic from the gateway to
-                            the backend endpoints
+                            the backend endpoints. Defaults to `LeastRequest`.
                           properties:
                             consistentHash:
                               description: |-
diff --git a/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml b/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
index 436a3331..5359569c 100644
--- a/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
+++ b/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
@@ -10922,7 +10922,7 @@ spec:
                                           loadBalancer:
                                             description: |-
                                               LoadBalancer policy to apply when routing traffic from the gateway to
-                                              the backend endpoints
+                                              the backend endpoints. Defaults to `LeastRequest`.
                                             properties:
                                               consistentHash:
                                                 description: |-
@@ -11812,7 +11812,7 @@ spec:
                                           loadBalancer:
                                             description: |-
                                               LoadBalancer policy to apply when routing traffic from the gateway to
-                                              the backend endpoints
+                                              the backend endpoints. Defaults to `LeastRequest`.
                                             properties:
                                               consistentHash:
                                                 description: |-
@@ -12757,7 +12757,7 @@ spec:
                                     loadBalancer:
                                       description: |-
                                         LoadBalancer policy to apply when routing traffic from the gateway to
-                                        the backend endpoints
+                                        the backend endpoints. Defaults to `LeastRequest`.
                                       properties:
                                         consistentHash:
                                           description: |-
@@ -13657,7 +13657,7 @@ spec:
                               loadBalancer:
                                 description: |-
                                   LoadBalancer policy to apply when routing traffic from the gateway to
-                                  the backend endpoints
+                                  the backend endpoints. Defaults to `LeastRequest`.
                                 properties:
                                   consistentHash:
                                     description: |-
diff --git a/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml b/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml
index da5eed29..394fddd6 100644
--- a/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml
+++ b/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml
@@ -830,7 +830,7 @@ spec:
                           loadBalancer:
                             description: |-
                               LoadBalancer policy to apply when routing traffic from the gateway to
-                              the backend endpoints
+                              the backend endpoints. Defaults to `LeastRequest`.
                             properties:
                               consistentHash:
                                 description: |-
@@ -1633,7 +1633,7 @@ spec:
                           loadBalancer:
                             description: |-
                               LoadBalancer policy to apply when routing traffic from the gateway to
-                              the backend endpoints
+                              the backend endpoints. Defaults to `LeastRequest`.
                             properties:
                               consistentHash:
                                 description: |-
gmake[1]: *** [tools/make/lint.mk:82: gen-check] Error 1
gmake[1]: Leaving directory '/Users/lk/personal/envoy-gateway'
gmake: *** [Makefile:18: _run] Error 2
```
</details>

The diff files shown above in error from what i can see got autogenerated while `===========> Running go.testdata.complete ... ` step was running. 

Is there some step/change i am missing here ?

**Comment by zirain** [comment]
> @zirain `make gen-check` is failing for me on local
> 
> Last few error lines
> ```shell
> ===========> Running go.testdata.complete ... 
> go test -timeout 30s github.com/envoyproxy/gateway/internal/xds/translator --override-testdata=true
> ok      github.com/envoyproxy/gateway/internal/xds/translator   1.395s
> go test -timeout 30s github.com/envoyproxy/gateway/internal/cmd/egctl --override-testdata=true
> ok      github.com/envoyproxy/gateway/internal/cmd/egctl        2.238s
> go test -timeout 30s github.com/envoyproxy/gateway/internal/infrastructure/kubernetes/ratelimit --override-testdata=true
> ok      github.com/envoyproxy/gateway/internal/infrastructure/kubernetes/ratelimit      1.053s
> go test -timeout 30s github.com/envoyproxy/gateway/internal/infrastructure/kubernetes/proxy --override-testdata=true
> ok      github.com/envoyproxy/gateway/internal/infrastructure/kubernetes/proxy  1.089s
> go test -timeout 30s github.com/envoyproxy/gateway/internal/xds/bootstrap --override-testdata=true
> ok      github.com/envoyproxy/gateway/internal/xds/bootstrap    0.797s
> go test -timeout 60s github.com/envoyproxy/gateway/internal/gatewayapi --override-testdata=true
> ok      github.com/envoyproxy/gateway/internal/gatewayapi       7.889s
> ===========> Running gen-check ... 
> ===========> ERROR: Some files need to be updated
> diff --git a/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml b/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml
> index 2190e623..a23e6567 100644
> --- a/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml
> +++ b/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_backendtrafficpolicies.yaml
> @@ -510,7 +510,7 @@ spec:
>                loadBalancer:
>                  description: |-
>                    LoadBalancer policy to apply when routing traffic from the gateway to
> -                  the backend endpoints
> +                  the backend endpoints. Defaults to `LeastRequest`.
>                  properties:
>                    consistentHash:
>                      description: |-
> diff --git a/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyextensionpolicies.yaml b/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyextensionpolicies.yaml
> index 5b88ec48..74a91b66 100644
> --- a/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyextensionpolicies.yaml
> +++ b/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyextensionpolicies.yaml
> @@ -624,7 +624,7 @@ spec:
>                          loadBalancer:
>                            description: |-
>                              LoadBalancer policy to apply when routing traffic from the gateway to
> -                            the backend endpoints
> +                            the backend endpoints. Defaults to `LeastRequest`.
>                            properties:
>                              consistentHash:
>                                description: |-
> diff --git a/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml b/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
> index 436a3331..5359569c 100644
> --- a/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
> +++ b/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_envoyproxies.yaml
> @@ -10922,7 +10922,7 @@ spec:
>                                            loadBalancer:
>                                              description: |-
>                                                LoadBalancer policy to apply when routing traffic from the gateway to
> -                                              the backend endpoints
> +                                              the backend endpoints. Defaults to `LeastRequest`.
>                                              properties:
>                                                consistentHash:
>                                                  description: |-
> @@ -11812,7 +11812,7 @@ spec:
>                                            loadBalancer:
>                                              description: |-
>                                                LoadBalancer policy to apply when routing traffic from the gateway to
> -                                              the backend endpoints
> +                                              the backend endpoints. Defaults to `LeastRequest`.
>                                              properties:
>                                                consistentHash:
>                                                  description: |-
> @@ -12757,7 +12757,7 @@ spec:
>                                      loadBalancer:
>                                        description: |-
>                                          LoadBalancer policy to apply when routing traffic from the gateway to
> -                                        the backend endpoints
> +                                        the backend endpoints. Defaults to `LeastRequest`.
>                                        properties:
>                                          consistentHash:
>                                            description: |-
> @@ -13657,7 +13657,7 @@ spec:
>                                loadBalancer:
>                                  description: |-
>                                    LoadBalancer policy to apply when routing traffic from the gateway to
> -                                  the backend endpoints
> +                                  the backend endpoints. Defaults to `LeastRequest`.
>                                  properties:
>                                    consistentHash:
>                                      description: |-
> diff --git a/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml b/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml
> index da5eed29..394fddd6 100644
> --- a/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml
> +++ b/charts/gateway-helm/crds/generated/gateway.envoyproxy.io_securitypolicies.yaml
> @@ -830,7 +830,7 @@ spec:
>                            loadBalancer:
>                              description: |-
>                                LoadBalancer policy to apply when routing traffic from the gateway to
> -                              the backend endpoints
> +                              the backend endpoints. Defaults to `LeastRequest`.
>                              properties:
>                                consistentHash:
>                                  description: |-
> @@ -1633,7 +1633,7 @@ spec:
>                            loadBalancer:
>                              description: |-
>                                LoadBalancer policy to apply when routing traffic from the gateway to
> -                              the backend endpoints
> +                              the backend endpoints. Defaults to `LeastRequest`.
>                              properties:
>                                consistentHash:
>                                  description: |-
> gmake[1]: *** [tools/make/lint.mk:82: gen-check] Error 1
> gmake[1]: Leaving directory '/Users/lk/personal/envoy-gateway'
> gmake: *** [Makefile:18: _run] Error 2
> ```
> 
> The diff files shown above in error from what i can see got autogenerated while `===========> Running go.testdata.complete ... ` step was running.
> 
> Is there some step/change i am missing here ?

commit them

**Comment by luvk1412** [comment]
@zirain committed the gen-check changes. `make gen-check` runs successfully on local.

**Review by shawnh2 — APPROVED** [review]

**Review by zirain — APPROVED** [review]

**Pull request merged**
