### PR TITLE
refactor: refactor TCP IR

### PR DESCRIPTION
**Pull request by aoledk**
Takes forward PR https://github.com/envoyproxy/gateway/pull/1976 and https://github.com/envoyproxy/gateway/pull/1798

Fixes: https://github.com/envoyproxy/gateway/issues/1635

### CODE REVIEW

**Comment by aoledk** [comment]
@arkodg I rebased your branch https://github.com/arkodg/gateway/tree/tls-ir-fix on the latest main branch, and adjusted `TCPListener` and `TCPRoute` fields according to `BackendTrafficPolicy` support for TCP Listener.

BTW, `TCPListener.TCPKeepalive` is not filled, because current main branch uses `TCPKeepalive` from `BackendTrafficPolicy` in both xDS TCP Listener and xDS Cluster. Which is not correct. We should use `TCPKeepalive` from `ClientTrafficPolicy` in xDS TCP Listener after https://github.com/envoyproxy/gateway/issues/3163 is implemented.

**Comment by arkodg** [comment]
thanks for taking the PR forward @aoledk ! will try to review this one soon before another round of merges making this refractor hard 
the keep alive issue is being tracked with https://github.com/envoyproxy/gateway/issues/3032 :)

**Review by arkodg — DISMISSED** [review]
LGTM thanks for taking this one forward

**Comment by arkodg** [comment]
hey @aoledk there are some CI failures, running `make generate` and fixing the new format for the xds test should fix it

**Review by arkodg — APPROVED** [review]

**Review by zhaohuabing — APPROVED** [review]
LGTM Thanks!

**Pull request merged**
