### PR TITLE
Relax Listener TLS CertRef constaints

### PR DESCRIPTION
**Pull request by arkodg**
* Fixes https://github.com/envoyproxy/gateway/issues/1275
* Also fixes https://github.com/envoyproxy/gateway/issues/1290 since we use a list instead of a map to generate a deterministic output

### CODE REVIEW

**Comment by arkodg** [comment]
docs for #1275 can be added in a follow up PR

**Review by qicz — APPROVED** [review]
LGTM

**Review by zhaohuabing — APPROVED** [review]
LGTM

BTW, why there was this one secret/cert per alog constraint in the first place?

**Review by Xunzhuo — DISMISSED** [review]
LGTM

**Comment by Xunzhuo** [comment]
Conformance is failed cc @arkodg

**Comment by arkodg** [comment]
@Xunzhuo its failing because of https://github.com/envoyproxy/gateway/issues/1268

**Review by chauhanshubham — APPROVED** [review]
thanks @arkodg 
In addition to this, I was also thinking if we could add status updates or validations for the following two scenarios
- single fqn has conflicting certs configured with same algo (the removed test basically)
- no valid cert is found for an fqn
also discussed here https://github.com/envoyproxy/envoy/issues/21739#issuecomment-1158688548 and https://github.com/envoyproxy/envoy/issues/21739#issuecomment-1176086430 in the same issue

**Comment by arkodg** [comment]
> thanks @arkodg In addition to this, I was also thinking if we could add status updates or validations for the following two scenarios
> 
> * single fqn has conflicting certs configured with same algo (the removed test basically)
> * no valid cert is found for an fqn
>   also discussed here [SNI-based cert selection in TLS transport socket envoy#21739 (comment)](https://github.com/envoyproxy/envoy/issues/21739#issuecomment-1158688548) and [SNI-based cert selection in TLS transport socket envoy#21739 (comment)](https://github.com/envoyproxy/envoy/issues/21739#issuecomment-1176086430) in the same issue

thanks for highlighting the edge cases, let me raise an issue for this

**Pull request merged**
