### PR TITLE
e2e: add CEL to accesslog test

### PR DESCRIPTION
**Pull request by zirain**
fix: https://github.com/envoyproxy/gateway/issues/3735

### CODE REVIEW

**Comment by zirain** [comment]
Positive test worked as expected.

**Review by guydc — DISMISSED** [review]
LGTM

**Comment by zirain** [comment]
will add negetive tests in this one.

**Review by zhaohuabing — APPROVED** [review]
LGTM thanks!

**Review by shawnh2 — APPROVED** [review]
LGTM!

**Pull request merged**
