### PR TITLE
feat: enable leader-election for eg controllers

### PR DESCRIPTION
**Pull request by Xunzhuo**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/envoyproxy/gateway/issues/1953

### CODE REVIEW

**Review by qicz — APPROVED** [review]

**Comment by zhaohuabing** [comment]
Do we need it?  Can multiple EG pods run in parallel?

**Comment by Xunzhuo** [comment]
> Do we need it? Can multiple EG pods run in parallel to share the workload?

@zhaohuabing, yes and like the question raised in https://github.com/envoyproxy/gateway/issues/1953:

We need to find out which is more expensive - enabling leader election and EG sending heartbeats to API server or multiple EG writing status back for same resource.

**Comment by qicz** [comment]
> > Do we need it? Can multiple EG pods run in parallel to share the workload?
> 
> @zhaohuabing, yes and like the question raised in #1953:
> 
> We need to find out which is more expensive - enabling leader election and EG sending heartbeats to API server or multiple EG writing status back for same resource.

In fact, We just one replicas on prod env. but we can enable leader election and set the replicas `1`

**Comment by zhaohuabing** [comment]
I am inclined to enable leader election by default. But we may need a knob in configuration to allow users to disable it in case that they have a fleet of Envoy instances and want to have multiple EG instances to share the workload of the XDS server.

**Comment by Xunzhuo** [comment]
> I am inclined to enable leader election by default. But we may need a knob in configuration to allow users to disable it in case that they have a fleet of Envoy instances and want to have multiple EG instances to share the workload of the XDS server.

Yep, this should be configurable in Envoy Gateway Config.

**Comment by Xunzhuo** [comment]
Let us make this into draft for now.

**Comment by liorokman** [comment]
If leader election is enabled and the number of Envoy Gateway instances is >1, then will the XDS server on envoy instances that are not the leader return correct XDS information? 

As far as I can tell, the readiness probe that is [configured](https://github.com/envoyproxy/gateway/blob/main/internal/provider/kubernetes/kubernetes.go#L72) in the Envoy Gateway deployment always returns true.

In non-leader pods, does this not mean that the Kubernetes provider won't get notified or watch any resources and the XDS server provided by those non-leader pods will not contain valid information?

Because as long as the pods return "ready" in their readiness probe, traffic from Envoy Proxy to the gRPC XDS endpoint might get routed to one of these non-leader pods, and the Envoy EProxy configuration will be bad. 

This would mean that simply turning on the "leaderElection" flag is not a good idea.

**Comment by arkodg** [comment]
hey @liorokman, you're right that this PR is not enough, had added some thoughts earlier in https://github.com/envoyproxy/gateway/issues/1953#issuecomment-1806263460

**Comment by Xunzhuo** [comment]
close this and tracked in https://github.com/envoyproxy/gateway/issues/1953

**Pull request closed without merging**
