### PR TITLE
fix: ensure all updates are processed in xds ir update test

### PR DESCRIPTION
**Pull request by dboslee**
**What this PR does / why we need it**:
TestXdsIRUpdates added in #1795 is flaky. This adds a sleep to reduce the chance of failing. Open to suggestions to avoid the sleep but this pattern is also used in another test here https://github.com/envoyproxy/gateway/blob/080674a93bc42504575d7c0c83d21300abbb6e00/internal/message/watchutil_test.go#L43

### CODE REVIEW

**Comment by arkodg** [comment]
how about using `require.Eventually` e.g. in [here](https://github.com/envoyproxy/gateway/blob/080674a93bc42504575d7c0c83d21300abbb6e00/internal/xds/translator/runner/runner_test.go#L82) ?

**Comment by arkodg** [comment]
would be good to test this with `go test ./... -count=20`

**Comment by dboslee** [comment]
> how about using `require.Eventually` e.g. in [here](https://github.com/envoyproxy/gateway/blob/080674a93bc42504575d7c0c83d21300abbb6e00/internal/xds/translator/runner/runner_test.go#L82) ?

@arkodg updated in https://github.com/envoyproxy/gateway/pull/1799/commits/5fcae5d4990ff97ae63da3a550ad0d173c3d854c

require.Eventually didn't exactly fit here. Checking that the number of updates is eventually equal to the desired value could work but could also give a false positive where the number of updates would have been incremented past the desired value otherwise.

This updates version of the test uses the `start` and `end` keys to indicate the first and last updates so we know when to close the map and ensure that all events have been processed.

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Review by zirain — APPROVED** [review]

**Pull request merged**
