### PR TITLE
feat: support custom StatsdExporter image

### PR DESCRIPTION
**Pull request by zirain**
Before make ratelimit support native prometheus endpoint, this patch will close https://github.com/envoyproxy/gateway/issues/3049.

### CODE REVIEW

**Comment by zhaohuabing** [comment]
@zirain Could we use `KubernetesPatchSpec` as a workaround for this?  

A `StatsdExporter` in `EnvoyGateway` API seems confusing for me as this is for Ratelimit, not for Envoy Gateway deployment. (Even the existing `ShutdownManager` should not be there, it's my bad).

**Comment by zirain** [comment]
> @zirain Could we use `KubernetesPatchSpec` as a workaround for this?
> 
> A `StatsdExporter` in `EnvoyGateway` API seems confusing for me as this is for Ratelimit, not for Envoy Gateway deployment. (Even the existing `ShutdownManager` should not be there, it's my bad).

Of course you can do that way, but TBH I think this's not a too bad idea.

**Comment by zhaohuabing** [comment]
I suggest we support it with `KubernetesPatchSpec` and wait for native prometheus endpoint support in ratelimit,  @envoyproxy/gateway-maintainers please weight in.

**Comment by zirain** [comment]
close since `KubernetesPatchSpec` support this.

**Pull request closed without merging**
