### PR TITLE
Fix typo: gatewy

### PR DESCRIPTION
**Pull request by vinaysrini**
**What type of PR is this?**
* "docs: fixes typo gatewy to gateway"

**What this PR does / why we need it**:
Simple typo fix
**Which issue(s) this PR fixes**:
Fixes documentation typo

### CODE REVIEW

**Review by zirain — APPROVED** [review]

**Comment by zirain** [comment]
is it same for latest?

**Comment by arkodg** [comment]
thanks @vinaysrini can you also update the same file in https://github.com/envoyproxy/gateway/tree/main/site/content/en/latest with the same change

**Comment by vinaysrini** [comment]
Updated in latest as well.

**Comment by zirain** [comment]
please fix DCO

**Comment by vinaysrini** [comment]
will redo this. got very confusing with multiple commits and DCO rejects

**Pull request closed without merging**
