### PR TITLE
api: increase rate-limit global rules limit

### LINKED ISSUE #2900: Increase Rate Limit Rules Limit
*Description*:

Current limit is 16 https://github.com/envoyproxy/gateway/blob/87eb55560ef9bd37ca0112c573c16f2656c0809c/api/v1alpha1/ratelimit_types.go#L52 and users have already started hitting it.

Recommend increasing it to 64

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

### PR DESCRIPTION
**Pull request by ShyunnY**
**What type of PR is this?**

feat: increase rate-limit global rules limit

**Which issue(s) this PR fixes**:

Fixes #2900

### CODE REVIEW

**Review by shawnh2 — APPROVED** [review]

**Comment by zirain** [comment]
can you add test for this? positive and negative.

**Comment by shawnh2** [comment]
> can you add test for this? positive and negative.

hi @ShyunnY, maybe add a test in `test/cel-validation/backendtrafficpolicy_test.go` to ensure the CEL validation.

**Comment by ShyunnY** [comment]
Sorry, this was an oversight on my part. I have added

**Review by arkodg — APPROVED** [review]
LGTM thanks for adding the test !

**Review by zirain — APPROVED** [review]

**Pull request merged**
