### PR TITLE
Allow upgrade to websocket for HTTP 1.1 listeners

### PR DESCRIPTION
**Pull request by arkodg**
Fixes: https://github.com/envoyproxy/gateway/issues/836

Signed-off-by: Arko Dasgupta <arko@tetrate.io>

### CODE REVIEW

**Comment by arkodg** [comment]
@skriss @AliceProxy does Contour and Emissary have this upgrade enabled by default as well, similar to Istio ?

**Review by Xunzhuo — COMMENTED** [review]
Or should we use configuration to determine if we use websocket or not?

**Comment by arkodg** [comment]
> Or should we use configuration to determine if we use websocket or not?

@Xunzhuo can you share any reason why a user might have web sockets enabled in the app backend but would like to force disable it in the proxy ?
imho this commit enables web socket upgrade proxying based on client-server web socket capability, and enabling it by default is helping the HTTPRoute owner (app developer) set one less thing to get their apps connected to the outside world.

**Review by Xunzhuo — DISMISSED** [review]
Sorry maybe I overthink it, LGTM, thanks!

**Comment by AliceProxy** [comment]
Emissary will not upgrade to websockets unless explicitly configured by the user

**Comment by skriss** [comment]
Contour's is also opt-in on a per-route basis.

**Comment by arkodg** [comment]
thanks @AliceProxy and @skriss for sharing Emissary's and Contour's implementation. 
I proposed enabling it by default for now (and changing this behavior in the future in case the upstream Gateway API is explicit about this feature being opt-in) in the community meeting today and did not receive any objection

**Review by Xunzhuo — APPROVED** [review]

**Pull request merged**
