### PR TITLE
feat(chart): Make security context configurable

### LINKED ISSUE #3887: Add Support for modifying Pod and Container SecurityContext for Envoy Gateway deploment in Helm
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

### PR DESCRIPTION
**Pull request by tamalsaha**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #3887

Release Notes: 
Add support for modifying container securityContext for Envoy Gateway deployment in Helm

### CODE REVIEW

**Comment by arkodg** [comment]
thanks for the PR @tamalsaha, this fixes https://github.com/envoyproxy/gateway/issues/3887
can you also add a test in https://github.com/envoyproxy/gateway/tree/main/test/helm that validate the custom overwrite

**Comment by zirain** [comment]
you need to run `make gen-check` locally.

**Comment by tamalsaha** [comment]
Done. PTAL.

**Review by zirain — APPROVED** [review]

**Comment by zhaohuabing** [comment]
@tamalsaha Thanks for working on this. Would you please share your use case on this? I'm curious - does the default SecurityContext fall short of meeting your requirements?

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Comment by zhaohuabing** [comment]
@tamalsaha Can we add a brief description in the release note?

**Comment by zhaohuabing** [comment]
> Added release note.

Please modify this file and include it in this PR: https://github.com/envoyproxy/gateway/blob/main/release-notes/current.yaml

**Comment by zhaohuabing** [comment]
> Add Support for modifying Pod and Container SecurityContext for Envoy Gateway deployment in Helm

This PR only add supports for container-level SecurityContext.

**Comment by tamalsaha** [comment]
Updated description

**Review by zhaohuabing — CHANGES_REQUESTED** [review]
Please modify this file and include it in this PR: https://github.com/envoyproxy/gateway/blob/main/release-notes/current.yaml

**Comment by tamalsaha** [comment]
Updated current.yaml

**Review by arkodg — APPROVED** [review]

**Comment by arkodg** [comment]
> > Add Support for modifying Pod and Container SecurityContext for Envoy Gateway deployment in Helm
> 
> This PR only add support for container-level SecurityContext.
> 
> @arkodg do we also want to allow customizing SecurityContext on the pod level? I am still interested to know the use cases for this @tamalsaha @arkodg as users typically won't need addtional permissions to run EG - do they use a custom EG image that may need more permissions than the original one?

fine with keeping it simple, with this existing implementation

**Review by zhaohuabing — APPROVED** [review]

**Pull request merged**
