### PR TITLE
[provider/kubernetes]: Watch Service objects under httpRouteReconciler

### LINKED ISSUE #189: Add Service Watch to HTTPRoute Controller
*Description*:
Add a Service controller to the Kubernetes Provider package similar to the [HTTP Route Controller](https://github.com/envoyproxy/gateway/pull/179) that will be needed by the [Gateway API Translator](https://github.com/envoyproxy/gateway/blob/c83b7b04530f1cbdeb4e9596d0781eb8a2e1317b/internal/gatewayapi/translator.go#L23)

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

### PR DESCRIPTION
**Pull request by chauhanshubham**
Adds a Service watcher in httpRouteReconciler to watch for Service CRUDs.
This also pushes affected HTTPRoutes for reconciliation when referenced
Service objects are created/updated/deleted.

_Other minor updates include -_
Fixing gatewayReconciler issue to initialise obj list. Object list variable should be 
initialised before calling client.List(...). Prior to this it was being set to nil which
caused issues in the controller workflow.
Cleanup DefaultEnvoyGateway on server startup

Resolves #189

### CODE REVIEW

**Comment by arkodg** [comment]
thanks for picking this issue up @chauhanshubham ! hoping this PR can be raised once https://github.com/envoyproxy/gateway/pull/193 is merged so that the `Service` resources can be appended into the provider `ResourceTable`

**Comment by chauhanshubham** [comment]
> thanks for picking this issue up @chauhanshubham ! hoping this PR can be reworked on once #193 is merged so that the `Service` resources can be appended into the provider `ResourceTable`

Sure, having a look at that right now, will include changes once the PR gets merged. I'm guessing we'll just need HTTPRoute to be published, when associated Service CRUD happens. At the consuming side, we can get the referenced Service NamespaceName from HTTPRoute spec itself.

**Comment by arkodg** [comment]
> > thanks for picking this issue up @chauhanshubham ! hoping this PR can be reworked on once #193 is merged so that the `Service` resources can be appended into the provider `ResourceTable`
> 
> Sure, having a look at that right now, will include changes once the PR gets merged. I'm guessing we'll just need HTTPRoute to be published, when associated Service CRUD happens. At the consuming side, we can get the referenced Service NamespaceName (and then obj spec) from HTTPRoute spec itself.

yeah that approach sgtm

**Review by danehans — APPROVED** [review]
Thanks for the PR!

**Review by kflynn — APPROVED** [review]
Looks pretty sane from here...

**Review by AliceProxy — APPROVED** [review]
lgtm

**Pull request merged**
