### PR TITLE
Fix attachedRoutes computation

### PR DESCRIPTION
**Pull request by arkodg**
* Fixes: https://github.com/envoyproxy/gateway/issues/2077
* Fixes: https://github.com/envoyproxy/gateway/issues/1916

### CODE REVIEW

**Comment by arkodg** [comment]
I've been able to fix the issue around `AttachedRoute`, but the conformance test is still failing due to status issue
* It is expecting the listener condition to have `Accepted` set, see [here](https://github.com/kubernetes-sigs/gateway-api/blob/ee42a6d5d81283d9f41a85627b93e4492b876638/conformance/tests/gateway-with-attached-routes.go#L103)
* but EG doesnt set it, and only sets `Programmed` & `ResolvedRefs` to `False` 
```
  status:
    conditions:
    - lastTransitionTime: "2023-10-27T01:38:14Z"
      message: The Gateway has been scheduled by Envoy Gateway
      observedGeneration: 2
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2023-10-27T01:38:14Z"
      message: No addresses have been assigned to the Gateway
      observedGeneration: 2
      reason: AddressNotAssigned
      status: "False"
      type: Programmed
    listeners:
    - attachedRoutes: 1
      conditions:
      - lastTransitionTime: "2023-10-27T01:38:14Z"
        message: Secret gateway-conformance-infra/does-not-exist does not exist.
        observedGeneration: 2
        reason: InvalidCertificateRef
        status: "False"
        type: ResolvedRefs
      - lastTransitionTime: "2023-10-27T01:38:14Z"
        message: Listener is invalid, see other Conditions for details.
        observedGeneration: 2
        reason: Invalid
        status: "False"
        type: Programmed
```

* AFAIK for this case `Accepted` doesnt need to be `True` since we may not generate any data plane config for this case, ([here](https://github.com/kubernetes-sigs/gateway-api/blob/ee42a6d5d81283d9f41a85627b93e4492b876638/apis/v1/gateway_types.go#L918) is the definition )

cc @danehans

**Comment by arkodg** [comment]
blocked on https://github.com/kubernetes-sigs/gateway-api/pull/2535

**Comment by arkodg** [comment]
there's another issue around a typo for `Accepted` condition to be `False` instead of `True`
```
- apiVersion: gateway.networking.k8s.io/v1
  kind: HTTPRoute
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"gateway.networking.k8s.io/v1beta1","kind":"HTTPRoute","metadata":{"annotations":{},"name":"http-route-4","namespace":"gateway-conformance-infra"},"spec":{"parentRefs":[{"kind":"Gateway","name":"unresolved-gateway-with-one-attached-unresolved-route","namespace":"gateway-conformance-infra","sectionName":"tls"}],"rules":[{"backendRefs":[{"name":"does-not-exist","port":8080}]}]}}
    creationTimestamp: "2023-10-27T01:35:27Z"
    generation: 1
    name: http-route-4
    namespace: gateway-conformance-infra
    resourceVersion: "1627"
    uid: fc991161-b6a4-459c-85c6-f814fee121bb
  spec:
    parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: unresolved-gateway-with-one-attached-unresolved-route
      namespace: gateway-conformance-infra
      sectionName: tls
    rules:
    - backendRefs:
      - group: ""
        kind: Service
        name: does-not-exist
        port: 8080
        weight: 1
      matches:
      - path:
          type: PathPrefix
          value: /
  status:
    parents:
    - conditions:
      - lastTransitionTime: "2023-10-27T01:38:14Z"
        message: There are no ready listeners for this parent ref
        observedGeneration: 1
        reason: NoReadyListeners
        status: "False"
        type: Accepted
      - lastTransitionTime: "2023-10-27T01:38:14Z"
        message: Service gateway-conformance-infra/does-not-exist not found
        observedGeneration: 1
        reason: BackendNotFound
        status: "False"
        type: ResolvedRefs
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
      parentRef:
        group: gateway.networking.k8s.io
        kind: Gateway
        name: unresolved-gateway-with-one-attached-unresolved-route
        namespace: gateway-conformance-infra
        sectionName: tls
kind: List
metadata:
  resourceVersion: ""
  ```

**Review by zirain — DISMISSED** [review]

**Review by zirain — APPROVED** [review]

**Review by Xunzhuo — APPROVED** [review]
Thanks

**Pull request merged**
