### PR TITLE
feat(translator): Implement header hash policy for consistent hash load balancers

### LINKED ISSUE #3341: Add support for the header hash policy in the consistent hash load balancer
*Description*:

[Slack discussion here.](https://envoyproxy.slack.com/archives/C03E6NHLESV/p1715069442245479)

While Envoy itself supports a [range of hash policies](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-routeaction-hashpolicy) for consistent hash load balancing, the Envoy Gateway can only be configured with the [ConnectionProperties](https://github.com/envoyproxy/envoy/blob/8937b3d0bd28ed9f60e44744f4ad24149dee5d85/api/envoy/config/route/v3/route_components.proto#L896-L902) policy via the [SourceIP](https://gateway.envoyproxy.io/v1.0.1/api/extension_types/#consistenthashtype) consistent hash type. This is insufficient for situations where session affinity must be based on a sharding key that is in a request header.

For example, a request might include an resource identifier in a request header. When the request is processed, that resource will be cached on the upstream, so subsequent requests should be routed to the same instance. This routing must be done based on the value of that header, rather than the source IP address, which can change for a variety of reasons[^1].

Specifically, we want this feature to implement session affinity for gRPC messages based on their [protocol headers.](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md)

[^1]: Whenever the downstream scales up/down, or for an public deployment, or when the client device roams and undergoes a network handover (which causing the connection to be reestablished), NAT rebinding, etc

*Any extra documentation required to understand the issue.*

* [ConnectionProperties proto](https://github.com/envoyproxy/envoy/blob/8937b3d0bd28ed9f60e44744f4ad24149dee5d85/api/envoy/config/route/v3/route_components.proto#L896-L902)
* [ConsistentHashType documentation](https://gateway.envoyproxy.io/v1.0.1/api/extension_types/#consistenthashtype)

### PR DESCRIPTION
**Pull request by harrisonturton**
**What type of PR is this?**

Adds a new feature to the translator.

**What this PR does / why we need it**:

This PR adds support for the [Header](https://github.com/envoyproxy/envoy/blob/8bc2e917519936ab4cb1e9fa52fd5456a4fce4f7/api/envoy/config/route/v3/route_components.proto#L834-L846) hash policy in the Envoy Gateway API, which will allow users the configure the Envoy Gateway to use session affinity based on the value of a header.

See #3341 for justification, discussed in [this Slack thread.](https://envoyproxy.slack.com/archives/C03E6NHLESV/p1715069442245479) The user-facing API changes were introduced in #3342, this PR implements them.

**Which issue(s) this PR fixes**:

Fixes #3341

### CODE REVIEW

**Comment by harrisonturton** [comment]
I think these CI failures are flakes. They are `context deadline exceeded` errors and seem to be unrelated to my changes.

**Review by shawnh2 — APPROVED** [review]
LGTM! Thanks for adding this.

**Review by cnvergence — APPROVED** [review]

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Pull request merged**
