### PR TITLE
docs: patch field within EnvoyService

### LINKED ISSUE #2904: docs: patch field within EnvoyService and EnvoyDeployment
*Description*:
>Describe the issue.

Add docs on how a user can patch the EnvoyService and EnvoyDeployment
https://gateway.envoyproxy.io/latest/api/extension_types/#kubernetesservicespec
https://gateway.envoyproxy.io/latest/api/extension_types/#kubernetesdeploymentspec

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

### PR DESCRIPTION
**Pull request by shawnh2**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #2904

### CODE REVIEW

**Comment by zhaohuabing** [comment]
Nit: clienttrafficpolicy is unlikely to be changed? Could we use a more realistic example, e.g, add a annotation ?

**Review by zirain — APPROVED** [review]

**Comment by shawnh2** [comment]
> Nit: clienttrafficpolicy is unlikely to be changed? Could we use a more realistic example, e.g, add a annotation ?

sounds great

**Review by zirain — APPROVED** [review]

**Pull request merged**
