### PR TITLE
chore: update grafana dashboards

### LINKED ISSUE #3703: Export WASM metrics into Grafana dashboard
*Description*:
>Describe the issue.

Export WASM metrics (https://github.com/envoyproxy/gateway/blob/main/internal/wasm/metrics.go) into Grafana dashboard (https://github.com/envoyproxy/gateway/blob/main/charts/gateway-addons-helm/dashboards/envoy-gateway-global.json) by adding a new row in that dashboard.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

remove TODO in https://github.com/envoyproxy/gateway/blob/51c6eb4b392859afe744c3157aca0975422876d9/internal/wasm/metrics.go#L54

### PR DESCRIPTION
**Pull request by shawnh2**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

follow-up of #3727, fix #3703

### CODE REVIEW

**Comment by zirain** [comment]
can you try to refactor dashboard with https://github.com/istio/istio/blob/395b9bb706a4fcb8633beac188b64707d7e7a1f1/manifests/addons/dashboards/README.md to make it maintainable?

**Comment by shawnh2** [comment]
> can you try to refactor dashboard with https://github.com/istio/istio/blob/395b9bb706a4fcb8633beac188b64707d7e7a1f1/manifests/addons/dashboards/README.md to make it maintainable?

this may require a lot of refactor work, raise another issue to track it.

**Review by zirain — APPROVED** [review]

**Review by Xunzhuo — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
