### PR TITLE
bugfix: fatal error: concurrent map writes

### LINKED ISSUE #3985: fatal error: concurrent map writes
*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
>Include the access logs and the Envoy logs.
  text:
  - path: /dev/stdout
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 14 [running]:
github.com/envoyproxy/gateway/internal/metrics.(*Gauge).With(0xc0007afe00, {0xc000a41cf8?, 0x0?, 0x0?})
	/build/internal/metrics/otel_metric_gauge.go:50 +0x31b
github.com/envoyproxy/gateway/internal/message.HandleSubscription[...]({{0x32510cc, 0x8?}, {0x325dfa5?, 0xe?}}, 0xc000a341e0?, 0xc000d0ffb0)
	/build/internal/message/watchutil.go:73 +0x1033
github.com/envoyproxy/gateway/internal/provider/kubernetes.(*gatewayAPIReconciler).subscribeAndUpdateStatus.func1()
	/build/internal/provider/kubernetes/status.go:31 +0xa8
created by github.com/envoyproxy/gateway/internal/provider/kubernetes.(*gatewayAPIReconciler).subscribeAndUpdateStatus in goroutine 1
	/build/internal/provider/kubernetes/status.go:30 +0x7d

goroutine 1 [chan receive]:
github.com/envoyproxy/gateway/internal/cmd.setupRunners(0xc0006b6fc0)
	/build/internal/cmd/server.go:203 +0x6ac
github.com/envoyproxy/gateway/internal/cmd.server()
	/build/internal/cmd/server.go:62 +0x54
github.com/envoyproxy/gateway/internal/cmd.getServerCommand.func1(0xc0003cd600?, {0x324a6f7?, 0x4?, 0x324a607?})
	/build/internal/cmd/server.go:36 +0xf
github.com/spf13/cobra.(*Command).execute(0xc0006a9808, {0xc000329cc0, 0x1, 0x1})
	/build/vendor/github.com/spf13/cobra/command.go:985 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc0006a9208)
	/build/vendor/github.com/spf13/cobra/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0xc0006a9208?)
	/build/vendor/github.com/spf13/cobra/command.go:1041 +0x13
main.main()
	/build/cmd/cc/main.go:19 +0x55

### PR DESCRIPTION
**Pull request by qicz**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #3985

### CODE REVIEW

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Review by shawnh2 — APPROVED** [review]

**Comment by zirain** [comment]
we need a test to guratee this

**Comment by arkodg** [comment]
> we need a test to guratee this

can you add a test @qicz ?

**Pull request merged**
