### PR TITLE
feat(translator): Implement BTP TCPKeepAlive

### LINKED ISSUE #1031: KeepAlive support
*Description*:
As a user I would like to enable and configure tcp keep-alive for 2 cases 
* downstream with client
* upstream with server

here is the config needed in Envoy
* upstream
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/address.proto#config-core-v3-tcpkeepalive

* downstream
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/socket_option.proto#config-core-v3-socketoption

How other Envoy based implementations express this as an API

* Emissary has support https://www.getambassador.io/docs/emissary/latest/topics/using/keepalive#keepalive (unsure if this is downstream or upstream socket)
* Istio supports Upstream Keepalive https://istio.io/v1.1/docs/reference/config/networking/v1alpha3/destination-rule/#ConnectionPoolSettings-TCPSettings-TcpKeepalive
* Contour : TODO

### PR DESCRIPTION
**Pull request by guydc**
**What this PR does / why we need it**:
Implements upstream TCP keep alive API in BakcendTrafficPolicy.

**Which issue(s) this PR fixes**:
Fixes #1031

### CODE REVIEW

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Review by shawnh2 — APPROVED** [review]
LGTM

**Review by arkodg — APPROVED** [review]

**Pull request merged**
