### PR TITLE
chore: remove cherrypicker action

### PR DESCRIPTION
**Pull request by zirain**
this action didn't work for a long time, let's remove it now to reduce some nosie.

### CODE REVIEW

**Review by Xunzhuo — COMMENTED** [review]
why there are some go mod changes>

**Comment by zirain** [comment]
> why there are some go mod changes>

goland cause

**Comment by Xunzhuo** [comment]
if so, we need to add lint to example server too, make sure its always go mod tidy

**Comment by zirain** [comment]
> if so, we need to add lint to example server too, make sure its always go mod tidy

removed, let me do that in seperated one.

**Review by Xunzhuo — APPROVED** [review]

**Review by arkodg — APPROVED** [review]

**Pull request merged**
