### PR TITLE
Support_Envoy_Gateway_pod_labels_and_annotations

### PR DESCRIPTION
**Pull request by rkosyk**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/envoyproxy/gateway/issues/1633

### CODE REVIEW

**Comment by arkodg** [comment]
should we directly expose `deployment.metdata` & `deployment.spec` as helm values so we dont need to keep adding helm templating for each sub field ?

**Comment by rkosyk** [comment]
> should we directly expose `deployment.metdata` & `deployment.spec` as helm values so we dont need to keep adding helm templating for each sub field ?

It is not recommended, as users don't need to have in-depth knowledge of Kubernetes object structures and syntax.

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Review by zirain — APPROVED** [review]

**Pull request merged**
