### PR TITLE
docs: remove comma

### PR DESCRIPTION
**Pull request by muffl0n**
**What this PR does / why we need it**:
Remove comma

### CODE REVIEW

**Comment by zirain** [comment]
please fix `latest` and `v1.1` then run `make -k gen-check`

**Comment by arkodg** [comment]
@muffl0n can you also fix  the same issue in `site/content/en/latest/tasks/quickstart.md` & `site/content/en/v1.1/tasks/quickstart.md`

**Comment by muffl0n** [comment]
Sure thing!

**Review by arkodg — APPROVED** [review]
thanks !

**Review by zirain — APPROVED** [review]

**Pull request merged**
