### PR TITLE
chore: update roadmap page

### PR DESCRIPTION
**Pull request by arkodg**

### CODE REVIEW

**Comment by zirain** [comment]
this worth a better place?

**Comment by arkodg** [comment]
> this worth a better place?

under `news` ? 

I dont see us using this page very often, based on commitment from contributors we add features into a release milestone

**Comment by zhaohuabing** [comment]
This may off-topic :-) but I feel a dedicated release page would be very useful. Many folks were asking about the next release date.

https://github.com/envoyproxy/envoy/blob/main/RELEASES.md

**Comment by arkodg** [comment]
> This may off-topic :-) but I feel a dedicated release page would be very useful. Many folks were asking about the next release date.
> 
> https://github.com/envoyproxy/envoy/blob/main/RELEASES.md

this lives in https://gateway.envoyproxy.io/news/releases/

**Comment by zhaohuabing** [comment]
> This may off-topic :-) but I feel a dedicated release page would be very useful. Many folks were asking about the next release date.
> 
> https://github.com/envoyproxy/envoy/blob/main/RELEASES.md

Oh, we already got one. Maybe just add the planned date for the next release.
https://gateway.envoyproxy.io/news/releases/

**Review by zhaohuabing — APPROVED** [review]

**Review by zirain — APPROVED** [review]

**Pull request merged**
