### PR TITLE
chore: bump golang to 1.22.3

### PR DESCRIPTION
**Pull request by shahar-h**
**What this PR does / why we need it**:
Bump `golang` version to `1.22.3` in order to resolve [GO-2024-2824 ](https://osv.dev/GO-2024-2824) .

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Review by arkodg — DISMISSED** [review]

**Review by zirain — APPROVED** [review]

**Comment by zirain** [comment]
seems not a flaky?

**Comment by shahar-h** [comment]
I changed `go 1.22` to `go 1.23` by accident in some e2e manifests, reverted: https://github.com/envoyproxy/gateway/pull/3351/commits/b2fc37b66537d757338102b44efd1cc3506bb5af

**Review by zirain — APPROVED** [review]

**Review by shawnh2 — APPROVED** [review]

**Pull request merged**
