### PR TITLE
ci: try to fix permissions for cherrypick action

### PR DESCRIPTION
**Pull request by zirain**
default action permissions:
image

cherrypick action permissions:

image

### CODE REVIEW

**Comment by arkodg** [comment]
so this PR reverts #1404 & #1428 ?

**Comment by zirain** [comment]
> so this PR reverts #1404 & #1428 ?

yes, and this's last try, if this PR not working, I have no idea about it.

**Comment by arkodg** [comment]
> > so this PR reverts #1404 & #1428 ?
> 
> yes, and this's last try, if this PR not working, I have no idea about it.

trying to understand how this will fix the issue

**Comment by zirain** [comment]
> 

make the setting as other action, expect to get same perrmissions when action setup

**Review by arkodg — APPROVED** [review]

**Review by Xunzhuo — APPROVED** [review]

**Pull request merged**
