### PR TITLE
forward jwt tokens after verification

### PR DESCRIPTION
**Pull request by zhaohuabing**
related: https://github.com/envoyproxy/gateway/issues/2295

### CODE REVIEW

**Comment by zirain** [comment]
is there a test for this?

**Comment by zhaohuabing** [comment]
> is there a test for this?

I think we don't need to add a test for this, it should work as long as jwt test passed.

**Comment by zirain** [comment]
> > is there a test for this?
> 
> I think we don't need to add a test for this, it should work as long as jwt test passed.

we need make sure it's there, avoid regression in the future.

**Comment by zhaohuabing** [comment]
> > > is there a test for this?
> > 
> > 
> > I think we don't need to add a test for this, it should work as long as jwt test passed.
> 
> we need make sure it's there, avoid regression in the future.

Totally agree if it's a bug. But if you look into the issue, it's actually a feature request other than a repeated bug. We don't want to add an individual e2e test for every single small configuration knob.

And the unit test should have already covered it.

**Review by zirain — APPROVED** [review]

**Review by Xunzhuo — APPROVED** [review]

**Pull request merged**
