### PR TITLE
feat: add CEL validation for EnvoyProxy telemetry

### PR DESCRIPTION
**Pull request by shawnh2**
**What type of PR is this?**

add missing unit test cases

**What this PR does / why we need it**:

some unit test cases are missing according to https://app.codecov.io/gh/envoyproxy/gateway/blob/main/api%2Fv1alpha1%2Fvalidation%2Fenvoyproxy_validate.go

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Review by zirain — APPROVED** [review]

**Review by zirain — CHANGES_REQUESTED** [review]
rethink about this, let's move to https://github.com/envoyproxy/gateway/pull/2059.

**Comment by arkodg** [comment]
@shawnh2 we've moved to CEL based validations, the newer tests live in https://github.com/envoyproxy/gateway/blob/main/test/cel-validation/envoyproxy_test.go, can we move the new test cases there instead and also make sure a CEL validation exists for it
cc @zirain

**Comment by shawnh2** [comment]
add missing CEL validation and test for `ProxyTelemetry`, PTAL @arkodg @zirain

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Review by zirain — APPROVED** [review]

**Pull request merged**
