### PR TITLE
performance: optimize by protobuf context-type.

### PR DESCRIPTION
**Pull request by qicz**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

replace #1596 
Fixes #

### CODE REVIEW

**Comment by zirain** [comment]
is there before-and-after data comparison?

**Comment by qicz** [comment]
current gateway API does not support protobuf. raised issue https://github.com/kubernetes-sigs/gateway-api/issues/3346#issue-2535691054

**Comment by qicz** [comment]
xref: https://github.com/envoyproxy/gateway/issues/4283#issuecomment-2370314094
https://github.com/envoyproxy/gateway/issues/4283#issuecomment-2378284177

EG has already support multi content-type by `controller-runtime`

**Pull request closed without merging**
