### PR TITLE
Fixes Initial Markdown Linter Errors

### PR DESCRIPTION
**Pull request by danehans**
Fixes Markdown linter errors from #572.

Signed-off-by: danehans <daneyonhansen@gmail.com>

### CODE REVIEW

**Comment by danehans** [comment]
cc: @Xunzhuo

**Comment by Xunzhuo** [comment]
Thanks @danehans, I was thinking doing this along with https://github.com/envoyproxy/gateway/pull/572, since it is a WIP. Changes look good to me, but this is not covered all lint errors, because we set many checkers to false.

**Review by arkodg — APPROVED** [review]

**Comment by danehans** [comment]
>Changes look good to me, but this is not covered all lint errors, because we set many checkers to false.
I updated the PR title accordingly.

**Comment by danehans** [comment]
No worries. I'll close this one.

**Pull request closed without merging**
