### PR TITLE
benchmark: test for 1000 HTTPRoutes

### PR DESCRIPTION
**Pull request by arkodg**

### CODE REVIEW

**Review by shawnh2 — APPROVED** [review]

**Comment by shawnh2** [comment]
Wait for the benchmark report.

**Comment by qicz** [comment]
IMO,  not only routes but also secrets and configmaps.

**Comment by arkodg** [comment]
seeing this error
```
2024-09-20T04:21:25.7708266Z ##[error]internal/cmd/options/global.go:10:2: k8s.io/cli-runtime@v0.31.1: Get "https://proxy.golang.org/k8s.io/cli-runtime/@v/v0.31.1.zip": stream error: stream ID 1; PROTOCOL_ERROR
```

**Comment by shawnh2** [comment]
seems 1000 httproutes will cause oom

**Comment by zirain** [comment]
give one more try after https://github.com/envoyproxy/gateway/pull/4454 merged.

**Comment by zirain** [comment]
@arkodg looks we're good now.

**Review by zirain — APPROVED** [review]

**Comment by arkodg** [comment]
### Metrics

|Test Name                |Envoy Gateway Memory (MiB)|Envoy Gateway CPU (s)|Envoy Proxy Memory (Avg) (MiB)|Envoy Proxy CPU (Avg) (s)|
|-                        |-                         |-                    |-                             |-                        |
|scale-up-httproutes-10   |107.11                    |0.74                 |25.85                         |30.44                    |
|scale-up-httproutes-50   |136.46                    |1.42                 |31.97                         |60.84                    |
|scale-up-httproutes-100  |136.98                    |2.75                 |38.13                         |91.64                    |
|scale-up-httproutes-300  |141.98                    |14.64                |60.31                         |124.75                   |
|scale-up-httproutes-500  |157.41                    |26.76                |80.52                         |158.63                   |
|scale-up-httproutes-1000 |179.77                    |57.89                |130.77                        |197.64                   |
|scale-down-httproutes-500|164.67                    |85.83                |130.91                        |233.84                   |
|scale-down-httproutes-300|152.14                    |96.66                |131.07                        |266.26                   |
|scale-down-httproutes-100|146.73                    |106.85               |127.11                        |298.33                   |
|scale-down-httproutes-50 |161.01                    |107.92               |127.04                        |329.02                   |
|scale-down-httproutes-10 |202.45                    |108.52               |126.36                        |359.48                   |

**Comment by zirain** [comment]
the last two seems a little strange

**Pull request merged**
