### PR TITLE
fix: format style & upgrade deprecated apis & use more readable name

### PR DESCRIPTION
**Pull request by qicz**
+ remove more unnecessary blank lines
+ refactor variable names to improve readability 
+ fix some Deprecated api

### CODE REVIEW

**Comment by qicz** [comment]
@arkodg pls review this pr and approval workflows , thank you

**Comment by Xunzhuo** [comment]
Plz sign your commit first, thanks @qicz.

**Comment by qicz** [comment]
> Plz sign your commit first, thanks @qicz.

did it @Xunzhuo

**Comment by Xunzhuo** [comment]
Can you provide more infos about what do you do in this PR, that could help our reviews. @qicz

**Comment by qicz** [comment]
> Can you provide more infos about what do you do in this PR, that could help our reviews. @qicz

- remove more unnecessary blank lines 
- Refactor variable names to improve readability

**Review by zirain — APPROVED** [review]

**Review by Xunzhuo — APPROVED** [review]

**Pull request merged**
