### PR TITLE
Cleans-Up Docs

### PR DESCRIPTION
**Pull request by danehans**
This PR simplifies the docs interface by:
- Removing the Envoy and Gateway API versions used. This is what the compatibility matrix is for.
- Adds links to ref'd Envoy Proxy and Gateway API.
- Expands the index to provide a brief introduction to the project.
- Removes the intro/index.rst and reference to it since this page was redundant with the docs homepage.
- Moves the note about EG being under active dev to the bottom of the docs homepage.

Signed-off-by: danehans <daneyonhansen@gmail.com>

### CODE REVIEW

**Review by AliceProxy — APPROVED** [review]

**Comment by AliceProxy** [comment]
Seems like a small lint error, but otherwise lgtm

**Review by Xunzhuo — COMMENTED** [review]
https://github.com/envoyproxy/gateway/blob/main/docs/conf.py#L35

Dont forget to remove the '+ fullversion' at the end. This is not ready too.

Others LGTM.

**Comment by Xunzhuo** [comment]
I suggest waiting for #639, after getting that merged, I think most of changes in this PR will not be needed.

**Comment by danehans** [comment]
Marking as Draft due to https://github.com/envoyproxy/gateway/pull/640#issuecomment-1287685091.

**Comment by danehans** [comment]
@Xunzhuo this PR still has changes that differ from #639. I rebased and updated so PTAL.

**Review by Xunzhuo — APPROVED** [review]
Looks good!

**Pull request merged**
