### PR TITLE
[release/v1.1] Pin ratelimit image to 26f28d78

### PR DESCRIPTION
**Pull request by arkodg**

### CODE REVIEW

**Comment by arkodg** [comment]
cc @zhaohuabing

**Review by guydc — APPROVED** [review]

**Review by zhaohuabing — APPROVED** [review]

**Review by zhaohuabing — APPROVED** [review]

**Review by zhaohuabing — APPROVED** [review]

**Comment by arkodg** [comment]
the wasm test is failing, @envoyproxy/gateway-maintainers any idea which PRs from main need to be backported into v1.1 to fix the flake ?

**Comment by zirain** [comment]
@arkodg can you try with https://github.com/envoyproxy/gateway/pull/4014?

**Comment by arkodg** [comment]
> @arkodg can you try with #4014?

thanks ! raised https://github.com/envoyproxy/gateway/pull/4151

**Comment by zirain** [comment]
> > @arkodg can you try with #4014?
> 
> thanks ! raised #4151

you may need rebase?

**Comment by arkodg** [comment]
thanks for the rebase @zirain !

**Pull request merged**
