### PR TITLE
feat: add metrics instrumentation for xds server

### LINKED ISSUE #2090: Implement Metrics instrumentation for xDS Server
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Implement Metrics instrumentation for xDS Server

### PR DESCRIPTION
**Pull request by shawnh2**
**What type of PR is this?**

**What this PR does / why we need it**:

image

**Which issue(s) this PR fixes**:

Fixes #2090

### CODE REVIEW

**Review by Xunzhuo — COMMENTED** [review]
I think we should have more histogram metrics for measuring the xds duration.

**Comment by shawnh2** [comment]
> I think we should have more histogram metrics for measuring the xds duration.



> I think we should have more histogram metrics for measuring the xds duration.

great! thanks, let me trying add more metrics for this

**Comment by ShyunnY** [comment]
Are you considering adding additional `namespace labels` to metrics? This will facilitate our use of ns select in PromQL.

**Comment by shawnh2** [comment]
> Are you considering adding additional `namespace labels` to metrics? This will facilitate our use of ns select in PromQL.

thanks for reporting, this will be investigate via https://github.com/envoyproxy/gateway/issues/3361

**Review by arkodg — APPROVED** [review]
this is going to be very useful, thanks for adding this !

**Review by zirain — APPROVED** [review]
It would be better if you can update the grafana dashboard.

**Pull request merged**
