### PR TITLE
api: support release channel

### PR DESCRIPTION
**Pull request by zirain**
fix: https://github.com/envoyproxy/gateway/issues/2541

### CODE REVIEW

**Review by cnvergence — APPROVED** [review]
lgtm

**Comment by Xunzhuo** [comment]
Should other policies be included as experimental too ?

**Comment by zirain** [comment]
> Should other policies be included as experimental too ?

wait for decision https://github.com/envoyproxy/gateway/issues/2541

**Comment by zirain** [comment]
kindly ping @arkodg on this

**Comment by zhaohuabing** [comment]
Are release channels and API versions related? For example, could EG have an `Experiment` channel containing V1 API?

**Comment by zirain** [comment]
No longer need this

**Pull request closed without merging**
