### PR TITLE
feat(translator): Set statPrefix for HCM and TCPProxy

### LINKED ISSUE #3160: Enriching the Prometheus metric labels emitted by Envoy from HCM/TcpProxy StatPrefix
*Description*:

> Currently HCM [^1] StatPrefix [^3] can be `http` or `https`, TcpProxy [^2] StatPrefix [^4] can be `tcp`, `passthrough` or `terminate`. That maybe not enough for production usage.

Because it's common to deploy many listeners for different domains, even serve multiple domains by single listener in which domains are distinguished via FilterChainMatch.SNI [^5]. If all listeners share the same StatPrefix, it's difficult to tell how many traffic does specified domain have received. Consider sample from Envoy's `/stats/prometheus`.

```
# TYPE envoy_listener_http_downstream_rq_completed counter
envoy_listener_http_downstream_rq_completed{envoy_http_conn_manager_prefix="https",envoy_listener_address="0.0.0.0_8080"} 0
envoy_listener_http_downstream_rq_completed{envoy_http_conn_manager_prefix="https",envoy_listener_address="0.0.0.0_8081"} 0
envoy_listener_http_downstream_rq_completed{envoy_http_conn_manager_prefix="https",envoy_listener_address="0.0.0.0_8082"} 0
envoy_listener_http_downstream_rq_completed{envoy_http_conn_manager_prefix="https",envoy_listener_address="0.0.0.0_8083"} 0
envoy_listener_http_downstream_rq_completed{envoy_http_conn_manager_prefix="http",envoy_listener_address="0.0.0.0_8084"} 1
envoy_listener_http_downstream_rq_completed{envoy_http_conn_manager_prefix="http",envoy_listener_address="0.0.0.0_8085"} 6
envoy_listener_http_downstream_rq_completed{envoy_http_conn_manager_prefix="http",envoy_listener_address="0.0.0.0_8086"} 0
envoy_listener_http_downstream_rq_completed{envoy_http_conn_manager_prefix="http",envoy_listener_address="0.0.0.0_8087"} 0
envoy_listener_http_downstream_rq_completed{envoy_http_conn_manager_prefix="https",envoy_listener_address="0.0.0.0_7021"} 0
envoy_listener_http_downstream_rq_completed{envoy_http_conn_manager_prefix="https",envoy_listener_address="0.0.0.0_8088"} 0
```

*Relevant Links*:

[^1]: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#extensions-filters-network-http-connection-manager-v3-httpconnectionmanager
[^2]: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto#extensions-filters-network-tcp-proxy-v3-tcpproxy
[^3]: https://github.com/envoyproxy/gateway/blob/32eca0b1a50e44af7acb41cbed77e7f22f6ad378/internal/xds/translator/listener.go#L207
[^4]: https://github.com/envoyproxy/gateway/blob/32eca0b1a50e44af7acb41cbed77e7f22f6ad378/internal/xds/translator/listener.go#L379
[^5]: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto#envoy-v3-api-msg-config-listener-v3-filterchainmatch

### PR DESCRIPTION
**Pull request by aoledk**
**What this PR does / why we need it**:

Improve metric observability.

- set `http-{port}` for HTTP listener
- set `https-{port}` for HTTPS listener
- set `tcp-{port}` for TCP listener
- set `tls-passthrough-{port}` for TLS passthrough listener
- set `tls-terminate-{port}` for TLS terminate listener

**Which issue(s) this PR fixes**:

xref #3160

### CODE REVIEW

**Comment by zirain** [comment]
I'm not sure this's a good idea or not, especially put hostname on stats, which means more memory cost.

**Comment by aoledk** [comment]
I put hostname in statPrefix to allow user to inspect metric of `https` or `terminate` listener on specific hostname. This will leading to more memory cost by envoy stats module and bandwidth cost between envoy and prometheus.

- _contour_ use `{http/https/tcp}-{port}` as statPrefix [^1].
- _emissary_ use `{gatewayNamespace}-{gatewayName}-{listenerIndex}` as statPrefix [^2].
- _istio_ can use multiple ways to set statPrefix [^3], without hostname.

Maybe we can do similar things as _contour_, remove `{hostname}` based on previous proposal.

[^1]: https://github.com/projectcontour/contour/blob/20d2ed91fdd616e1122a64a6520bdd6e4c7016f5/internal/gatewayapi/listeners.go#L184
[^2]: https://github.com/emissary-ingress/emissary/blob/5f7ac3008006082e44f602ac048610d298906ed1/pkg/gateway/gw_transforms.go#L31
[^3]: https://github.com/istio/istio/blob/8f4506bf3d4526d7bee254b9fc390459ba555354/pilot/pkg/networking/core/listener_builder.go#L301

**Comment by zirain** [comment]
> I put hostname in statPrefix to allow user to inspect metric of `https` or `terminate` listener on specific hostname. This will leading to more memory cost by envoy stats module and bandwidth cost between envoy and prometheus.
> 
> * _contour_ use `{http/https/tcp}-{port}` as statPrefix [1](#user-content-fn-1-b906cb0c3081a57f4e22d1586699e8b5).
> * _emissary_ use `{gatewayNamespace}-{gatewayName}-{listenerIndex}` as statPrefix [2](#user-content-fn-2-b906cb0c3081a57f4e22d1586699e8b5).
> * _istio_ can use multiple ways to set statPrefix [3](#user-content-fn-3-b906cb0c3081a57f4e22d1586699e8b5), without hostname.
> 
> Maybe we can do similar things as _contour_, remove `{hostname}` based on previous proposal.
> 
> ## Footnotes
> 1. https://github.com/projectcontour/contour/blob/20d2ed91fdd616e1122a64a6520bdd6e4c7016f5/internal/gatewayapi/listeners.go#L184 [↩](#user-content-fnref-1-b906cb0c3081a57f4e22d1586699e8b5)
> 2. https://github.com/emissary-ingress/emissary/blob/5f7ac3008006082e44f602ac048610d298906ed1/pkg/gateway/gw_transforms.go#L31 [↩](#user-content-fnref-2-b906cb0c3081a57f4e22d1586699e8b5)
> 3. https://github.com/istio/istio/blob/8f4506bf3d4526d7bee254b9fc390459ba555354/pilot/pkg/networking/core/listener_builder.go#L301 [↩](#user-content-fnref-3-b906cb0c3081a57f4e22d1586699e8b5)

it should be as concise as possible or user input.

**Comment by aoledk** [comment]
Then I prefer to `{http/https/tcp/passthrough/terminate}-{port}`, what's your option ? @zirain

**Comment by zirain** [comment]
> Then I prefer to `{http/https/tcp/passthrough/terminate}-{port}`, usually port maybe configured on cloud provider's load balancer target group, what's your option ? @zirain

looks better, what's the different between https/passthrough/terminate?

**Comment by aoledk** [comment]
`http` / `tcp` / `https` / `passthrough` / `terminate` are current statPrefix for HCM or TCPProxy:

- `https` for HTTPS listener with TLS certificates.
- `passthrough` for TLS listener without TLS certificates, just to inspect SNI for routing.
- `terminate` for TLS listener with TLS certificates.

**Comment by zirain** [comment]
> `http` / `tcp` / `https` / `passthrough` / `terminate` are current statPrefix for HCM or TCPProxy:
> 
> * `https` for HTTPS listener with TLS certificates.
> * `passthrough` for TLS listener without TLS certificates, just to inspect SNI for routing.
> * `terminate` for TLS listener with TLS certificates.

what's the different between HTTPS and TLS?

**Comment by zhaohuabing** [comment]
> > `http` / `tcp` / `https` / `passthrough` / `terminate` are current statPrefix for HCM or TCPProxy:
> > 
> > * `https` for HTTPS listener with TLS certificates.
> > * `passthrough` for TLS listener without TLS certificates, just to inspect SNI for routing.
> > * `terminate` for TLS listener with TLS certificates.
> 
> what's the different between HTTPS and TLS?

I think the alpn is HTTP vs others. These terminologies are quite confusing, I need to think a moment every time I see them.

These names could be more explicit: http/tcp/https/tcp-passthrought/tcp-terminate

**Comment by aoledk** [comment]
https means it's a Gateway API listener whose protocol is HTTPS, will be HCM eventually. tls means it's a Gateway API listener whose protocol is TLS, will be TCPProxy eventually.

**Comment by aoledk** [comment]
> > > `http` / `tcp` / `https` / `passthrough` / `terminate` are current statPrefix for HCM or TCPProxy:
> 
> > > 
> 
> > > * `https` for HTTPS listener with TLS certificates.
> 
> > > * `passthrough` for TLS listener without TLS certificates, just to inspect SNI for routing.
> 
> > > * `terminate` for TLS listener with TLS certificates.
> 
> > 
> 
> > what's the different between HTTPS and TLS?
> 
> 
> 
> I think the alpns are HTTP vs others. These terminologies are quite confusing, I need to think a moment every time I see them.
> 
> 
> 
> These names could be more explicit: (plain)http/https(-terminate)/(plain)tcp/tls-passthrought/tls-terminate

Leading with tls prefix for passthrough and terminate is a good idea.

**Comment by zhaohuabing** [comment]
@aoledk In the example of this issue https://github.com/envoyproxy/gateway/issues/3160 ,  port is a lable of the metric. Do all the metrics have the port label? If that's the case, we don't need to add a port to the stats prefix.

**Comment by aoledk** [comment]
> @aoledk In the example of this issue #3160 , port is part of the `envoy_listener_address` lable of the metric. Do all the metrics have this label? If that's the case, we don't need to add the port to the stats prefix.
> 
> envoy_listener_http_downstream_rq_completed{envoy_http_conn_manager_prefix="https",envoy_listener_address="0.0.0.0_8080"} 0

Only [`Per listener statistics`](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/stats#per-listener-statistics) of HCM will have `envoy_listener_address` tag and it just covers very small part of all metrics of HCM. TCPProxy doesn't have `Per listener statistics` like HCM.

So IMO port should be added to statPrefix.

**Review by zhaohuabing — APPROVED** [review]
LGTM. Thanks for adding the "tls-" prefix, which makes the stat prefix easier to understand.

**Comment by guydc** [comment]
@aoledk - can you regenerate and update the PR description?

**Comment by aoledk** [comment]
> @aoledk - can you regenerate and update the PR description?

Done.

**Review by zhaohuabing — APPROVED** [review]

**Review by zhaohuabing — APPROVED** [review]

**Comment by arkodg** [comment]
can you check why tests are failing @aoledk ?
also would be great if you can share what the metrics looked like now vs earlier

**Comment by aoledk** [comment]
> can you check why tests are failing @aoledk ? also would be great if you can share what the metrics looked like now vs earlier

previous looks like

```
envoy_http_downstream_rq_total{envoy_http_conn_manager_prefix="admin"} 19
envoy_http_downstream_rq_total{envoy_http_conn_manager_prefix="eg-ready-http"} 45
envoy_http_downstream_rq_total{envoy_http_conn_manager_prefix="http-10080"} 0
```

now looks like

```
envoy_http_downstream_rq_total{envoy_http_conn_manager_prefix="admin"} 19
envoy_http_downstream_rq_total{envoy_http_conn_manager_prefix="eg-ready-http"} 45
envoy_http_downstream_rq_total{envoy_http_conn_manager_prefix="http"} 0
```

**Comment by arkodg** [comment]
thanks for fixing the e2e test @aoledk, does this change impact the grafana dashboards as well https://gateway.envoyproxy.io/docs/tasks/observability/grafana-integration/
cc @shawnh2

**Review by zirain — APPROVED** [review]
LGTM, thanks for adding this.

**Pull request merged**
