### PR TITLE
fix: allow websockets in url rewrite

### LINKED ISSUE #2989: URLRewrite filter not working with websockets
Hi. The `URLRewrite` filter on the `HTTPRoute`, which works fine with regular HTTP requests, seems not to be working with websockets respectively fails when the websocket protocol upgrade is performed. I am not sure if this is a problem with envoy itself or with envoy gateway. But what I did is using a [simple HTTP/WS echo server](https://github.com/jmalloc/echo-server) and the following `HTTPRoute`:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: websocket-echo
  namespace: default
spec:
  hostnames:
  - ws.example.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-gateway-https
    namespace: default
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: websocket-echo
      port: 8080
      weight: 1
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          replaceFullPath: /
          type: ReplaceFullPath
    matches:
    - path:
        type: Exact
        value: /echo
```
While regular HTTP requests are echoed back just fine, above config results in `error: Unexpected server response: 403` on the client side when trying to establish a websocket connection to `https://ws.example.com/echo` with e.g. [wscat](https://github.com/websockets/wscat).
On the envoy proxy you can see the following log:

```json
{
  "start_time": "2024-03-20T12:26:30.465Z",
  "method": "GET",
  "x-envoy-origin-path": "/echo",
  "protocol": "HTTP/1.1",
  "response_code": "403",
  "response_flags": "-",
  "response_code_details": "upgrade_failed",
  "connection_termination_details": "-",
  "upstream_transport_failure_reason": "-",
  "bytes_received": "0",
  "bytes_sent": "0",
  "duration": "0",
  "x-envoy-upstream-service-time": "-",
  "x-forwarded-for": "<redacted>",
  "user-agent": "-",
  "x-request-id": "e6e15a68-c012-482f-9fd9-f71b873e9e68",
  ":authority": "ws.example.com",
  "upstream_host": "-",
  "upstream_cluster": "httproute/default/websocket-echo/rule/0",
  "upstream_local_address": "-",
  "downstream_local_address": "<redacted>",
  "downstream_remote_address": "<redacted>",
  "requested_server_name": "-",
  "route_name": "httproute/default/websocket-echo/rule/0/match/0/ws_example_com"
}
```

If I remove the filter from the `HTTPRoute` websocket connections can be established without any problems.

### PR DESCRIPTION
**Pull request by zetaab**
**What type of PR is this?**

fix: allow websockets in url rewrite 

**What this PR does / why we need it**:

This will add websocket UpgradeConfig to urlrewrite case.

**Which issue(s) this PR fixes**:

Fixes #2989

cc @arkodg

### CODE REVIEW

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Review by zirain — APPROVED** [review]

**Review by cnvergence — APPROVED** [review]

**Comment by zirain** [comment]
add label to verify github action

**Comment by arkodg** [comment]
We also need @Xunzhuo to approve then

**Comment by zirain** [comment]
> We also need @Xunzhuo to approve then

just want to make sure bot will create the PR.

**Comment by zirain** [comment]
wait https://github.com/envoyproxy/gateway/pull/3039

**Pull request merged**
