### PR TITLE
chore: use most recent gateway api conformance backend

### PR DESCRIPTION
**Pull request by guydc**
**What this PR does / why we need it**:
Gateway API changed their conformance tests to use a different echo server a while ago: https://github.com/kubernetes-sigs/gateway-api/pull/2468. The new server is maintained by the Gateway API project (https://github.com/kubernetes-sigs/gateway-api/tree/main/conformance/echo-basic) and includes additional functionality like delayed response. 

The enhanced feature set can be useful for testing scenarios like circuit breakers, connection limits, backend timeouts, etc. 

Raising this PR to see if there are any e2e tests that fail due to change in server.

### CODE REVIEW

**Comment by arkodg** [comment]
thanks @guydc, can we also fix use this image in quick start and other user guides :)

**Review by arkodg — DISMISSED** [review]

**Comment by guydc** [comment]
sorry for force-push, I started from scratch after breaking something in the docs gen. 
Also added egctl tests and removed `httpbin` from the circuit breakers user guide.

**Review by shawnh2 — APPROVED** [review]
LGTM

**Review by arkodg — APPROVED** [review]

**Pull request merged**
