### PR TITLE
reuse filewatcher

### PR DESCRIPTION
**Pull request by zirain**
1. reuse `filewatcher` package
2. move code under `util`

### CODE REVIEW

**Comment by zirain** [comment]
cc @shawnh2 PTAL

**Review by shawnh2 — COMMENTED** [review]
Done some test, seems running `envoy-gateway server -c config.yaml` with `config.yaml`:

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyGateway
gateway:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
provider:
  type: Custom
  custom:
    resource:
      type: File
      file:
        paths: ["test/"]
logging:
  level:
    default: info
```

cannot catch any modifications under the `paths`.

**Comment by zirain** [comment]
@shawnh2 can you review and test this again?

**Comment by zirain** [comment]
@shawnh2 seems you have more idea, I'd like close this one.

**Pull request closed without merging**
