### PR TITLE
chore: upgrade test should use v1.1.0 by default

### PR DESCRIPTION
**Pull request by guydc**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Review by arkodg — APPROVED** [review]

**Review by shawnh2 — APPROVED** [review]
/retest

**Review by zhaohuabing — APPROVED** [review]

**Comment by guydc** [comment]
looks like we have a legitimate v1.1 => main upgrade issue

**Pull request closed without merging**
