### PR TITLE
Test data to demonstrate wrong validation of namespaces

### PR DESCRIPTION
**Pull request by sadovnikov**
**What type of PR is this?**

This PR extends the test files with one `SecurityPolicy` and `HTTPRoute` in a different namespace, to demonstrate #3918

### CODE REVIEW

**Comment by zhaohuabing** [comment]
@sadovnikov Looks like the output file is incorrect, could you please run `make gen-check` and submit the change?

**Comment by sadovnikov** [comment]
@zhaohuabing, I updated the testdata files. However, the testing setup does not want to accept a new namespace. 
The new `gateway-3` should be accepting routes from all namespaces, but it does not

image

**Comment by zhaohuabing** [comment]
> @zhaohuabing, I updated the testdata files. However, the testing setup does not want to accept a new namespace. The new `gateway-3` should be accepting routes from all namespaces, but it does not

Hi @sadovnikov you can just add the `other-ns` namespace in the .in.yaml

```yaml
namespaces:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: other-ns
```

**Comment by sadovnikov** [comment]
Hi @zhaohuabing, thanks a lot for the tip about the namespace creation!

Unfortunately, status of neither HTTPRoutes nor SecurityPolicy status reflects the link between the two. However, from the empty `status.ancestors` of the `target-route-in-other-ns` policy, I conclude that this [condition](https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/securitypolicy.go#L269-L278) never gets matched and the code can be removed? Do you agree with this conclusion and with #3918?

```- apiVersion: gateway.envoyproxy.io/v1alpha1
  kind: SecurityPolicy
  metadata:
    creationTimestamp: null
    name: target-route-in-other-ns
    namespace: envoy-gateway
  spec:
    targetRef:
      group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: httproute-other-ns
  status:
    ancestors: null
```

**Comment by zhaohuabing** [comment]
> Hi @zhaohuabing, thanks a lot for the tip about the namespace creation!
> 
> Unfortunately, status of neither `HTTPRoute` nor `SecurityPolicy` reflects the link between the two. However, from the empty `status.ancestors` of the `target-route-in-other-ns` policy, I conclude that this [condition](https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/securitypolicy.go#L269-L278) never gets matched and the code can be removed? Do you agree with this conclusion and with #3918?
> 
> ```
>   kind: SecurityPolicy
>   metadata:
>     creationTimestamp: null
>     name: target-route-in-other-ns
>     namespace: envoy-gateway
>   spec:
>     targetRef:
>       group: gateway.networking.k8s.io
>       kind: HTTPRoute
>       name: httproute-other-ns
>   status:
>     ancestors: null
> ```

@sadovnikov The ancestor is null because the gateway api translator can't find the referenced `HTTPRoute envoy-gateway/httproute-other-ns` of the `SecurityPolicy`. Unlike `Gateway` and `HTTPRoute`, the `SecurityPolicy` doesn't have an affinity to a `GatewayClass`. Therefor, the translator doesn't know whether the HTTPRoute doesn't exist or simply doesn't belong to the current translator.

**Comment by sadovnikov** [comment]
Hi @zhaohuabing, the point I'm trying to make is that this [assignment](https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/securitypolicy.go#L251) and the following  [condition check](https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/securitypolicy.go#L269-L278) are incorrect.

**Comment by zhaohuabing** [comment]
> Reference in new issue

I got it. This checking is not needed anymore as cross-namespace references are not supported for policies.

**Comment by sadovnikov** [comment]
@zhaohuabing, thank you very much for #3961 👍 
Should this PR be merged if you find the new test cases useful? or closed?

**Comment by zhaohuabing** [comment]
Let's close this PR for now. If cross-ns references need to be supported, we can add tests for that later.

**Pull request closed without merging**
