### PR TITLE
feat: Support for converting JWT claims into HTTP headers

### PR DESCRIPTION
**Pull request by tmsnan**
Description:
Support ratelimit based on jwt claims
Relates to #851 #1489

### CODE REVIEW

**Comment by tmsnan** [comment]
I want to add `doc/rate-limit` for ratelimit based jwt claims, but I need to use two different jwt tokens. At present, I only find [one jwt token](https://raw.githubusercontent.com/envoyproxy/gateway/main/examples/kubernetes/authn/test.jwt) on the `User Guides`. How should I add another jwt token.

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Comment by arkodg** [comment]
> I want to add `doc/rate-limit` for ratelimit based jwt claims, but I need to use two different jwt tokens. At present, I only find [one jwt token](https://raw.githubusercontent.com/envoyproxy/gateway/main/examples/kubernetes/authn/test.jwt) on the `User Guides`. How should I add another jwt token? Of course, using the same jwt token is also a verification method by changing the ratelimit matching conditions, but this is a little informal.

they are saved here https://github.com/envoyproxy/gateway/tree/main/examples/kubernetes/authn
you could create another one for ratelimiting or use the same one

**Comment by tmsnan** [comment]
> > I want to add `doc/rate-limit` for ratelimit based jwt claims, but I need to use two different jwt tokens. At present, I only find [one jwt token](https://raw.githubusercontent.com/envoyproxy/gateway/main/examples/kubernetes/authn/test.jwt) on the `User Guides`. How should I add another jwt token? Of course, using the same jwt token is also a verification method by changing the ratelimit matching conditions, but this is a little informal.
> 
> they are saved here https://github.com/envoyproxy/gateway/tree/main/examples/kubernetes/authn you could create another one for ratelimiting or use the same one

 Thanks!

**Review by zirain — APPROVED** [review]

**Pull request merged**
